// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: banner.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Banner struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageUrl      string                 `protobuf:"bytes,1,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	Action        *TransitionAction      `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	Id            uint32                 `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	Width         uint32                 `protobuf:"varint,4,opt,name=width,proto3" json:"width,omitempty"`
	Height        uint32                 `protobuf:"varint,5,opt,name=height,proto3" json:"height,omitempty"`
	IsPr          bool                   `protobuf:"varint,6,opt,name=is_pr,json=isPr,proto3" json:"is_pr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Banner) Reset() {
	*x = Banner{}
	mi := &file_banner_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Banner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Banner) ProtoMessage() {}

func (x *Banner) ProtoReflect() protoreflect.Message {
	mi := &file_banner_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Banner.ProtoReflect.Descriptor instead.
func (*Banner) Descriptor() ([]byte, []int) {
	return file_banner_proto_rawDescGZIP(), []int{0}
}

func (x *Banner) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *Banner) GetAction() *TransitionAction {
	if x != nil {
		return x.Action
	}
	return nil
}

func (x *Banner) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Banner) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Banner) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Banner) GetIsPr() bool {
	if x != nil {
		return x.IsPr
	}
	return false
}

var File_banner_proto protoreflect.FileDescriptor

const file_banner_proto_rawDesc = "" +
	"\n" +
	"\fbanner.proto\x12\x16jp.co.comic.jump.proto\x1a\x17transition_action.proto\"\xba\x01\n" +
	"\x06Banner\x12\x1b\n" +
	"\timage_url\x18\x01 \x01(\tR\bimageUrl\x12@\n" +
	"\x06action\x18\x02 \x01(\v2(.jp.co.comic.jump.proto.TransitionActionR\x06action\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\rR\x02id\x12\x14\n" +
	"\x05width\x18\x04 \x01(\rR\x05width\x12\x16\n" +
	"\x06height\x18\x05 \x01(\rR\x06height\x12\x13\n" +
	"\x05is_pr\x18\x06 \x01(\bR\x04isPrb\x06proto3"

var (
	file_banner_proto_rawDescOnce sync.Once
	file_banner_proto_rawDescData []byte
)

func file_banner_proto_rawDescGZIP() []byte {
	file_banner_proto_rawDescOnce.Do(func() {
		file_banner_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_banner_proto_rawDesc), len(file_banner_proto_rawDesc)))
	})
	return file_banner_proto_rawDescData
}

var file_banner_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_banner_proto_goTypes = []any{
	(*Banner)(nil),           // 0: jp.co.comic.jump.proto.Banner
	(*TransitionAction)(nil), // 1: jp.co.comic.jump.proto.TransitionAction
}
var file_banner_proto_depIdxs = []int32{
	1, // 0: jp.co.comic.jump.proto.Banner.action:type_name -> jp.co.comic.jump.proto.TransitionAction
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_banner_proto_init() }
func file_banner_proto_init() {
	if File_banner_proto != nil {
		return
	}
	file_transition_action_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_banner_proto_rawDesc), len(file_banner_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_banner_proto_goTypes,
		DependencyIndexes: file_banner_proto_depIdxs,
		MessageInfos:      file_banner_proto_msgTypes,
	}.Build()
	File_banner_proto = out.File
	file_banner_proto_goTypes = nil
	file_banner_proto_depIdxs = nil
}
