// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: chapter.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChapterType int32

const (
	ChapterType_FREE                   ChapterType = 0
	ChapterType_FREE_FOR_FIRST_TIME    ChapterType = 1
	ChapterType_STANDARD               ChapterType = 2
	ChapterType_DELUXE                 ChapterType = 3
	ChapterType_LOCKED_AFTER_FREE_READ ChapterType = 4
)

// Enum value maps for ChapterType.
var (
	ChapterType_name = map[int32]string{
		0: "FREE",
		1: "FREE_FOR_FIRST_TIME",
		2: "STANDARD",
		3: "DELUXE",
		4: "LOCKED_AFTER_FREE_READ",
	}
	ChapterType_value = map[string]int32{
		"FREE":                   0,
		"FREE_FOR_FIRST_TIME":    1,
		"STANDARD":               2,
		"DELUXE":                 3,
		"LOCKED_AFTER_FREE_READ": 4,
	}
)

func (x ChapterType) Enum() *ChapterType {
	p := new(ChapterType)
	*p = x
	return p
}

func (x ChapterType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChapterType) Descriptor() protoreflect.EnumDescriptor {
	return file_chapter_proto_enumTypes[0].Descriptor()
}

func (ChapterType) Type() protoreflect.EnumType {
	return &file_chapter_proto_enumTypes[0]
}

func (x ChapterType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChapterType.Descriptor instead.
func (ChapterType) EnumDescriptor() ([]byte, []int) {
	return file_chapter_proto_rawDescGZIP(), []int{0}
}

type Chapter struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	TitleId              uint32                 `protobuf:"varint,1,opt,name=title_id,json=titleId,proto3" json:"title_id,omitempty"`
	ChapterId            uint32                 `protobuf:"varint,2,opt,name=chapter_id,json=chapterId,proto3" json:"chapter_id,omitempty"`
	Name                 string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	SubTitle             string                 `protobuf:"bytes,4,opt,name=sub_title,json=subTitle,proto3" json:"sub_title,omitempty"`
	ThumbnailUrl         string                 `protobuf:"bytes,5,opt,name=thumbnail_url,json=thumbnailUrl,proto3" json:"thumbnail_url,omitempty"`
	StartTimeStamp       uint32                 `protobuf:"varint,6,opt,name=start_time_stamp,json=startTimeStamp,proto3" json:"start_time_stamp,omitempty"`
	EndTimeStamp         uint32                 `protobuf:"varint,7,opt,name=end_time_stamp,json=endTimeStamp,proto3" json:"end_time_stamp,omitempty"`
	AlreadyViewed        bool                   `protobuf:"varint,8,opt,name=already_viewed,json=alreadyViewed,proto3" json:"already_viewed,omitempty"`
	IsVerticalOnly       bool                   `protobuf:"varint,9,opt,name=is_vertical_only,json=isVerticalOnly,proto3" json:"is_vertical_only,omitempty"`
	ChapterTicketEndtime uint32                 `protobuf:"varint,10,opt,name=chapter_ticket_endtime,json=chapterTicketEndtime,proto3" json:"chapter_ticket_endtime,omitempty"`
	ViewedForFree        bool                   `protobuf:"varint,11,opt,name=viewed_for_free,json=viewedForFree,proto3" json:"viewed_for_free,omitempty"`
	IsHorizontalOnly     bool                   `protobuf:"varint,12,opt,name=is_horizontal_only,json=isHorizontalOnly,proto3" json:"is_horizontal_only,omitempty"`
	ViewCount            uint32                 `protobuf:"varint,13,opt,name=view_count,json=viewCount,proto3" json:"view_count,omitempty"`
	CommentCount         uint32                 `protobuf:"varint,14,opt,name=comment_count,json=commentCount,proto3" json:"comment_count,omitempty"`
	IsUpdated            bool                   `protobuf:"varint,15,opt,name=is_updated,json=isUpdated,proto3" json:"is_updated,omitempty"`
	ChapterType          ChapterType            `protobuf:"varint,16,opt,name=chapter_type,json=chapterType,proto3,enum=jp.co.comic.jump.proto.ChapterType" json:"chapter_type,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Chapter) Reset() {
	*x = Chapter{}
	mi := &file_chapter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chapter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chapter) ProtoMessage() {}

func (x *Chapter) ProtoReflect() protoreflect.Message {
	mi := &file_chapter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chapter.ProtoReflect.Descriptor instead.
func (*Chapter) Descriptor() ([]byte, []int) {
	return file_chapter_proto_rawDescGZIP(), []int{0}
}

func (x *Chapter) GetTitleId() uint32 {
	if x != nil {
		return x.TitleId
	}
	return 0
}

func (x *Chapter) GetChapterId() uint32 {
	if x != nil {
		return x.ChapterId
	}
	return 0
}

func (x *Chapter) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Chapter) GetSubTitle() string {
	if x != nil {
		return x.SubTitle
	}
	return ""
}

func (x *Chapter) GetThumbnailUrl() string {
	if x != nil {
		return x.ThumbnailUrl
	}
	return ""
}

func (x *Chapter) GetStartTimeStamp() uint32 {
	if x != nil {
		return x.StartTimeStamp
	}
	return 0
}

func (x *Chapter) GetEndTimeStamp() uint32 {
	if x != nil {
		return x.EndTimeStamp
	}
	return 0
}

func (x *Chapter) GetAlreadyViewed() bool {
	if x != nil {
		return x.AlreadyViewed
	}
	return false
}

func (x *Chapter) GetIsVerticalOnly() bool {
	if x != nil {
		return x.IsVerticalOnly
	}
	return false
}

func (x *Chapter) GetChapterTicketEndtime() uint32 {
	if x != nil {
		return x.ChapterTicketEndtime
	}
	return 0
}

func (x *Chapter) GetViewedForFree() bool {
	if x != nil {
		return x.ViewedForFree
	}
	return false
}

func (x *Chapter) GetIsHorizontalOnly() bool {
	if x != nil {
		return x.IsHorizontalOnly
	}
	return false
}

func (x *Chapter) GetViewCount() uint32 {
	if x != nil {
		return x.ViewCount
	}
	return 0
}

func (x *Chapter) GetCommentCount() uint32 {
	if x != nil {
		return x.CommentCount
	}
	return 0
}

func (x *Chapter) GetIsUpdated() bool {
	if x != nil {
		return x.IsUpdated
	}
	return false
}

func (x *Chapter) GetChapterType() ChapterType {
	if x != nil {
		return x.ChapterType
	}
	return ChapterType_FREE
}

var File_chapter_proto protoreflect.FileDescriptor

const file_chapter_proto_rawDesc = "" +
	"\n" +
	"\rchapter.proto\x12\x16jp.co.comic.jump.proto\"\xf1\x04\n" +
	"\aChapter\x12\x19\n" +
	"\btitle_id\x18\x01 \x01(\rR\atitleId\x12\x1d\n" +
	"\n" +
	"chapter_id\x18\x02 \x01(\rR\tchapterId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1b\n" +
	"\tsub_title\x18\x04 \x01(\tR\bsubTitle\x12#\n" +
	"\rthumbnail_url\x18\x05 \x01(\tR\fthumbnailUrl\x12(\n" +
	"\x10start_time_stamp\x18\x06 \x01(\rR\x0estartTimeStamp\x12$\n" +
	"\x0eend_time_stamp\x18\a \x01(\rR\fendTimeStamp\x12%\n" +
	"\x0ealready_viewed\x18\b \x01(\bR\ralreadyViewed\x12(\n" +
	"\x10is_vertical_only\x18\t \x01(\bR\x0eisVerticalOnly\x124\n" +
	"\x16chapter_ticket_endtime\x18\n" +
	" \x01(\rR\x14chapterTicketEndtime\x12&\n" +
	"\x0fviewed_for_free\x18\v \x01(\bR\rviewedForFree\x12,\n" +
	"\x12is_horizontal_only\x18\f \x01(\bR\x10isHorizontalOnly\x12\x1d\n" +
	"\n" +
	"view_count\x18\r \x01(\rR\tviewCount\x12#\n" +
	"\rcomment_count\x18\x0e \x01(\rR\fcommentCount\x12\x1d\n" +
	"\n" +
	"is_updated\x18\x0f \x01(\bR\tisUpdated\x12F\n" +
	"\fchapter_type\x18\x10 \x01(\x0e2#.jp.co.comic.jump.proto.ChapterTypeR\vchapterType*f\n" +
	"\vChapterType\x12\b\n" +
	"\x04FREE\x10\x00\x12\x17\n" +
	"\x13FREE_FOR_FIRST_TIME\x10\x01\x12\f\n" +
	"\bSTANDARD\x10\x02\x12\n" +
	"\n" +
	"\x06DELUXE\x10\x03\x12\x1a\n" +
	"\x16LOCKED_AFTER_FREE_READ\x10\x04b\x06proto3"

var (
	file_chapter_proto_rawDescOnce sync.Once
	file_chapter_proto_rawDescData []byte
)

func file_chapter_proto_rawDescGZIP() []byte {
	file_chapter_proto_rawDescOnce.Do(func() {
		file_chapter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chapter_proto_rawDesc), len(file_chapter_proto_rawDesc)))
	})
	return file_chapter_proto_rawDescData
}

var file_chapter_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_chapter_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_chapter_proto_goTypes = []any{
	(ChapterType)(0), // 0: jp.co.comic.jump.proto.ChapterType
	(*Chapter)(nil),  // 1: jp.co.comic.jump.proto.Chapter
}
var file_chapter_proto_depIdxs = []int32{
	0, // 0: jp.co.comic.jump.proto.Chapter.chapter_type:type_name -> jp.co.comic.jump.proto.ChapterType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_chapter_proto_init() }
func file_chapter_proto_init() {
	if File_chapter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chapter_proto_rawDesc), len(file_chapter_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_chapter_proto_goTypes,
		DependencyIndexes: file_chapter_proto_depIdxs,
		EnumInfos:         file_chapter_proto_enumTypes,
		MessageInfos:      file_chapter_proto_msgTypes,
	}.Build()
	File_chapter_proto = out.File
	file_chapter_proto_goTypes = nil
	file_chapter_proto_depIdxs = nil
}
