// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: comment_list_view.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommentListView struct {
	state              protoimpl.MessageState              `protogen:"open.v1"`
	Comments           []*Comment                          `protobuf:"bytes,1,rep,name=comments,proto3" json:"comments,omitempty"`
	IfSetUserName      bool                                `protobuf:"varint,2,opt,name=if_set_user_name,json=ifSetUserName,proto3" json:"if_set_user_name,omitempty"`
	TitleDetailComment *CommentListView_TitleDetailComment `protobuf:"bytes,3,opt,name=title_detail_comment,json=titleDetailComment,proto3" json:"title_detail_comment,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CommentListView) Reset() {
	*x = CommentListView{}
	mi := &file_comment_list_view_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentListView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentListView) ProtoMessage() {}

func (x *CommentListView) ProtoReflect() protoreflect.Message {
	mi := &file_comment_list_view_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentListView.ProtoReflect.Descriptor instead.
func (*CommentListView) Descriptor() ([]byte, []int) {
	return file_comment_list_view_proto_rawDescGZIP(), []int{0}
}

func (x *CommentListView) GetComments() []*Comment {
	if x != nil {
		return x.Comments
	}
	return nil
}

func (x *CommentListView) GetIfSetUserName() bool {
	if x != nil {
		return x.IfSetUserName
	}
	return false
}

func (x *CommentListView) GetTitleDetailComment() *CommentListView_TitleDetailComment {
	if x != nil {
		return x.TitleDetailComment
	}
	return nil
}

type CommentListView_TitleDetailComment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TitleId       uint32                 `protobuf:"varint,1,opt,name=title_id,json=titleId,proto3" json:"title_id,omitempty"`
	TitleName     string                 `protobuf:"bytes,2,opt,name=title_name,json=titleName,proto3" json:"title_name,omitempty"`
	ChapterName   string                 `protobuf:"bytes,3,opt,name=chapter_name,json=chapterName,proto3" json:"chapter_name,omitempty"`
	Credit        string                 `protobuf:"bytes,4,opt,name=credit,proto3" json:"credit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommentListView_TitleDetailComment) Reset() {
	*x = CommentListView_TitleDetailComment{}
	mi := &file_comment_list_view_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentListView_TitleDetailComment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentListView_TitleDetailComment) ProtoMessage() {}

func (x *CommentListView_TitleDetailComment) ProtoReflect() protoreflect.Message {
	mi := &file_comment_list_view_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentListView_TitleDetailComment.ProtoReflect.Descriptor instead.
func (*CommentListView_TitleDetailComment) Descriptor() ([]byte, []int) {
	return file_comment_list_view_proto_rawDescGZIP(), []int{0, 0}
}

func (x *CommentListView_TitleDetailComment) GetTitleId() uint32 {
	if x != nil {
		return x.TitleId
	}
	return 0
}

func (x *CommentListView_TitleDetailComment) GetTitleName() string {
	if x != nil {
		return x.TitleName
	}
	return ""
}

func (x *CommentListView_TitleDetailComment) GetChapterName() string {
	if x != nil {
		return x.ChapterName
	}
	return ""
}

func (x *CommentListView_TitleDetailComment) GetCredit() string {
	if x != nil {
		return x.Credit
	}
	return ""
}

var File_comment_list_view_proto protoreflect.FileDescriptor

const file_comment_list_view_proto_rawDesc = "" +
	"\n" +
	"\x17comment_list_view.proto\x12\x16jp.co.comic.jump.proto\x1a\rcomment.proto\"\xf1\x02\n" +
	"\x0fCommentListView\x12;\n" +
	"\bcomments\x18\x01 \x03(\v2\x1f.jp.co.comic.jump.proto.CommentR\bcomments\x12'\n" +
	"\x10if_set_user_name\x18\x02 \x01(\bR\rifSetUserName\x12l\n" +
	"\x14title_detail_comment\x18\x03 \x01(\v2:.jp.co.comic.jump.proto.CommentListView.TitleDetailCommentR\x12titleDetailComment\x1a\x89\x01\n" +
	"\x12TitleDetailComment\x12\x19\n" +
	"\btitle_id\x18\x01 \x01(\rR\atitleId\x12\x1d\n" +
	"\n" +
	"title_name\x18\x02 \x01(\tR\ttitleName\x12!\n" +
	"\fchapter_name\x18\x03 \x01(\tR\vchapterName\x12\x16\n" +
	"\x06credit\x18\x04 \x01(\tR\x06creditb\x06proto3"

var (
	file_comment_list_view_proto_rawDescOnce sync.Once
	file_comment_list_view_proto_rawDescData []byte
)

func file_comment_list_view_proto_rawDescGZIP() []byte {
	file_comment_list_view_proto_rawDescOnce.Do(func() {
		file_comment_list_view_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_comment_list_view_proto_rawDesc), len(file_comment_list_view_proto_rawDesc)))
	})
	return file_comment_list_view_proto_rawDescData
}

var file_comment_list_view_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_comment_list_view_proto_goTypes = []any{
	(*CommentListView)(nil),                    // 0: jp.co.comic.jump.proto.CommentListView
	(*CommentListView_TitleDetailComment)(nil), // 1: jp.co.comic.jump.proto.CommentListView.TitleDetailComment
	(*Comment)(nil),                            // 2: jp.co.comic.jump.proto.Comment
}
var file_comment_list_view_proto_depIdxs = []int32{
	2, // 0: jp.co.comic.jump.proto.CommentListView.comments:type_name -> jp.co.comic.jump.proto.Comment
	1, // 1: jp.co.comic.jump.proto.CommentListView.title_detail_comment:type_name -> jp.co.comic.jump.proto.CommentListView.TitleDetailComment
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_comment_list_view_proto_init() }
func file_comment_list_view_proto_init() {
	if File_comment_list_view_proto != nil {
		return
	}
	file_comment_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_comment_list_view_proto_rawDesc), len(file_comment_list_view_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_comment_list_view_proto_goTypes,
		DependencyIndexes: file_comment_list_view_proto_depIdxs,
		MessageInfos:      file_comment_list_view_proto_msgTypes,
	}.Build()
	File_comment_list_view_proto = out.File
	file_comment_list_view_proto_goTypes = nil
	file_comment_list_view_proto_depIdxs = nil
}
