// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: dialogue.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FirstTimeFreePlatform int32

const (
	FirstTimeFreePlatform_DISABLED FirstTimeFreePlatform = 0
	FirstTimeFreePlatform_WEB      FirstTimeFreePlatform = 1
	FirstTimeFreePlatform_APP      FirstTimeFreePlatform = 2
)

// Enum value maps for FirstTimeFreePlatform.
var (
	FirstTimeFreePlatform_name = map[int32]string{
		0: "DISABLED",
		1: "WEB",
		2: "APP",
	}
	FirstTimeFreePlatform_value = map[string]int32{
		"DISABLED": 0,
		"WEB":      1,
		"APP":      2,
	}
)

func (x FirstTimeFreePlatform) Enum() *FirstTimeFreePlatform {
	p := new(FirstTimeFreePlatform)
	*p = x
	return p
}

func (x FirstTimeFreePlatform) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FirstTimeFreePlatform) Descriptor() protoreflect.EnumDescriptor {
	return file_dialogue_proto_enumTypes[0].Descriptor()
}

func (FirstTimeFreePlatform) Type() protoreflect.EnumType {
	return &file_dialogue_proto_enumTypes[0]
}

func (x FirstTimeFreePlatform) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FirstTimeFreePlatform.Descriptor instead.
func (FirstTimeFreePlatform) EnumDescriptor() ([]byte, []int) {
	return file_dialogue_proto_rawDescGZIP(), []int{0}
}

type FreeViewDialogue struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Platform        FirstTimeFreePlatform  `protobuf:"varint,1,opt,name=platform,proto3,enum=jp.co.comic.jump.proto.FirstTimeFreePlatform" json:"platform,omitempty"`
	DialogueUrl     string                 `protobuf:"bytes,2,opt,name=dialogue_url,json=dialogueUrl,proto3" json:"dialogue_url,omitempty"`
	PublisherBanner *Banner                `protobuf:"bytes,3,opt,name=publisher_banner,json=publisherBanner,proto3" json:"publisher_banner,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FreeViewDialogue) Reset() {
	*x = FreeViewDialogue{}
	mi := &file_dialogue_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FreeViewDialogue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FreeViewDialogue) ProtoMessage() {}

func (x *FreeViewDialogue) ProtoReflect() protoreflect.Message {
	mi := &file_dialogue_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FreeViewDialogue.ProtoReflect.Descriptor instead.
func (*FreeViewDialogue) Descriptor() ([]byte, []int) {
	return file_dialogue_proto_rawDescGZIP(), []int{0}
}

func (x *FreeViewDialogue) GetPlatform() FirstTimeFreePlatform {
	if x != nil {
		return x.Platform
	}
	return FirstTimeFreePlatform_DISABLED
}

func (x *FreeViewDialogue) GetDialogueUrl() string {
	if x != nil {
		return x.DialogueUrl
	}
	return ""
}

func (x *FreeViewDialogue) GetPublisherBanner() *Banner {
	if x != nil {
		return x.PublisherBanner
	}
	return nil
}

var File_dialogue_proto protoreflect.FileDescriptor

const file_dialogue_proto_rawDesc = "" +
	"\n" +
	"\x0edialogue.proto\x12\x16jp.co.comic.jump.proto\x1a\fbanner.proto\"\xcb\x01\n" +
	"\x10FreeViewDialogue\x12I\n" +
	"\bplatform\x18\x01 \x01(\x0e2-.jp.co.comic.jump.proto.FirstTimeFreePlatformR\bplatform\x12!\n" +
	"\fdialogue_url\x18\x02 \x01(\tR\vdialogueUrl\x12I\n" +
	"\x10publisher_banner\x18\x03 \x01(\v2\x1e.jp.co.comic.jump.proto.BannerR\x0fpublisherBanner*7\n" +
	"\x15FirstTimeFreePlatform\x12\f\n" +
	"\bDISABLED\x10\x00\x12\a\n" +
	"\x03WEB\x10\x01\x12\a\n" +
	"\x03APP\x10\x02b\x06proto3"

var (
	file_dialogue_proto_rawDescOnce sync.Once
	file_dialogue_proto_rawDescData []byte
)

func file_dialogue_proto_rawDescGZIP() []byte {
	file_dialogue_proto_rawDescOnce.Do(func() {
		file_dialogue_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dialogue_proto_rawDesc), len(file_dialogue_proto_rawDesc)))
	})
	return file_dialogue_proto_rawDescData
}

var file_dialogue_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_dialogue_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_dialogue_proto_goTypes = []any{
	(FirstTimeFreePlatform)(0), // 0: jp.co.comic.jump.proto.FirstTimeFreePlatform
	(*FreeViewDialogue)(nil),   // 1: jp.co.comic.jump.proto.FreeViewDialogue
	(*Banner)(nil),             // 2: jp.co.comic.jump.proto.Banner
}
var file_dialogue_proto_depIdxs = []int32{
	0, // 0: jp.co.comic.jump.proto.FreeViewDialogue.platform:type_name -> jp.co.comic.jump.proto.FirstTimeFreePlatform
	2, // 1: jp.co.comic.jump.proto.FreeViewDialogue.publisher_banner:type_name -> jp.co.comic.jump.proto.Banner
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_dialogue_proto_init() }
func file_dialogue_proto_init() {
	if File_dialogue_proto != nil {
		return
	}
	file_banner_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dialogue_proto_rawDesc), len(file_dialogue_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dialogue_proto_goTypes,
		DependencyIndexes: file_dialogue_proto_depIdxs,
		EnumInfos:         file_dialogue_proto_enumTypes,
		MessageInfos:      file_dialogue_proto_msgTypes,
	}.Build()
	File_dialogue_proto = out.File
	file_dialogue_proto_goTypes = nil
	file_dialogue_proto_depIdxs = nil
}
