// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: downloadable_images_view.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DownloadableImagesView struct {
	state              protoimpl.MessageState    `protogen:"open.v1"`
	DownloadableImages []*DownloadableImageGroup `protobuf:"bytes,1,rep,name=downloadable_images,json=downloadableImages,proto3" json:"downloadable_images,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *DownloadableImagesView) Reset() {
	*x = DownloadableImagesView{}
	mi := &file_downloadable_images_view_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadableImagesView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadableImagesView) ProtoMessage() {}

func (x *DownloadableImagesView) ProtoReflect() protoreflect.Message {
	mi := &file_downloadable_images_view_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadableImagesView.ProtoReflect.Descriptor instead.
func (*DownloadableImagesView) Descriptor() ([]byte, []int) {
	return file_downloadable_images_view_proto_rawDescGZIP(), []int{0}
}

func (x *DownloadableImagesView) GetDownloadableImages() []*DownloadableImageGroup {
	if x != nil {
		return x.DownloadableImages
	}
	return nil
}

type DownloadableImageGroup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,2,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	ImageTitle    string                 `protobuf:"bytes,3,opt,name=image_title,json=imageTitle,proto3" json:"image_title,omitempty"`
	Width         uint32                 `protobuf:"varint,4,opt,name=width,proto3" json:"width,omitempty"`
	Height        uint32                 `protobuf:"varint,5,opt,name=height,proto3" json:"height,omitempty"`
	Type          string                 `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadableImageGroup) Reset() {
	*x = DownloadableImageGroup{}
	mi := &file_downloadable_images_view_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadableImageGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadableImageGroup) ProtoMessage() {}

func (x *DownloadableImageGroup) ProtoReflect() protoreflect.Message {
	mi := &file_downloadable_images_view_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadableImageGroup.ProtoReflect.Descriptor instead.
func (*DownloadableImageGroup) Descriptor() ([]byte, []int) {
	return file_downloadable_images_view_proto_rawDescGZIP(), []int{1}
}

func (x *DownloadableImageGroup) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DownloadableImageGroup) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *DownloadableImageGroup) GetImageTitle() string {
	if x != nil {
		return x.ImageTitle
	}
	return ""
}

func (x *DownloadableImageGroup) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *DownloadableImageGroup) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *DownloadableImageGroup) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

var File_downloadable_images_view_proto protoreflect.FileDescriptor

const file_downloadable_images_view_proto_rawDesc = "" +
	"\n" +
	"\x1edownloadable_images_view.proto\x12\x16jp.co.comic.jump.proto\"y\n" +
	"\x16DownloadableImagesView\x12_\n" +
	"\x13downloadable_images\x18\x01 \x03(\v2..jp.co.comic.jump.proto.DownloadableImageGroupR\x12downloadableImages\"\xa8\x01\n" +
	"\x16DownloadableImageGroup\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1b\n" +
	"\timage_url\x18\x02 \x01(\tR\bimageUrl\x12\x1f\n" +
	"\vimage_title\x18\x03 \x01(\tR\n" +
	"imageTitle\x12\x14\n" +
	"\x05width\x18\x04 \x01(\rR\x05width\x12\x16\n" +
	"\x06height\x18\x05 \x01(\rR\x06height\x12\x12\n" +
	"\x04type\x18\x06 \x01(\tR\x04typeb\x06proto3"

var (
	file_downloadable_images_view_proto_rawDescOnce sync.Once
	file_downloadable_images_view_proto_rawDescData []byte
)

func file_downloadable_images_view_proto_rawDescGZIP() []byte {
	file_downloadable_images_view_proto_rawDescOnce.Do(func() {
		file_downloadable_images_view_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_downloadable_images_view_proto_rawDesc), len(file_downloadable_images_view_proto_rawDesc)))
	})
	return file_downloadable_images_view_proto_rawDescData
}

var file_downloadable_images_view_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_downloadable_images_view_proto_goTypes = []any{
	(*DownloadableImagesView)(nil), // 0: jp.co.comic.jump.proto.DownloadableImagesView
	(*DownloadableImageGroup)(nil), // 1: jp.co.comic.jump.proto.DownloadableImageGroup
}
var file_downloadable_images_view_proto_depIdxs = []int32{
	1, // 0: jp.co.comic.jump.proto.DownloadableImagesView.downloadable_images:type_name -> jp.co.comic.jump.proto.DownloadableImageGroup
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_downloadable_images_view_proto_init() }
func file_downloadable_images_view_proto_init() {
	if File_downloadable_images_view_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_downloadable_images_view_proto_rawDesc), len(file_downloadable_images_view_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_downloadable_images_view_proto_goTypes,
		DependencyIndexes: file_downloadable_images_view_proto_depIdxs,
		MessageInfos:      file_downloadable_images_view_proto_msgTypes,
	}.Build()
	File_downloadable_images_view_proto = out.File
	file_downloadable_images_view_proto_goTypes = nil
	file_downloadable_images_view_proto_depIdxs = nil
}
