// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: engage_view.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EngageView struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Medias        []*EngageMedia         `protobuf:"bytes,1,rep,name=medias,proto3" json:"medias,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EngageView) Reset() {
	*x = EngageView{}
	mi := &file_engage_view_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EngageView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EngageView) ProtoMessage() {}

func (x *EngageView) ProtoReflect() protoreflect.Message {
	mi := &file_engage_view_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EngageView.ProtoReflect.Descriptor instead.
func (*EngageView) Descriptor() ([]byte, []int) {
	return file_engage_view_proto_rawDescGZIP(), []int{0}
}

func (x *EngageView) GetMedias() []*EngageMedia {
	if x != nil {
		return x.Medias
	}
	return nil
}

func (x *EngageView) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type EngageMedia struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	BookId                   uint32                 `protobuf:"varint,1,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	Title                    string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Author                   string                 `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	BookCoverUri             string                 `protobuf:"bytes,4,opt,name=book_cover_uri,json=bookCoverUri,proto3" json:"book_cover_uri,omitempty"`
	MediaActionUri           string                 `protobuf:"bytes,5,opt,name=media_action_uri,json=mediaActionUri,proto3" json:"media_action_uri,omitempty"`
	Progress                 uint32                 `protobuf:"varint,6,opt,name=progress,proto3" json:"progress,omitempty"`
	LastEngagementTimeMillis uint64                 `protobuf:"varint,7,opt,name=last_engagement_time_millis,json=lastEngagementTimeMillis,proto3" json:"last_engagement_time_millis,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *EngageMedia) Reset() {
	*x = EngageMedia{}
	mi := &file_engage_view_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EngageMedia) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EngageMedia) ProtoMessage() {}

func (x *EngageMedia) ProtoReflect() protoreflect.Message {
	mi := &file_engage_view_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EngageMedia.ProtoReflect.Descriptor instead.
func (*EngageMedia) Descriptor() ([]byte, []int) {
	return file_engage_view_proto_rawDescGZIP(), []int{1}
}

func (x *EngageMedia) GetBookId() uint32 {
	if x != nil {
		return x.BookId
	}
	return 0
}

func (x *EngageMedia) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *EngageMedia) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *EngageMedia) GetBookCoverUri() string {
	if x != nil {
		return x.BookCoverUri
	}
	return ""
}

func (x *EngageMedia) GetMediaActionUri() string {
	if x != nil {
		return x.MediaActionUri
	}
	return ""
}

func (x *EngageMedia) GetProgress() uint32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *EngageMedia) GetLastEngagementTimeMillis() uint64 {
	if x != nil {
		return x.LastEngagementTimeMillis
	}
	return 0
}

var File_engage_view_proto protoreflect.FileDescriptor

const file_engage_view_proto_rawDesc = "" +
	"\n" +
	"\x11engage_view.proto\x12\x16jp.co.comic.jump.proto\"_\n" +
	"\n" +
	"EngageView\x12;\n" +
	"\x06medias\x18\x01 \x03(\v2#.jp.co.comic.jump.proto.EngageMediaR\x06medias\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\"\xff\x01\n" +
	"\vEngageMedia\x12\x17\n" +
	"\abook_id\x18\x01 \x01(\rR\x06bookId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x16\n" +
	"\x06author\x18\x03 \x01(\tR\x06author\x12$\n" +
	"\x0ebook_cover_uri\x18\x04 \x01(\tR\fbookCoverUri\x12(\n" +
	"\x10media_action_uri\x18\x05 \x01(\tR\x0emediaActionUri\x12\x1a\n" +
	"\bprogress\x18\x06 \x01(\rR\bprogress\x12=\n" +
	"\x1blast_engagement_time_millis\x18\a \x01(\x04R\x18lastEngagementTimeMillisb\x06proto3"

var (
	file_engage_view_proto_rawDescOnce sync.Once
	file_engage_view_proto_rawDescData []byte
)

func file_engage_view_proto_rawDescGZIP() []byte {
	file_engage_view_proto_rawDescOnce.Do(func() {
		file_engage_view_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_engage_view_proto_rawDesc), len(file_engage_view_proto_rawDesc)))
	})
	return file_engage_view_proto_rawDescData
}

var file_engage_view_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_engage_view_proto_goTypes = []any{
	(*EngageView)(nil),  // 0: jp.co.comic.jump.proto.EngageView
	(*EngageMedia)(nil), // 1: jp.co.comic.jump.proto.EngageMedia
}
var file_engage_view_proto_depIdxs = []int32{
	1, // 0: jp.co.comic.jump.proto.EngageView.medias:type_name -> jp.co.comic.jump.proto.EngageMedia
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_engage_view_proto_init() }
func file_engage_view_proto_init() {
	if File_engage_view_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_engage_view_proto_rawDesc), len(file_engage_view_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_engage_view_proto_goTypes,
		DependencyIndexes: file_engage_view_proto_depIdxs,
		MessageInfos:      file_engage_view_proto_msgTypes,
	}.Build()
	File_engage_view_proto = out.File
	file_engage_view_proto_goTypes = nil
	file_engage_view_proto_depIdxs = nil
}
