// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: favorite_titles_view.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FavoriteTitlesView struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	AvailableLanguages []*AvailableLanguages  `protobuf:"bytes,1,rep,name=available_languages,json=availableLanguages,proto3" json:"available_languages,omitempty"`
	FavoriteTitles     []*FavoriteTitleGroup  `protobuf:"bytes,2,rep,name=favorite_titles,json=favoriteTitles,proto3" json:"favorite_titles,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *FavoriteTitlesView) Reset() {
	*x = FavoriteTitlesView{}
	mi := &file_favorite_titles_view_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FavoriteTitlesView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FavoriteTitlesView) ProtoMessage() {}

func (x *FavoriteTitlesView) ProtoReflect() protoreflect.Message {
	mi := &file_favorite_titles_view_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FavoriteTitlesView.ProtoReflect.Descriptor instead.
func (*FavoriteTitlesView) Descriptor() ([]byte, []int) {
	return file_favorite_titles_view_proto_rawDescGZIP(), []int{0}
}

func (x *FavoriteTitlesView) GetAvailableLanguages() []*AvailableLanguages {
	if x != nil {
		return x.AvailableLanguages
	}
	return nil
}

func (x *FavoriteTitlesView) GetFavoriteTitles() []*FavoriteTitleGroup {
	if x != nil {
		return x.FavoriteTitles
	}
	return nil
}

type FavoriteTitleGroup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Language      Language               `protobuf:"varint,1,opt,name=language,proto3,enum=jp.co.comic.jump.proto.Language" json:"language,omitempty"`
	Titles        []*Title               `protobuf:"bytes,2,rep,name=titles,proto3" json:"titles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FavoriteTitleGroup) Reset() {
	*x = FavoriteTitleGroup{}
	mi := &file_favorite_titles_view_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FavoriteTitleGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FavoriteTitleGroup) ProtoMessage() {}

func (x *FavoriteTitleGroup) ProtoReflect() protoreflect.Message {
	mi := &file_favorite_titles_view_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FavoriteTitleGroup.ProtoReflect.Descriptor instead.
func (*FavoriteTitleGroup) Descriptor() ([]byte, []int) {
	return file_favorite_titles_view_proto_rawDescGZIP(), []int{1}
}

func (x *FavoriteTitleGroup) GetLanguage() Language {
	if x != nil {
		return x.Language
	}
	return Language_ENGLISH
}

func (x *FavoriteTitleGroup) GetTitles() []*Title {
	if x != nil {
		return x.Titles
	}
	return nil
}

var File_favorite_titles_view_proto protoreflect.FileDescriptor

const file_favorite_titles_view_proto_rawDesc = "" +
	"\n" +
	"\x1afavorite_titles_view.proto\x12\x16jp.co.comic.jump.proto\x1a\x0flanguages.proto\x1a\vtitle.proto\"\xc6\x01\n" +
	"\x12FavoriteTitlesView\x12[\n" +
	"\x13available_languages\x18\x01 \x03(\v2*.jp.co.comic.jump.proto.AvailableLanguagesR\x12availableLanguages\x12S\n" +
	"\x0ffavorite_titles\x18\x02 \x03(\v2*.jp.co.comic.jump.proto.FavoriteTitleGroupR\x0efavoriteTitles\"\x89\x01\n" +
	"\x12FavoriteTitleGroup\x12<\n" +
	"\blanguage\x18\x01 \x01(\x0e2 .jp.co.comic.jump.proto.LanguageR\blanguage\x125\n" +
	"\x06titles\x18\x02 \x03(\v2\x1d.jp.co.comic.jump.proto.TitleR\x06titlesb\x06proto3"

var (
	file_favorite_titles_view_proto_rawDescOnce sync.Once
	file_favorite_titles_view_proto_rawDescData []byte
)

func file_favorite_titles_view_proto_rawDescGZIP() []byte {
	file_favorite_titles_view_proto_rawDescOnce.Do(func() {
		file_favorite_titles_view_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_favorite_titles_view_proto_rawDesc), len(file_favorite_titles_view_proto_rawDesc)))
	})
	return file_favorite_titles_view_proto_rawDescData
}

var file_favorite_titles_view_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_favorite_titles_view_proto_goTypes = []any{
	(*FavoriteTitlesView)(nil), // 0: jp.co.comic.jump.proto.FavoriteTitlesView
	(*FavoriteTitleGroup)(nil), // 1: jp.co.comic.jump.proto.FavoriteTitleGroup
	(*AvailableLanguages)(nil), // 2: jp.co.comic.jump.proto.AvailableLanguages
	(Language)(0),              // 3: jp.co.comic.jump.proto.Language
	(*Title)(nil),              // 4: jp.co.comic.jump.proto.Title
}
var file_favorite_titles_view_proto_depIdxs = []int32{
	2, // 0: jp.co.comic.jump.proto.FavoriteTitlesView.available_languages:type_name -> jp.co.comic.jump.proto.AvailableLanguages
	1, // 1: jp.co.comic.jump.proto.FavoriteTitlesView.favorite_titles:type_name -> jp.co.comic.jump.proto.FavoriteTitleGroup
	3, // 2: jp.co.comic.jump.proto.FavoriteTitleGroup.language:type_name -> jp.co.comic.jump.proto.Language
	4, // 3: jp.co.comic.jump.proto.FavoriteTitleGroup.titles:type_name -> jp.co.comic.jump.proto.Title
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_favorite_titles_view_proto_init() }
func file_favorite_titles_view_proto_init() {
	if File_favorite_titles_view_proto != nil {
		return
	}
	file_languages_proto_init()
	file_title_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_favorite_titles_view_proto_rawDesc), len(file_favorite_titles_view_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_favorite_titles_view_proto_goTypes,
		DependencyIndexes: file_favorite_titles_view_proto_depIdxs,
		MessageInfos:      file_favorite_titles_view_proto_msgTypes,
	}.Build()
	File_favorite_titles_view_proto = out.File
	file_favorite_titles_view_proto_goTypes = nil
	file_favorite_titles_view_proto_depIdxs = nil
}
