// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: featured_titles_view.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FeaturedTitlesView struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	MainBanner    *Banner                        `protobuf:"bytes,1,opt,name=main_banner,json=mainBanner,proto3" json:"main_banner,omitempty"`
	SubBanner_1   *Banner                        `protobuf:"bytes,2,opt,name=sub_banner_1,json=subBanner1,proto3" json:"sub_banner_1,omitempty"`
	SubBanner_2   *Banner                        `protobuf:"bytes,3,opt,name=sub_banner_2,json=subBanner2,proto3" json:"sub_banner_2,omitempty"`
	Contents      []*FeaturedTitlesView_Contents `protobuf:"bytes,4,rep,name=contents,proto3" json:"contents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeaturedTitlesView) Reset() {
	*x = FeaturedTitlesView{}
	mi := &file_featured_titles_view_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeaturedTitlesView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeaturedTitlesView) ProtoMessage() {}

func (x *FeaturedTitlesView) ProtoReflect() protoreflect.Message {
	mi := &file_featured_titles_view_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeaturedTitlesView.ProtoReflect.Descriptor instead.
func (*FeaturedTitlesView) Descriptor() ([]byte, []int) {
	return file_featured_titles_view_proto_rawDescGZIP(), []int{0}
}

func (x *FeaturedTitlesView) GetMainBanner() *Banner {
	if x != nil {
		return x.MainBanner
	}
	return nil
}

func (x *FeaturedTitlesView) GetSubBanner_1() *Banner {
	if x != nil {
		return x.SubBanner_1
	}
	return nil
}

func (x *FeaturedTitlesView) GetSubBanner_2() *Banner {
	if x != nil {
		return x.SubBanner_2
	}
	return nil
}

func (x *FeaturedTitlesView) GetContents() []*FeaturedTitlesView_Contents {
	if x != nil {
		return x.Contents
	}
	return nil
}

type FeaturedTitlesView_Contents struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Data:
	//
	//	*FeaturedTitlesView_Contents_Banner
	//	*FeaturedTitlesView_Contents_TitleList
	Data          isFeaturedTitlesView_Contents_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeaturedTitlesView_Contents) Reset() {
	*x = FeaturedTitlesView_Contents{}
	mi := &file_featured_titles_view_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeaturedTitlesView_Contents) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeaturedTitlesView_Contents) ProtoMessage() {}

func (x *FeaturedTitlesView_Contents) ProtoReflect() protoreflect.Message {
	mi := &file_featured_titles_view_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeaturedTitlesView_Contents.ProtoReflect.Descriptor instead.
func (*FeaturedTitlesView_Contents) Descriptor() ([]byte, []int) {
	return file_featured_titles_view_proto_rawDescGZIP(), []int{0, 0}
}

func (x *FeaturedTitlesView_Contents) GetData() isFeaturedTitlesView_Contents_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *FeaturedTitlesView_Contents) GetBanner() *Banner {
	if x != nil {
		if x, ok := x.Data.(*FeaturedTitlesView_Contents_Banner); ok {
			return x.Banner
		}
	}
	return nil
}

func (x *FeaturedTitlesView_Contents) GetTitleList() *TitleList {
	if x != nil {
		if x, ok := x.Data.(*FeaturedTitlesView_Contents_TitleList); ok {
			return x.TitleList
		}
	}
	return nil
}

type isFeaturedTitlesView_Contents_Data interface {
	isFeaturedTitlesView_Contents_Data()
}

type FeaturedTitlesView_Contents_Banner struct {
	Banner *Banner `protobuf:"bytes,1,opt,name=banner,proto3,oneof"`
}

type FeaturedTitlesView_Contents_TitleList struct {
	TitleList *TitleList `protobuf:"bytes,2,opt,name=title_list,json=titleList,proto3,oneof"`
}

func (*FeaturedTitlesView_Contents_Banner) isFeaturedTitlesView_Contents_Data() {}

func (*FeaturedTitlesView_Contents_TitleList) isFeaturedTitlesView_Contents_Data() {}

var File_featured_titles_view_proto protoreflect.FileDescriptor

const file_featured_titles_view_proto_rawDesc = "" +
	"\n" +
	"\x1afeatured_titles_view.proto\x12\x16jp.co.comic.jump.proto\x1a\fbanner.proto\x1a\x10title_list.proto\"\xbd\x03\n" +
	"\x12FeaturedTitlesView\x12?\n" +
	"\vmain_banner\x18\x01 \x01(\v2\x1e.jp.co.comic.jump.proto.BannerR\n" +
	"mainBanner\x12@\n" +
	"\fsub_banner_1\x18\x02 \x01(\v2\x1e.jp.co.comic.jump.proto.BannerR\n" +
	"subBanner1\x12@\n" +
	"\fsub_banner_2\x18\x03 \x01(\v2\x1e.jp.co.comic.jump.proto.BannerR\n" +
	"subBanner2\x12O\n" +
	"\bcontents\x18\x04 \x03(\v23.jp.co.comic.jump.proto.FeaturedTitlesView.ContentsR\bcontents\x1a\x90\x01\n" +
	"\bContents\x128\n" +
	"\x06banner\x18\x01 \x01(\v2\x1e.jp.co.comic.jump.proto.BannerH\x00R\x06banner\x12B\n" +
	"\n" +
	"title_list\x18\x02 \x01(\v2!.jp.co.comic.jump.proto.TitleListH\x00R\ttitleListB\x06\n" +
	"\x04datab\x06proto3"

var (
	file_featured_titles_view_proto_rawDescOnce sync.Once
	file_featured_titles_view_proto_rawDescData []byte
)

func file_featured_titles_view_proto_rawDescGZIP() []byte {
	file_featured_titles_view_proto_rawDescOnce.Do(func() {
		file_featured_titles_view_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_featured_titles_view_proto_rawDesc), len(file_featured_titles_view_proto_rawDesc)))
	})
	return file_featured_titles_view_proto_rawDescData
}

var file_featured_titles_view_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_featured_titles_view_proto_goTypes = []any{
	(*FeaturedTitlesView)(nil),          // 0: jp.co.comic.jump.proto.FeaturedTitlesView
	(*FeaturedTitlesView_Contents)(nil), // 1: jp.co.comic.jump.proto.FeaturedTitlesView.Contents
	(*Banner)(nil),                      // 2: jp.co.comic.jump.proto.Banner
	(*TitleList)(nil),                   // 3: jp.co.comic.jump.proto.TitleList
}
var file_featured_titles_view_proto_depIdxs = []int32{
	2, // 0: jp.co.comic.jump.proto.FeaturedTitlesView.main_banner:type_name -> jp.co.comic.jump.proto.Banner
	2, // 1: jp.co.comic.jump.proto.FeaturedTitlesView.sub_banner_1:type_name -> jp.co.comic.jump.proto.Banner
	2, // 2: jp.co.comic.jump.proto.FeaturedTitlesView.sub_banner_2:type_name -> jp.co.comic.jump.proto.Banner
	1, // 3: jp.co.comic.jump.proto.FeaturedTitlesView.contents:type_name -> jp.co.comic.jump.proto.FeaturedTitlesView.Contents
	2, // 4: jp.co.comic.jump.proto.FeaturedTitlesView.Contents.banner:type_name -> jp.co.comic.jump.proto.Banner
	3, // 5: jp.co.comic.jump.proto.FeaturedTitlesView.Contents.title_list:type_name -> jp.co.comic.jump.proto.TitleList
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_featured_titles_view_proto_init() }
func file_featured_titles_view_proto_init() {
	if File_featured_titles_view_proto != nil {
		return
	}
	file_banner_proto_init()
	file_title_list_proto_init()
	file_featured_titles_view_proto_msgTypes[1].OneofWrappers = []any{
		(*FeaturedTitlesView_Contents_Banner)(nil),
		(*FeaturedTitlesView_Contents_TitleList)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_featured_titles_view_proto_rawDesc), len(file_featured_titles_view_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_featured_titles_view_proto_goTypes,
		DependencyIndexes: file_featured_titles_view_proto_depIdxs,
		MessageInfos:      file_featured_titles_view_proto_msgTypes,
	}.Build()
	File_featured_titles_view_proto = out.File
	file_featured_titles_view_proto_goTypes = nil
	file_featured_titles_view_proto_depIdxs = nil
}
