// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: featured_titles_view_v2.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FeaturedTitlesViewV2 struct {
	state            protoimpl.MessageState         `protogen:"open.v1"`
	TopSearchBanners []*Banner                      `protobuf:"bytes,1,rep,name=top_search_banners,json=topSearchBanners,proto3" json:"top_search_banners,omitempty"`
	Contents         []*FeaturedTitlesView_Contents `protobuf:"bytes,2,rep,name=contents,proto3" json:"contents,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *FeaturedTitlesViewV2) Reset() {
	*x = FeaturedTitlesViewV2{}
	mi := &file_featured_titles_view_v2_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeaturedTitlesViewV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeaturedTitlesViewV2) ProtoMessage() {}

func (x *FeaturedTitlesViewV2) ProtoReflect() protoreflect.Message {
	mi := &file_featured_titles_view_v2_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeaturedTitlesViewV2.ProtoReflect.Descriptor instead.
func (*FeaturedTitlesViewV2) Descriptor() ([]byte, []int) {
	return file_featured_titles_view_v2_proto_rawDescGZIP(), []int{0}
}

func (x *FeaturedTitlesViewV2) GetTopSearchBanners() []*Banner {
	if x != nil {
		return x.TopSearchBanners
	}
	return nil
}

func (x *FeaturedTitlesViewV2) GetContents() []*FeaturedTitlesView_Contents {
	if x != nil {
		return x.Contents
	}
	return nil
}

type FeaturedTitlesViewV2_Contents struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Banner        *Banner                `protobuf:"bytes,1,opt,name=banner,proto3" json:"banner,omitempty"`
	TitleList     *TitleList             `protobuf:"bytes,2,opt,name=title_list,json=titleList,proto3" json:"title_list,omitempty"`
	RankedTitles  []*TitleRankingGroup   `protobuf:"bytes,3,rep,name=ranked_titles,json=rankedTitles,proto3" json:"ranked_titles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeaturedTitlesViewV2_Contents) Reset() {
	*x = FeaturedTitlesViewV2_Contents{}
	mi := &file_featured_titles_view_v2_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeaturedTitlesViewV2_Contents) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeaturedTitlesViewV2_Contents) ProtoMessage() {}

func (x *FeaturedTitlesViewV2_Contents) ProtoReflect() protoreflect.Message {
	mi := &file_featured_titles_view_v2_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeaturedTitlesViewV2_Contents.ProtoReflect.Descriptor instead.
func (*FeaturedTitlesViewV2_Contents) Descriptor() ([]byte, []int) {
	return file_featured_titles_view_v2_proto_rawDescGZIP(), []int{0, 0}
}

func (x *FeaturedTitlesViewV2_Contents) GetBanner() *Banner {
	if x != nil {
		return x.Banner
	}
	return nil
}

func (x *FeaturedTitlesViewV2_Contents) GetTitleList() *TitleList {
	if x != nil {
		return x.TitleList
	}
	return nil
}

func (x *FeaturedTitlesViewV2_Contents) GetRankedTitles() []*TitleRankingGroup {
	if x != nil {
		return x.RankedTitles
	}
	return nil
}

var File_featured_titles_view_v2_proto protoreflect.FileDescriptor

const file_featured_titles_view_v2_proto_rawDesc = "" +
	"\n" +
	"\x1dfeatured_titles_view_v2.proto\x12\x16jp.co.comic.jump.proto\x1a\fbanner.proto\x1a\x1afeatured_titles_view.proto\x1a\x10title_list.proto\x1a\x16title_list_group.proto\"\x8c\x03\n" +
	"\x14FeaturedTitlesViewV2\x12L\n" +
	"\x12top_search_banners\x18\x01 \x03(\v2\x1e.jp.co.comic.jump.proto.BannerR\x10topSearchBanners\x12O\n" +
	"\bcontents\x18\x02 \x03(\v23.jp.co.comic.jump.proto.FeaturedTitlesView.ContentsR\bcontents\x1a\xd4\x01\n" +
	"\bContents\x126\n" +
	"\x06banner\x18\x01 \x01(\v2\x1e.jp.co.comic.jump.proto.BannerR\x06banner\x12@\n" +
	"\n" +
	"title_list\x18\x02 \x01(\v2!.jp.co.comic.jump.proto.TitleListR\ttitleList\x12N\n" +
	"\rranked_titles\x18\x03 \x03(\v2).jp.co.comic.jump.proto.TitleRankingGroupR\frankedTitlesb\x06proto3"

var (
	file_featured_titles_view_v2_proto_rawDescOnce sync.Once
	file_featured_titles_view_v2_proto_rawDescData []byte
)

func file_featured_titles_view_v2_proto_rawDescGZIP() []byte {
	file_featured_titles_view_v2_proto_rawDescOnce.Do(func() {
		file_featured_titles_view_v2_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_featured_titles_view_v2_proto_rawDesc), len(file_featured_titles_view_v2_proto_rawDesc)))
	})
	return file_featured_titles_view_v2_proto_rawDescData
}

var file_featured_titles_view_v2_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_featured_titles_view_v2_proto_goTypes = []any{
	(*FeaturedTitlesViewV2)(nil),          // 0: jp.co.comic.jump.proto.FeaturedTitlesViewV2
	(*FeaturedTitlesViewV2_Contents)(nil), // 1: jp.co.comic.jump.proto.FeaturedTitlesViewV2.Contents
	(*Banner)(nil),                        // 2: jp.co.comic.jump.proto.Banner
	(*FeaturedTitlesView_Contents)(nil),   // 3: jp.co.comic.jump.proto.FeaturedTitlesView.Contents
	(*TitleList)(nil),                     // 4: jp.co.comic.jump.proto.TitleList
	(*TitleRankingGroup)(nil),             // 5: jp.co.comic.jump.proto.TitleRankingGroup
}
var file_featured_titles_view_v2_proto_depIdxs = []int32{
	2, // 0: jp.co.comic.jump.proto.FeaturedTitlesViewV2.top_search_banners:type_name -> jp.co.comic.jump.proto.Banner
	3, // 1: jp.co.comic.jump.proto.FeaturedTitlesViewV2.contents:type_name -> jp.co.comic.jump.proto.FeaturedTitlesView.Contents
	2, // 2: jp.co.comic.jump.proto.FeaturedTitlesViewV2.Contents.banner:type_name -> jp.co.comic.jump.proto.Banner
	4, // 3: jp.co.comic.jump.proto.FeaturedTitlesViewV2.Contents.title_list:type_name -> jp.co.comic.jump.proto.TitleList
	5, // 4: jp.co.comic.jump.proto.FeaturedTitlesViewV2.Contents.ranked_titles:type_name -> jp.co.comic.jump.proto.TitleRankingGroup
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_featured_titles_view_v2_proto_init() }
func file_featured_titles_view_v2_proto_init() {
	if File_featured_titles_view_v2_proto != nil {
		return
	}
	file_banner_proto_init()
	file_featured_titles_view_proto_init()
	file_title_list_proto_init()
	file_title_list_group_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_featured_titles_view_v2_proto_rawDesc), len(file_featured_titles_view_v2_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_featured_titles_view_v2_proto_goTypes,
		DependencyIndexes: file_featured_titles_view_v2_proto_depIdxs,
		MessageInfos:      file_featured_titles_view_v2_proto_msgTypes,
	}.Build()
	File_featured_titles_view_v2_proto = out.File
	file_featured_titles_view_v2_proto_goTypes = nil
	file_featured_titles_view_v2_proto_depIdxs = nil
}
