// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: feedback.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Feedback_ResponseType int32

const (
	Feedback_QUESTION Feedback_ResponseType = 0
	Feedback_ANSWER   Feedback_ResponseType = 1
)

// Enum value maps for Feedback_ResponseType.
var (
	Feedback_ResponseType_name = map[int32]string{
		0: "QUESTION",
		1: "ANSWER",
	}
	Feedback_ResponseType_value = map[string]int32{
		"QUESTION": 0,
		"ANSWER":   1,
	}
)

func (x Feedback_ResponseType) Enum() *Feedback_ResponseType {
	p := new(Feedback_ResponseType)
	*p = x
	return p
}

func (x Feedback_ResponseType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Feedback_ResponseType) Descriptor() protoreflect.EnumDescriptor {
	return file_feedback_proto_enumTypes[0].Descriptor()
}

func (Feedback_ResponseType) Type() protoreflect.EnumType {
	return &file_feedback_proto_enumTypes[0]
}

func (x Feedback_ResponseType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Feedback_ResponseType.Descriptor instead.
func (Feedback_ResponseType) EnumDescriptor() ([]byte, []int) {
	return file_feedback_proto_rawDescGZIP(), []int{0, 0}
}

type Feedback struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimeStamp     uint32                 `protobuf:"varint,1,opt,name=time_stamp,json=timeStamp,proto3" json:"time_stamp,omitempty"`
	Body          string                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	ResponseType  Feedback_ResponseType  `protobuf:"varint,3,opt,name=response_type,json=responseType,proto3,enum=jp.co.comic.jump.proto.Feedback_ResponseType" json:"response_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Feedback) Reset() {
	*x = Feedback{}
	mi := &file_feedback_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Feedback) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Feedback) ProtoMessage() {}

func (x *Feedback) ProtoReflect() protoreflect.Message {
	mi := &file_feedback_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Feedback.ProtoReflect.Descriptor instead.
func (*Feedback) Descriptor() ([]byte, []int) {
	return file_feedback_proto_rawDescGZIP(), []int{0}
}

func (x *Feedback) GetTimeStamp() uint32 {
	if x != nil {
		return x.TimeStamp
	}
	return 0
}

func (x *Feedback) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Feedback) GetResponseType() Feedback_ResponseType {
	if x != nil {
		return x.ResponseType
	}
	return Feedback_QUESTION
}

var File_feedback_proto protoreflect.FileDescriptor

const file_feedback_proto_rawDesc = "" +
	"\n" +
	"\x0efeedback.proto\x12\x16jp.co.comic.jump.proto\"\xbb\x01\n" +
	"\bFeedback\x12\x1d\n" +
	"\n" +
	"time_stamp\x18\x01 \x01(\rR\ttimeStamp\x12\x12\n" +
	"\x04body\x18\x02 \x01(\tR\x04body\x12R\n" +
	"\rresponse_type\x18\x03 \x01(\x0e2-.jp.co.comic.jump.proto.Feedback.ResponseTypeR\fresponseType\"(\n" +
	"\fResponseType\x12\f\n" +
	"\bQUESTION\x10\x00\x12\n" +
	"\n" +
	"\x06ANSWER\x10\x01b\x06proto3"

var (
	file_feedback_proto_rawDescOnce sync.Once
	file_feedback_proto_rawDescData []byte
)

func file_feedback_proto_rawDescGZIP() []byte {
	file_feedback_proto_rawDescOnce.Do(func() {
		file_feedback_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_feedback_proto_rawDesc), len(file_feedback_proto_rawDesc)))
	})
	return file_feedback_proto_rawDescData
}

var file_feedback_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_feedback_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_feedback_proto_goTypes = []any{
	(Feedback_ResponseType)(0), // 0: jp.co.comic.jump.proto.Feedback.ResponseType
	(*Feedback)(nil),           // 1: jp.co.comic.jump.proto.Feedback
}
var file_feedback_proto_depIdxs = []int32{
	0, // 0: jp.co.comic.jump.proto.Feedback.response_type:type_name -> jp.co.comic.jump.proto.Feedback.ResponseType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_feedback_proto_init() }
func file_feedback_proto_init() {
	if File_feedback_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_feedback_proto_rawDesc), len(file_feedback_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_feedback_proto_goTypes,
		DependencyIndexes: file_feedback_proto_depIdxs,
		EnumInfos:         file_feedback_proto_enumTypes,
		MessageInfos:      file_feedback_proto_msgTypes,
	}.Build()
	File_feedback_proto = out.File
	file_feedback_proto_goTypes = nil
	file_feedback_proto_depIdxs = nil
}
