// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: feedback_view.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FeedbackView struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FeedbackList  []*Feedback            `protobuf:"bytes,1,rep,name=feedback_list,json=feedbackList,proto3" json:"feedback_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeedbackView) Reset() {
	*x = FeedbackView{}
	mi := &file_feedback_view_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeedbackView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedbackView) ProtoMessage() {}

func (x *FeedbackView) ProtoReflect() protoreflect.Message {
	mi := &file_feedback_view_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedbackView.ProtoReflect.Descriptor instead.
func (*FeedbackView) Descriptor() ([]byte, []int) {
	return file_feedback_view_proto_rawDescGZIP(), []int{0}
}

func (x *FeedbackView) GetFeedbackList() []*Feedback {
	if x != nil {
		return x.FeedbackList
	}
	return nil
}

var File_feedback_view_proto protoreflect.FileDescriptor

const file_feedback_view_proto_rawDesc = "" +
	"\n" +
	"\x13feedback_view.proto\x12\x16jp.co.comic.jump.proto\x1a\x0efeedback.proto\"U\n" +
	"\fFeedbackView\x12E\n" +
	"\rfeedback_list\x18\x01 \x03(\v2 .jp.co.comic.jump.proto.FeedbackR\ffeedbackListb\x06proto3"

var (
	file_feedback_view_proto_rawDescOnce sync.Once
	file_feedback_view_proto_rawDescData []byte
)

func file_feedback_view_proto_rawDescGZIP() []byte {
	file_feedback_view_proto_rawDescOnce.Do(func() {
		file_feedback_view_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_feedback_view_proto_rawDesc), len(file_feedback_view_proto_rawDesc)))
	})
	return file_feedback_view_proto_rawDescData
}

var file_feedback_view_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_feedback_view_proto_goTypes = []any{
	(*FeedbackView)(nil), // 0: jp.co.comic.jump.proto.FeedbackView
	(*Feedback)(nil),     // 1: jp.co.comic.jump.proto.Feedback
}
var file_feedback_view_proto_depIdxs = []int32{
	1, // 0: jp.co.comic.jump.proto.FeedbackView.feedback_list:type_name -> jp.co.comic.jump.proto.Feedback
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_feedback_view_proto_init() }
func file_feedback_view_proto_init() {
	if File_feedback_view_proto != nil {
		return
	}
	file_feedback_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_feedback_view_proto_rawDesc), len(file_feedback_view_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_feedback_view_proto_goTypes,
		DependencyIndexes: file_feedback_view_proto_depIdxs,
		MessageInfos:      file_feedback_view_proto_msgTypes,
	}.Build()
	File_feedback_view_proto = out.File
	file_feedback_view_proto_goTypes = nil
	file_feedback_view_proto_depIdxs = nil
}
