// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: home_preview_view.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HomePreviewView struct {
	state           protoimpl.MessageState       `protogen:"open.v1"`
	PreviewSections []*HomeViewV6_PreviewSection `protobuf:"bytes,1,rep,name=preview_sections,json=previewSections,proto3" json:"preview_sections,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HomePreviewView) Reset() {
	*x = HomePreviewView{}
	mi := &file_home_preview_view_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HomePreviewView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HomePreviewView) ProtoMessage() {}

func (x *HomePreviewView) ProtoReflect() protoreflect.Message {
	mi := &file_home_preview_view_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HomePreviewView.ProtoReflect.Descriptor instead.
func (*HomePreviewView) Descriptor() ([]byte, []int) {
	return file_home_preview_view_proto_rawDescGZIP(), []int{0}
}

func (x *HomePreviewView) GetPreviewSections() []*HomeViewV6_PreviewSection {
	if x != nil {
		return x.PreviewSections
	}
	return nil
}

var File_home_preview_view_proto protoreflect.FileDescriptor

const file_home_preview_view_proto_rawDesc = "" +
	"\n" +
	"\x17home_preview_view.proto\x12\x16jp.co.comic.jump.proto\x1a\x12home_view_v6.proto\"o\n" +
	"\x0fHomePreviewView\x12\\\n" +
	"\x10preview_sections\x18\x01 \x03(\v21.jp.co.comic.jump.proto.HomeViewV6.PreviewSectionR\x0fpreviewSectionsb\x06proto3"

var (
	file_home_preview_view_proto_rawDescOnce sync.Once
	file_home_preview_view_proto_rawDescData []byte
)

func file_home_preview_view_proto_rawDescGZIP() []byte {
	file_home_preview_view_proto_rawDescOnce.Do(func() {
		file_home_preview_view_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_home_preview_view_proto_rawDesc), len(file_home_preview_view_proto_rawDesc)))
	})
	return file_home_preview_view_proto_rawDescData
}

var file_home_preview_view_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_home_preview_view_proto_goTypes = []any{
	(*HomePreviewView)(nil),           // 0: jp.co.comic.jump.proto.HomePreviewView
	(*HomeViewV6_PreviewSection)(nil), // 1: jp.co.comic.jump.proto.HomeViewV6.PreviewSection
}
var file_home_preview_view_proto_depIdxs = []int32{
	1, // 0: jp.co.comic.jump.proto.HomePreviewView.preview_sections:type_name -> jp.co.comic.jump.proto.HomeViewV6.PreviewSection
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_home_preview_view_proto_init() }
func file_home_preview_view_proto_init() {
	if File_home_preview_view_proto != nil {
		return
	}
	file_home_view_v6_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_home_preview_view_proto_rawDesc), len(file_home_preview_view_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_home_preview_view_proto_goTypes,
		DependencyIndexes: file_home_preview_view_proto_depIdxs,
		MessageInfos:      file_home_preview_view_proto_msgTypes,
	}.Build()
	File_home_preview_view_proto = out.File
	file_home_preview_view_proto_goTypes = nil
	file_home_preview_view_proto_depIdxs = nil
}
