// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: initial_view_v2.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InitialViewV2 struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	GdprAgreementRequired bool                   `protobuf:"varint,1,opt,name=gdpr_agreement_required,json=gdprAgreementRequired,proto3" json:"gdpr_agreement_required,omitempty"`
	AvailableLanguages    []*AvailableLanguages  `protobuf:"bytes,2,rep,name=available_languages,json=availableLanguages,proto3" json:"available_languages,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *InitialViewV2) Reset() {
	*x = InitialViewV2{}
	mi := &file_initial_view_v2_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitialViewV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitialViewV2) ProtoMessage() {}

func (x *InitialViewV2) ProtoReflect() protoreflect.Message {
	mi := &file_initial_view_v2_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitialViewV2.ProtoReflect.Descriptor instead.
func (*InitialViewV2) Descriptor() ([]byte, []int) {
	return file_initial_view_v2_proto_rawDescGZIP(), []int{0}
}

func (x *InitialViewV2) GetGdprAgreementRequired() bool {
	if x != nil {
		return x.GdprAgreementRequired
	}
	return false
}

func (x *InitialViewV2) GetAvailableLanguages() []*AvailableLanguages {
	if x != nil {
		return x.AvailableLanguages
	}
	return nil
}

var File_initial_view_v2_proto protoreflect.FileDescriptor

const file_initial_view_v2_proto_rawDesc = "" +
	"\n" +
	"\x15initial_view_v2.proto\x12\x16jp.co.comic.jump.proto\x1a\x0flanguages.proto\"\xa4\x01\n" +
	"\rInitialViewV2\x126\n" +
	"\x17gdpr_agreement_required\x18\x01 \x01(\bR\x15gdprAgreementRequired\x12[\n" +
	"\x13available_languages\x18\x02 \x03(\v2*.jp.co.comic.jump.proto.AvailableLanguagesR\x12availableLanguagesb\x06proto3"

var (
	file_initial_view_v2_proto_rawDescOnce sync.Once
	file_initial_view_v2_proto_rawDescData []byte
)

func file_initial_view_v2_proto_rawDescGZIP() []byte {
	file_initial_view_v2_proto_rawDescOnce.Do(func() {
		file_initial_view_v2_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_initial_view_v2_proto_rawDesc), len(file_initial_view_v2_proto_rawDesc)))
	})
	return file_initial_view_v2_proto_rawDescData
}

var file_initial_view_v2_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_initial_view_v2_proto_goTypes = []any{
	(*InitialViewV2)(nil),      // 0: jp.co.comic.jump.proto.InitialViewV2
	(*AvailableLanguages)(nil), // 1: jp.co.comic.jump.proto.AvailableLanguages
}
var file_initial_view_v2_proto_depIdxs = []int32{
	1, // 0: jp.co.comic.jump.proto.InitialViewV2.available_languages:type_name -> jp.co.comic.jump.proto.AvailableLanguages
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_initial_view_v2_proto_init() }
func file_initial_view_v2_proto_init() {
	if File_initial_view_v2_proto != nil {
		return
	}
	file_languages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_initial_view_v2_proto_rawDesc), len(file_initial_view_v2_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_initial_view_v2_proto_goTypes,
		DependencyIndexes: file_initial_view_v2_proto_depIdxs,
		MessageInfos:      file_initial_view_v2_proto_msgTypes,
	}.Build()
	File_initial_view_v2_proto = out.File
	file_initial_view_v2_proto_goTypes = nil
	file_initial_view_v2_proto_depIdxs = nil
}
