// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: introduce_subscription.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IntroduceSubscription struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Subscription     string                 `protobuf:"bytes,1,opt,name=subscription,proto3" json:"subscription,omitempty"`
	TitleCountText   string                 `protobuf:"bytes,2,opt,name=title_count_text,json=titleCountText,proto3" json:"title_count_text,omitempty"`
	ChapterCountText string                 `protobuf:"bytes,3,opt,name=chapter_count_text,json=chapterCountText,proto3" json:"chapter_count_text,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *IntroduceSubscription) Reset() {
	*x = IntroduceSubscription{}
	mi := &file_introduce_subscription_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntroduceSubscription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntroduceSubscription) ProtoMessage() {}

func (x *IntroduceSubscription) ProtoReflect() protoreflect.Message {
	mi := &file_introduce_subscription_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntroduceSubscription.ProtoReflect.Descriptor instead.
func (*IntroduceSubscription) Descriptor() ([]byte, []int) {
	return file_introduce_subscription_proto_rawDescGZIP(), []int{0}
}

func (x *IntroduceSubscription) GetSubscription() string {
	if x != nil {
		return x.Subscription
	}
	return ""
}

func (x *IntroduceSubscription) GetTitleCountText() string {
	if x != nil {
		return x.TitleCountText
	}
	return ""
}

func (x *IntroduceSubscription) GetChapterCountText() string {
	if x != nil {
		return x.ChapterCountText
	}
	return ""
}

var File_introduce_subscription_proto protoreflect.FileDescriptor

const file_introduce_subscription_proto_rawDesc = "" +
	"\n" +
	"\x1cintroduce_subscription.proto\x12\x16jp.co.comic.jump.proto\"\x93\x01\n" +
	"\x15IntroduceSubscription\x12\"\n" +
	"\fsubscription\x18\x01 \x01(\tR\fsubscription\x12(\n" +
	"\x10title_count_text\x18\x02 \x01(\tR\x0etitleCountText\x12,\n" +
	"\x12chapter_count_text\x18\x03 \x01(\tR\x10chapterCountTextb\x06proto3"

var (
	file_introduce_subscription_proto_rawDescOnce sync.Once
	file_introduce_subscription_proto_rawDescData []byte
)

func file_introduce_subscription_proto_rawDescGZIP() []byte {
	file_introduce_subscription_proto_rawDescOnce.Do(func() {
		file_introduce_subscription_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_introduce_subscription_proto_rawDesc), len(file_introduce_subscription_proto_rawDesc)))
	})
	return file_introduce_subscription_proto_rawDescData
}

var file_introduce_subscription_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_introduce_subscription_proto_goTypes = []any{
	(*IntroduceSubscription)(nil), // 0: jp.co.comic.jump.proto.IntroduceSubscription
}
var file_introduce_subscription_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_introduce_subscription_proto_init() }
func file_introduce_subscription_proto_init() {
	if File_introduce_subscription_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_introduce_subscription_proto_rawDesc), len(file_introduce_subscription_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_introduce_subscription_proto_goTypes,
		DependencyIndexes: file_introduce_subscription_proto_depIdxs,
		MessageInfos:      file_introduce_subscription_proto_msgTypes,
	}.Build()
	File_introduce_subscription_proto = out.File
	file_introduce_subscription_proto_goTypes = nil
	file_introduce_subscription_proto_depIdxs = nil
}
