// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: labeled_view.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LabeledView struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Label              *Label                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	LabeledTitlesGroup []*LabeledTitlesGroup  `protobuf:"bytes,2,rep,name=labeledTitlesGroup,proto3" json:"labeledTitlesGroup,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *LabeledView) Reset() {
	*x = LabeledView{}
	mi := &file_labeled_view_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LabeledView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LabeledView) ProtoMessage() {}

func (x *LabeledView) ProtoReflect() protoreflect.Message {
	mi := &file_labeled_view_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LabeledView.ProtoReflect.Descriptor instead.
func (*LabeledView) Descriptor() ([]byte, []int) {
	return file_labeled_view_proto_rawDescGZIP(), []int{0}
}

func (x *LabeledView) GetLabel() *Label {
	if x != nil {
		return x.Label
	}
	return nil
}

func (x *LabeledView) GetLabeledTitlesGroup() []*LabeledTitlesGroup {
	if x != nil {
		return x.LabeledTitlesGroup
	}
	return nil
}

var File_labeled_view_proto protoreflect.FileDescriptor

const file_labeled_view_proto_rawDesc = "" +
	"\n" +
	"\x12labeled_view.proto\x12\x16jp.co.comic.jump.proto\x1a\vlabel.proto\x1a\x16title_list_group.proto\"\x9e\x01\n" +
	"\vLabeledView\x123\n" +
	"\x05label\x18\x01 \x01(\v2\x1d.jp.co.comic.jump.proto.LabelR\x05label\x12Z\n" +
	"\x12labeledTitlesGroup\x18\x02 \x03(\v2*.jp.co.comic.jump.proto.LabeledTitlesGroupR\x12labeledTitlesGroupb\x06proto3"

var (
	file_labeled_view_proto_rawDescOnce sync.Once
	file_labeled_view_proto_rawDescData []byte
)

func file_labeled_view_proto_rawDescGZIP() []byte {
	file_labeled_view_proto_rawDescOnce.Do(func() {
		file_labeled_view_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_labeled_view_proto_rawDesc), len(file_labeled_view_proto_rawDesc)))
	})
	return file_labeled_view_proto_rawDescData
}

var file_labeled_view_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_labeled_view_proto_goTypes = []any{
	(*LabeledView)(nil),        // 0: jp.co.comic.jump.proto.LabeledView
	(*Label)(nil),              // 1: jp.co.comic.jump.proto.Label
	(*LabeledTitlesGroup)(nil), // 2: jp.co.comic.jump.proto.LabeledTitlesGroup
}
var file_labeled_view_proto_depIdxs = []int32{
	1, // 0: jp.co.comic.jump.proto.LabeledView.label:type_name -> jp.co.comic.jump.proto.Label
	2, // 1: jp.co.comic.jump.proto.LabeledView.labeledTitlesGroup:type_name -> jp.co.comic.jump.proto.LabeledTitlesGroup
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_labeled_view_proto_init() }
func file_labeled_view_proto_init() {
	if File_labeled_view_proto != nil {
		return
	}
	file_label_proto_init()
	file_title_list_group_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_labeled_view_proto_rawDesc), len(file_labeled_view_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_labeled_view_proto_goTypes,
		DependencyIndexes: file_labeled_view_proto_depIdxs,
		MessageInfos:      file_labeled_view_proto_msgTypes,
	}.Build()
	File_labeled_view_proto = out.File
	file_labeled_view_proto_goTypes = nil
	file_labeled_view_proto_depIdxs = nil
}
