// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: label.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LabelCodes int32

const (
	LabelCodes_WJ       LabelCodes = 0
	LabelCodes_SQ       LabelCodes = 1
	LabelCodes_VJ       LabelCodes = 2
	LabelCodes_YJ       LabelCodes = 3
	LabelCodes_J_PLUS   LabelCodes = 4
	LabelCodes_REVIVAL  LabelCodes = 5
	LabelCodes_CREATORS LabelCodes = 6
	LabelCodes_MEE      LabelCodes = 7
	LabelCodes_TYJ      LabelCodes = 8
	LabelCodes_OTHERS   LabelCodes = 9
	LabelCodes_SKJ      LabelCodes = 10
	LabelCodes_GIGA     LabelCodes = 11
	LabelCodes_UJ       LabelCodes = 12
	LabelCodes_DX       LabelCodes = 13
)

// Enum value maps for LabelCodes.
var (
	LabelCodes_name = map[int32]string{
		0:  "WJ",
		1:  "SQ",
		2:  "VJ",
		3:  "YJ",
		4:  "J_PLUS",
		5:  "REVIVAL",
		6:  "CREATORS",
		7:  "MEE",
		8:  "TYJ",
		9:  "OTHERS",
		10: "SKJ",
		11: "GIGA",
		12: "UJ",
		13: "DX",
	}
	LabelCodes_value = map[string]int32{
		"WJ":       0,
		"SQ":       1,
		"VJ":       2,
		"YJ":       3,
		"J_PLUS":   4,
		"REVIVAL":  5,
		"CREATORS": 6,
		"MEE":      7,
		"TYJ":      8,
		"OTHERS":   9,
		"SKJ":      10,
		"GIGA":     11,
		"UJ":       12,
		"DX":       13,
	}
)

func (x LabelCodes) Enum() *LabelCodes {
	p := new(LabelCodes)
	*p = x
	return p
}

func (x LabelCodes) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LabelCodes) Descriptor() protoreflect.EnumDescriptor {
	return file_label_proto_enumTypes[0].Descriptor()
}

func (LabelCodes) Type() protoreflect.EnumType {
	return &file_label_proto_enumTypes[0]
}

func (x LabelCodes) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LabelCodes.Descriptor instead.
func (LabelCodes) EnumDescriptor() ([]byte, []int) {
	return file_label_proto_rawDescGZIP(), []int{0}
}

type Label struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         LabelCodes             `protobuf:"varint,1,opt,name=label,proto3,enum=jp.co.comic.jump.proto.LabelCodes" json:"label,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Label) Reset() {
	*x = Label{}
	mi := &file_label_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Label) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Label) ProtoMessage() {}

func (x *Label) ProtoReflect() protoreflect.Message {
	mi := &file_label_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Label.ProtoReflect.Descriptor instead.
func (*Label) Descriptor() ([]byte, []int) {
	return file_label_proto_rawDescGZIP(), []int{0}
}

func (x *Label) GetLabel() LabelCodes {
	if x != nil {
		return x.Label
	}
	return LabelCodes_WJ
}

func (x *Label) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_label_proto protoreflect.FileDescriptor

const file_label_proto_rawDesc = "" +
	"\n" +
	"\vlabel.proto\x12\x16jp.co.comic.jump.proto\"c\n" +
	"\x05Label\x128\n" +
	"\x05label\x18\x01 \x01(\x0e2\".jp.co.comic.jump.proto.LabelCodesR\x05label\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription*\x94\x01\n" +
	"\n" +
	"LabelCodes\x12\x06\n" +
	"\x02WJ\x10\x00\x12\x06\n" +
	"\x02SQ\x10\x01\x12\x06\n" +
	"\x02VJ\x10\x02\x12\x06\n" +
	"\x02YJ\x10\x03\x12\n" +
	"\n" +
	"\x06J_PLUS\x10\x04\x12\v\n" +
	"\aREVIVAL\x10\x05\x12\f\n" +
	"\bCREATORS\x10\x06\x12\a\n" +
	"\x03MEE\x10\a\x12\a\n" +
	"\x03TYJ\x10\b\x12\n" +
	"\n" +
	"\x06OTHERS\x10\t\x12\a\n" +
	"\x03SKJ\x10\n" +
	"\x12\b\n" +
	"\x04GIGA\x10\v\x12\x06\n" +
	"\x02UJ\x10\f\x12\x06\n" +
	"\x02DX\x10\rb\x06proto3"

var (
	file_label_proto_rawDescOnce sync.Once
	file_label_proto_rawDescData []byte
)

func file_label_proto_rawDescGZIP() []byte {
	file_label_proto_rawDescOnce.Do(func() {
		file_label_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_label_proto_rawDesc), len(file_label_proto_rawDesc)))
	})
	return file_label_proto_rawDescData
}

var file_label_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_label_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_label_proto_goTypes = []any{
	(LabelCodes)(0), // 0: jp.co.comic.jump.proto.LabelCodes
	(*Label)(nil),   // 1: jp.co.comic.jump.proto.Label
}
var file_label_proto_depIdxs = []int32{
	0, // 0: jp.co.comic.jump.proto.Label.label:type_name -> jp.co.comic.jump.proto.LabelCodes
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_label_proto_init() }
func file_label_proto_init() {
	if File_label_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_label_proto_rawDesc), len(file_label_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_label_proto_goTypes,
		DependencyIndexes: file_label_proto_depIdxs,
		EnumInfos:         file_label_proto_enumTypes,
		MessageInfos:      file_label_proto_msgTypes,
	}.Build()
	File_label_proto = out.File
	file_label_proto_goTypes = nil
	file_label_proto_depIdxs = nil
}
