// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: languages.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Language int32

const (
	Language_ENGLISH       Language = 0
	Language_SPANISH       Language = 1
	Language_FRENCH        Language = 2
	Language_INDONESIAN    Language = 3
	Language_PORTUGUESE_BR Language = 4
	Language_RUSSIAN       Language = 5
	Language_THAI          Language = 6
	Language_GERMAN        Language = 7
	Language_ITALIAN       Language = 8
	Language_VIETNAMESE    Language = 9
)

// Enum value maps for Language.
var (
	Language_name = map[int32]string{
		0: "ENGLISH",
		1: "SPANISH",
		2: "FRENCH",
		3: "INDONESIAN",
		4: "PORTUGUESE_BR",
		5: "RUSSIAN",
		6: "THAI",
		7: "GERMAN",
		8: "ITALIAN",
		9: "VIETNAMESE",
	}
	Language_value = map[string]int32{
		"ENGLISH":       0,
		"SPANISH":       1,
		"FRENCH":        2,
		"INDONESIAN":    3,
		"PORTUGUESE_BR": 4,
		"RUSSIAN":       5,
		"THAI":          6,
		"GERMAN":        7,
		"ITALIAN":       8,
		"VIETNAMESE":    9,
	}
)

func (x Language) Enum() *Language {
	p := new(Language)
	*p = x
	return p
}

func (x Language) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Language) Descriptor() protoreflect.EnumDescriptor {
	return file_languages_proto_enumTypes[0].Descriptor()
}

func (Language) Type() protoreflect.EnumType {
	return &file_languages_proto_enumTypes[0]
}

func (x Language) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Language.Descriptor instead.
func (Language) EnumDescriptor() ([]byte, []int) {
	return file_languages_proto_rawDescGZIP(), []int{0}
}

type Languages struct {
	state                       protoimpl.MessageState `protogen:"open.v1"`
	DefaultUiLanguage           Language               `protobuf:"varint,1,opt,name=default_ui_language,json=defaultUiLanguage,proto3,enum=jp.co.comic.jump.proto.Language" json:"default_ui_language,omitempty"`
	DefaultContentLanguageOne   Language               `protobuf:"varint,2,opt,name=default_content_language_one,json=defaultContentLanguageOne,proto3,enum=jp.co.comic.jump.proto.Language" json:"default_content_language_one,omitempty"`
	DefaultContentLanguageTwo   Language               `protobuf:"varint,3,opt,name=default_content_language_two,json=defaultContentLanguageTwo,proto3,enum=jp.co.comic.jump.proto.Language" json:"default_content_language_two,omitempty"`
	DefaultContentLanguageThree Language               `protobuf:"varint,4,opt,name=default_content_language_three,json=defaultContentLanguageThree,proto3,enum=jp.co.comic.jump.proto.Language" json:"default_content_language_three,omitempty"`
	AvailableLanguages          []*AvailableLanguages  `protobuf:"bytes,5,rep,name=available_languages,json=availableLanguages,proto3" json:"available_languages,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *Languages) Reset() {
	*x = Languages{}
	mi := &file_languages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Languages) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Languages) ProtoMessage() {}

func (x *Languages) ProtoReflect() protoreflect.Message {
	mi := &file_languages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Languages.ProtoReflect.Descriptor instead.
func (*Languages) Descriptor() ([]byte, []int) {
	return file_languages_proto_rawDescGZIP(), []int{0}
}

func (x *Languages) GetDefaultUiLanguage() Language {
	if x != nil {
		return x.DefaultUiLanguage
	}
	return Language_ENGLISH
}

func (x *Languages) GetDefaultContentLanguageOne() Language {
	if x != nil {
		return x.DefaultContentLanguageOne
	}
	return Language_ENGLISH
}

func (x *Languages) GetDefaultContentLanguageTwo() Language {
	if x != nil {
		return x.DefaultContentLanguageTwo
	}
	return Language_ENGLISH
}

func (x *Languages) GetDefaultContentLanguageThree() Language {
	if x != nil {
		return x.DefaultContentLanguageThree
	}
	return Language_ENGLISH
}

func (x *Languages) GetAvailableLanguages() []*AvailableLanguages {
	if x != nil {
		return x.AvailableLanguages
	}
	return nil
}

type AvailableLanguages struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Language      Language               `protobuf:"varint,1,opt,name=language,proto3,enum=jp.co.comic.jump.proto.Language" json:"language,omitempty"`
	TitlesCount   uint32                 `protobuf:"varint,2,opt,name=titles_count,json=titlesCount,proto3" json:"titles_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AvailableLanguages) Reset() {
	*x = AvailableLanguages{}
	mi := &file_languages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AvailableLanguages) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvailableLanguages) ProtoMessage() {}

func (x *AvailableLanguages) ProtoReflect() protoreflect.Message {
	mi := &file_languages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvailableLanguages.ProtoReflect.Descriptor instead.
func (*AvailableLanguages) Descriptor() ([]byte, []int) {
	return file_languages_proto_rawDescGZIP(), []int{1}
}

func (x *AvailableLanguages) GetLanguage() Language {
	if x != nil {
		return x.Language
	}
	return Language_ENGLISH
}

func (x *AvailableLanguages) GetTitlesCount() uint32 {
	if x != nil {
		return x.TitlesCount
	}
	return 0
}

var File_languages_proto protoreflect.FileDescriptor

const file_languages_proto_rawDesc = "" +
	"\n" +
	"\x0flanguages.proto\x12\x16jp.co.comic.jump.proto\"\xe7\x03\n" +
	"\tLanguages\x12P\n" +
	"\x13default_ui_language\x18\x01 \x01(\x0e2 .jp.co.comic.jump.proto.LanguageR\x11defaultUiLanguage\x12a\n" +
	"\x1cdefault_content_language_one\x18\x02 \x01(\x0e2 .jp.co.comic.jump.proto.LanguageR\x19defaultContentLanguageOne\x12a\n" +
	"\x1cdefault_content_language_two\x18\x03 \x01(\x0e2 .jp.co.comic.jump.proto.LanguageR\x19defaultContentLanguageTwo\x12e\n" +
	"\x1edefault_content_language_three\x18\x04 \x01(\x0e2 .jp.co.comic.jump.proto.LanguageR\x1bdefaultContentLanguageThree\x12[\n" +
	"\x13available_languages\x18\x05 \x03(\v2*.jp.co.comic.jump.proto.AvailableLanguagesR\x12availableLanguages\"u\n" +
	"\x12AvailableLanguages\x12<\n" +
	"\blanguage\x18\x01 \x01(\x0e2 .jp.co.comic.jump.proto.LanguageR\blanguage\x12!\n" +
	"\ftitles_count\x18\x02 \x01(\rR\vtitlesCount*\x93\x01\n" +
	"\bLanguage\x12\v\n" +
	"\aENGLISH\x10\x00\x12\v\n" +
	"\aSPANISH\x10\x01\x12\n" +
	"\n" +
	"\x06FRENCH\x10\x02\x12\x0e\n" +
	"\n" +
	"INDONESIAN\x10\x03\x12\x11\n" +
	"\rPORTUGUESE_BR\x10\x04\x12\v\n" +
	"\aRUSSIAN\x10\x05\x12\b\n" +
	"\x04THAI\x10\x06\x12\n" +
	"\n" +
	"\x06GERMAN\x10\a\x12\v\n" +
	"\aITALIAN\x10\b\x12\x0e\n" +
	"\n" +
	"VIETNAMESE\x10\tb\x06proto3"

var (
	file_languages_proto_rawDescOnce sync.Once
	file_languages_proto_rawDescData []byte
)

func file_languages_proto_rawDescGZIP() []byte {
	file_languages_proto_rawDescOnce.Do(func() {
		file_languages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_languages_proto_rawDesc), len(file_languages_proto_rawDesc)))
	})
	return file_languages_proto_rawDescData
}

var file_languages_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_languages_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_languages_proto_goTypes = []any{
	(Language)(0),              // 0: jp.co.comic.jump.proto.Language
	(*Languages)(nil),          // 1: jp.co.comic.jump.proto.Languages
	(*AvailableLanguages)(nil), // 2: jp.co.comic.jump.proto.AvailableLanguages
}
var file_languages_proto_depIdxs = []int32{
	0, // 0: jp.co.comic.jump.proto.Languages.default_ui_language:type_name -> jp.co.comic.jump.proto.Language
	0, // 1: jp.co.comic.jump.proto.Languages.default_content_language_one:type_name -> jp.co.comic.jump.proto.Language
	0, // 2: jp.co.comic.jump.proto.Languages.default_content_language_two:type_name -> jp.co.comic.jump.proto.Language
	0, // 3: jp.co.comic.jump.proto.Languages.default_content_language_three:type_name -> jp.co.comic.jump.proto.Language
	2, // 4: jp.co.comic.jump.proto.Languages.available_languages:type_name -> jp.co.comic.jump.proto.AvailableLanguages
	0, // 5: jp.co.comic.jump.proto.AvailableLanguages.language:type_name -> jp.co.comic.jump.proto.Language
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_languages_proto_init() }
func file_languages_proto_init() {
	if File_languages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_languages_proto_rawDesc), len(file_languages_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_languages_proto_goTypes,
		DependencyIndexes: file_languages_proto_depIdxs,
		EnumInfos:         file_languages_proto_enumTypes,
		MessageInfos:      file_languages_proto_msgTypes,
	}.Build()
	File_languages_proto = out.File
	file_languages_proto_goTypes = nil
	file_languages_proto_depIdxs = nil
}
