// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: manga_viewer.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MangaViewer struct {
	state                   protoimpl.MessageState                 `protogen:"open.v1"`
	Pages                   []*Page                                `protobuf:"bytes,1,rep,name=pages,proto3" json:"pages,omitempty"`
	ChapterId               uint32                                 `protobuf:"varint,2,opt,name=chapter_id,json=chapterId,proto3" json:"chapter_id,omitempty"`
	Chapters                []*Chapter                             `protobuf:"bytes,3,rep,name=chapters,proto3" json:"chapters,omitempty"`
	Sns                     *Sns                                   `protobuf:"bytes,4,opt,name=sns,proto3" json:"sns,omitempty"`
	TitleName               string                                 `protobuf:"bytes,5,opt,name=title_name,json=titleName,proto3" json:"title_name,omitempty"`
	ChapterName             string                                 `protobuf:"bytes,6,opt,name=chapter_name,json=chapterName,proto3" json:"chapter_name,omitempty"`
	NumberOfComments        uint32                                 `protobuf:"varint,7,opt,name=number_of_comments,json=numberOfComments,proto3" json:"number_of_comments,omitempty"`
	IsVerticalOnly          bool                                   `protobuf:"varint,8,opt,name=is_vertical_only,json=isVerticalOnly,proto3" json:"is_vertical_only,omitempty"`
	TitleId                 uint32                                 `protobuf:"varint,9,opt,name=titleId,proto3" json:"titleId,omitempty"`
	StartFromRight          bool                                   `protobuf:"varint,10,opt,name=start_from_right,json=startFromRight,proto3" json:"start_from_right,omitempty"`
	RegionCode              string                                 `protobuf:"bytes,11,opt,name=region_code,json=regionCode,proto3" json:"region_code,omitempty"`
	IsHorizontalOnly        bool                                   `protobuf:"varint,12,opt,name=is_horizontal_only,json=isHorizontalOnly,proto3" json:"is_horizontal_only,omitempty"`
	UserSubscription        *Subscription                          `protobuf:"bytes,13,opt,name=user_subscription,json=userSubscription,proto3" json:"user_subscription,omitempty"`
	PlanType                string                                 `protobuf:"bytes,14,opt,name=plan_type,json=planType,proto3" json:"plan_type,omitempty"`
	TitleLanguage           string                                 `protobuf:"bytes,15,opt,name=title_language,json=titleLanguage,proto3" json:"title_language,omitempty"`
	RatingPopup             *Popup                                 `protobuf:"bytes,16,opt,name=rating_popup,json=ratingPopup,proto3" json:"rating_popup,omitempty"`
	TitleAvailableLanguages []*MangaViewer_TitleAvailableLanguages `protobuf:"bytes,17,rep,name=title_available_languages,json=titleAvailableLanguages,proto3" json:"title_available_languages,omitempty"`
	Title                   *Title                                 `protobuf:"bytes,18,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *MangaViewer) Reset() {
	*x = MangaViewer{}
	mi := &file_manga_viewer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MangaViewer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MangaViewer) ProtoMessage() {}

func (x *MangaViewer) ProtoReflect() protoreflect.Message {
	mi := &file_manga_viewer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MangaViewer.ProtoReflect.Descriptor instead.
func (*MangaViewer) Descriptor() ([]byte, []int) {
	return file_manga_viewer_proto_rawDescGZIP(), []int{0}
}

func (x *MangaViewer) GetPages() []*Page {
	if x != nil {
		return x.Pages
	}
	return nil
}

func (x *MangaViewer) GetChapterId() uint32 {
	if x != nil {
		return x.ChapterId
	}
	return 0
}

func (x *MangaViewer) GetChapters() []*Chapter {
	if x != nil {
		return x.Chapters
	}
	return nil
}

func (x *MangaViewer) GetSns() *Sns {
	if x != nil {
		return x.Sns
	}
	return nil
}

func (x *MangaViewer) GetTitleName() string {
	if x != nil {
		return x.TitleName
	}
	return ""
}

func (x *MangaViewer) GetChapterName() string {
	if x != nil {
		return x.ChapterName
	}
	return ""
}

func (x *MangaViewer) GetNumberOfComments() uint32 {
	if x != nil {
		return x.NumberOfComments
	}
	return 0
}

func (x *MangaViewer) GetIsVerticalOnly() bool {
	if x != nil {
		return x.IsVerticalOnly
	}
	return false
}

func (x *MangaViewer) GetTitleId() uint32 {
	if x != nil {
		return x.TitleId
	}
	return 0
}

func (x *MangaViewer) GetStartFromRight() bool {
	if x != nil {
		return x.StartFromRight
	}
	return false
}

func (x *MangaViewer) GetRegionCode() string {
	if x != nil {
		return x.RegionCode
	}
	return ""
}

func (x *MangaViewer) GetIsHorizontalOnly() bool {
	if x != nil {
		return x.IsHorizontalOnly
	}
	return false
}

func (x *MangaViewer) GetUserSubscription() *Subscription {
	if x != nil {
		return x.UserSubscription
	}
	return nil
}

func (x *MangaViewer) GetPlanType() string {
	if x != nil {
		return x.PlanType
	}
	return ""
}

func (x *MangaViewer) GetTitleLanguage() string {
	if x != nil {
		return x.TitleLanguage
	}
	return ""
}

func (x *MangaViewer) GetRatingPopup() *Popup {
	if x != nil {
		return x.RatingPopup
	}
	return nil
}

func (x *MangaViewer) GetTitleAvailableLanguages() []*MangaViewer_TitleAvailableLanguages {
	if x != nil {
		return x.TitleAvailableLanguages
	}
	return nil
}

func (x *MangaViewer) GetTitle() *Title {
	if x != nil {
		return x.Title
	}
	return nil
}

type MangaViewer_TitleAvailableLanguages struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TitleId       uint32                 `protobuf:"varint,1,opt,name=title_id,json=titleId,proto3" json:"title_id,omitempty"`
	Language      Language               `protobuf:"varint,2,opt,name=language,proto3,enum=jp.co.comic.jump.proto.Language" json:"language,omitempty"`
	IsNew         bool                   `protobuf:"varint,3,opt,name=is_new,json=isNew,proto3" json:"is_new,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MangaViewer_TitleAvailableLanguages) Reset() {
	*x = MangaViewer_TitleAvailableLanguages{}
	mi := &file_manga_viewer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MangaViewer_TitleAvailableLanguages) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MangaViewer_TitleAvailableLanguages) ProtoMessage() {}

func (x *MangaViewer_TitleAvailableLanguages) ProtoReflect() protoreflect.Message {
	mi := &file_manga_viewer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MangaViewer_TitleAvailableLanguages.ProtoReflect.Descriptor instead.
func (*MangaViewer_TitleAvailableLanguages) Descriptor() ([]byte, []int) {
	return file_manga_viewer_proto_rawDescGZIP(), []int{0, 0}
}

func (x *MangaViewer_TitleAvailableLanguages) GetTitleId() uint32 {
	if x != nil {
		return x.TitleId
	}
	return 0
}

func (x *MangaViewer_TitleAvailableLanguages) GetLanguage() Language {
	if x != nil {
		return x.Language
	}
	return Language_ENGLISH
}

func (x *MangaViewer_TitleAvailableLanguages) GetIsNew() bool {
	if x != nil {
		return x.IsNew
	}
	return false
}

var File_manga_viewer_proto protoreflect.FileDescriptor

const file_manga_viewer_proto_rawDesc = "" +
	"\n" +
	"\x12manga_viewer.proto\x12\x16jp.co.comic.jump.proto\x1a\rchapter.proto\x1a\x0flanguages.proto\x1a\n" +
	"page.proto\x1a\vpopup.proto\x1a\tsns.proto\x1a\x12subscription.proto\x1a\vtitle.proto\"\x8c\b\n" +
	"\vMangaViewer\x122\n" +
	"\x05pages\x18\x01 \x03(\v2\x1c.jp.co.comic.jump.proto.PageR\x05pages\x12\x1d\n" +
	"\n" +
	"chapter_id\x18\x02 \x01(\rR\tchapterId\x12;\n" +
	"\bchapters\x18\x03 \x03(\v2\x1f.jp.co.comic.jump.proto.ChapterR\bchapters\x12-\n" +
	"\x03sns\x18\x04 \x01(\v2\x1b.jp.co.comic.jump.proto.SnsR\x03sns\x12\x1d\n" +
	"\n" +
	"title_name\x18\x05 \x01(\tR\ttitleName\x12!\n" +
	"\fchapter_name\x18\x06 \x01(\tR\vchapterName\x12,\n" +
	"\x12number_of_comments\x18\a \x01(\rR\x10numberOfComments\x12(\n" +
	"\x10is_vertical_only\x18\b \x01(\bR\x0eisVerticalOnly\x12\x18\n" +
	"\atitleId\x18\t \x01(\rR\atitleId\x12(\n" +
	"\x10start_from_right\x18\n" +
	" \x01(\bR\x0estartFromRight\x12\x1f\n" +
	"\vregion_code\x18\v \x01(\tR\n" +
	"regionCode\x12,\n" +
	"\x12is_horizontal_only\x18\f \x01(\bR\x10isHorizontalOnly\x12Q\n" +
	"\x11user_subscription\x18\r \x01(\v2$.jp.co.comic.jump.proto.SubscriptionR\x10userSubscription\x12\x1b\n" +
	"\tplan_type\x18\x0e \x01(\tR\bplanType\x12%\n" +
	"\x0etitle_language\x18\x0f \x01(\tR\rtitleLanguage\x12@\n" +
	"\frating_popup\x18\x10 \x01(\v2\x1d.jp.co.comic.jump.proto.PopupR\vratingPopup\x12w\n" +
	"\x19title_available_languages\x18\x11 \x03(\v2;.jp.co.comic.jump.proto.MangaViewer.TitleAvailableLanguagesR\x17titleAvailableLanguages\x123\n" +
	"\x05title\x18\x12 \x01(\v2\x1d.jp.co.comic.jump.proto.TitleR\x05title\x1a\x89\x01\n" +
	"\x17TitleAvailableLanguages\x12\x19\n" +
	"\btitle_id\x18\x01 \x01(\rR\atitleId\x12<\n" +
	"\blanguage\x18\x02 \x01(\x0e2 .jp.co.comic.jump.proto.LanguageR\blanguage\x12\x15\n" +
	"\x06is_new\x18\x03 \x01(\bR\x05isNewb\x06proto3"

var (
	file_manga_viewer_proto_rawDescOnce sync.Once
	file_manga_viewer_proto_rawDescData []byte
)

func file_manga_viewer_proto_rawDescGZIP() []byte {
	file_manga_viewer_proto_rawDescOnce.Do(func() {
		file_manga_viewer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_manga_viewer_proto_rawDesc), len(file_manga_viewer_proto_rawDesc)))
	})
	return file_manga_viewer_proto_rawDescData
}

var file_manga_viewer_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_manga_viewer_proto_goTypes = []any{
	(*MangaViewer)(nil),                         // 0: jp.co.comic.jump.proto.MangaViewer
	(*MangaViewer_TitleAvailableLanguages)(nil), // 1: jp.co.comic.jump.proto.MangaViewer.TitleAvailableLanguages
	(*Page)(nil),                                // 2: jp.co.comic.jump.proto.Page
	(*Chapter)(nil),                             // 3: jp.co.comic.jump.proto.Chapter
	(*Sns)(nil),                                 // 4: jp.co.comic.jump.proto.Sns
	(*Subscription)(nil),                        // 5: jp.co.comic.jump.proto.Subscription
	(*Popup)(nil),                               // 6: jp.co.comic.jump.proto.Popup
	(*Title)(nil),                               // 7: jp.co.comic.jump.proto.Title
	(Language)(0),                               // 8: jp.co.comic.jump.proto.Language
}
var file_manga_viewer_proto_depIdxs = []int32{
	2, // 0: jp.co.comic.jump.proto.MangaViewer.pages:type_name -> jp.co.comic.jump.proto.Page
	3, // 1: jp.co.comic.jump.proto.MangaViewer.chapters:type_name -> jp.co.comic.jump.proto.Chapter
	4, // 2: jp.co.comic.jump.proto.MangaViewer.sns:type_name -> jp.co.comic.jump.proto.Sns
	5, // 3: jp.co.comic.jump.proto.MangaViewer.user_subscription:type_name -> jp.co.comic.jump.proto.Subscription
	6, // 4: jp.co.comic.jump.proto.MangaViewer.rating_popup:type_name -> jp.co.comic.jump.proto.Popup
	1, // 5: jp.co.comic.jump.proto.MangaViewer.title_available_languages:type_name -> jp.co.comic.jump.proto.MangaViewer.TitleAvailableLanguages
	7, // 6: jp.co.comic.jump.proto.MangaViewer.title:type_name -> jp.co.comic.jump.proto.Title
	8, // 7: jp.co.comic.jump.proto.MangaViewer.TitleAvailableLanguages.language:type_name -> jp.co.comic.jump.proto.Language
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_manga_viewer_proto_init() }
func file_manga_viewer_proto_init() {
	if File_manga_viewer_proto != nil {
		return
	}
	file_chapter_proto_init()
	file_languages_proto_init()
	file_page_proto_init()
	file_popup_proto_init()
	file_sns_proto_init()
	file_subscription_proto_init()
	file_title_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_manga_viewer_proto_rawDesc), len(file_manga_viewer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_manga_viewer_proto_goTypes,
		DependencyIndexes: file_manga_viewer_proto_depIdxs,
		MessageInfos:      file_manga_viewer_proto_msgTypes,
	}.Build()
	File_manga_viewer_proto = out.File
	file_manga_viewer_proto_goTypes = nil
	file_manga_viewer_proto_depIdxs = nil
}
