// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: mpc_status_view.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MpcStatusView struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	IsMpcMaintenance   bool                   `protobuf:"varint,1,opt,name=is_mpc_maintenance,json=isMpcMaintenance,proto3" json:"is_mpc_maintenance,omitempty"`
	MaintenanceMessage string                 `protobuf:"bytes,2,opt,name=maintenance_message,json=maintenanceMessage,proto3" json:"maintenance_message,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *MpcStatusView) Reset() {
	*x = MpcStatusView{}
	mi := &file_mpc_status_view_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MpcStatusView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MpcStatusView) ProtoMessage() {}

func (x *MpcStatusView) ProtoReflect() protoreflect.Message {
	mi := &file_mpc_status_view_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MpcStatusView.ProtoReflect.Descriptor instead.
func (*MpcStatusView) Descriptor() ([]byte, []int) {
	return file_mpc_status_view_proto_rawDescGZIP(), []int{0}
}

func (x *MpcStatusView) GetIsMpcMaintenance() bool {
	if x != nil {
		return x.IsMpcMaintenance
	}
	return false
}

func (x *MpcStatusView) GetMaintenanceMessage() string {
	if x != nil {
		return x.MaintenanceMessage
	}
	return ""
}

var File_mpc_status_view_proto protoreflect.FileDescriptor

const file_mpc_status_view_proto_rawDesc = "" +
	"\n" +
	"\x15mpc_status_view.proto\x12\x16jp.co.comic.jump.proto\"n\n" +
	"\rMpcStatusView\x12,\n" +
	"\x12is_mpc_maintenance\x18\x01 \x01(\bR\x10isMpcMaintenance\x12/\n" +
	"\x13maintenance_message\x18\x02 \x01(\tR\x12maintenanceMessageb\x06proto3"

var (
	file_mpc_status_view_proto_rawDescOnce sync.Once
	file_mpc_status_view_proto_rawDescData []byte
)

func file_mpc_status_view_proto_rawDescGZIP() []byte {
	file_mpc_status_view_proto_rawDescOnce.Do(func() {
		file_mpc_status_view_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mpc_status_view_proto_rawDesc), len(file_mpc_status_view_proto_rawDesc)))
	})
	return file_mpc_status_view_proto_rawDescData
}

var file_mpc_status_view_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_mpc_status_view_proto_goTypes = []any{
	(*MpcStatusView)(nil), // 0: jp.co.comic.jump.proto.MpcStatusView
}
var file_mpc_status_view_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mpc_status_view_proto_init() }
func file_mpc_status_view_proto_init() {
	if File_mpc_status_view_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mpc_status_view_proto_rawDesc), len(file_mpc_status_view_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mpc_status_view_proto_goTypes,
		DependencyIndexes: file_mpc_status_view_proto_depIdxs,
		MessageInfos:      file_mpc_status_view_proto_msgTypes,
	}.Build()
	File_mpc_status_view_proto = out.File
	file_mpc_status_view_proto_goTypes = nil
	file_mpc_status_view_proto_depIdxs = nil
}
