// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: page.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Page_ChapterType int32

const (
	Page_LATEST     Page_ChapterType = 0
	Page_SEQUENCE   Page_ChapterType = 1
	Page_NOSEQUENCE Page_ChapterType = 2
)

// Enum value maps for Page_ChapterType.
var (
	Page_ChapterType_name = map[int32]string{
		0: "LATEST",
		1: "SEQUENCE",
		2: "NOSEQUENCE",
	}
	Page_ChapterType_value = map[string]int32{
		"LATEST":     0,
		"SEQUENCE":   1,
		"NOSEQUENCE": 2,
	}
)

func (x Page_ChapterType) Enum() *Page_ChapterType {
	p := new(Page_ChapterType)
	*p = x
	return p
}

func (x Page_ChapterType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Page_ChapterType) Descriptor() protoreflect.EnumDescriptor {
	return file_page_proto_enumTypes[0].Descriptor()
}

func (Page_ChapterType) Type() protoreflect.EnumType {
	return &file_page_proto_enumTypes[0]
}

func (x Page_ChapterType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Page_ChapterType.Descriptor instead.
func (Page_ChapterType) EnumDescriptor() ([]byte, []int) {
	return file_page_proto_rawDescGZIP(), []int{0, 0}
}

type Page_PageType int32

const (
	Page_SINGLE Page_PageType = 0
	Page_LEFT   Page_PageType = 1
	Page_RIGHT  Page_PageType = 2
	Page_DOUBLE Page_PageType = 3
)

// Enum value maps for Page_PageType.
var (
	Page_PageType_name = map[int32]string{
		0: "SINGLE",
		1: "LEFT",
		2: "RIGHT",
		3: "DOUBLE",
	}
	Page_PageType_value = map[string]int32{
		"SINGLE": 0,
		"LEFT":   1,
		"RIGHT":  2,
		"DOUBLE": 3,
	}
)

func (x Page_PageType) Enum() *Page_PageType {
	p := new(Page_PageType)
	*p = x
	return p
}

func (x Page_PageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Page_PageType) Descriptor() protoreflect.EnumDescriptor {
	return file_page_proto_enumTypes[1].Descriptor()
}

func (Page_PageType) Type() protoreflect.EnumType {
	return &file_page_proto_enumTypes[1]
}

func (x Page_PageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Page_PageType.Descriptor instead.
func (Page_PageType) EnumDescriptor() ([]byte, []int) {
	return file_page_proto_rawDescGZIP(), []int{0, 1}
}

type Page struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Data:
	//
	//	*Page_MangaPage_
	//	*Page_BannerList_
	//	*Page_LastPage_
	//	*Page_Advertisement
	//	*Page_InsertBannerList
	Data          isPage_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Page) Reset() {
	*x = Page{}
	mi := &file_page_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Page) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Page) ProtoMessage() {}

func (x *Page) ProtoReflect() protoreflect.Message {
	mi := &file_page_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Page.ProtoReflect.Descriptor instead.
func (*Page) Descriptor() ([]byte, []int) {
	return file_page_proto_rawDescGZIP(), []int{0}
}

func (x *Page) GetData() isPage_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Page) GetMangaPage() *Page_MangaPage {
	if x != nil {
		if x, ok := x.Data.(*Page_MangaPage_); ok {
			return x.MangaPage
		}
	}
	return nil
}

func (x *Page) GetBannerList() *Page_BannerList {
	if x != nil {
		if x, ok := x.Data.(*Page_BannerList_); ok {
			return x.BannerList
		}
	}
	return nil
}

func (x *Page) GetLastPage() *Page_LastPage {
	if x != nil {
		if x, ok := x.Data.(*Page_LastPage_); ok {
			return x.LastPage
		}
	}
	return nil
}

func (x *Page) GetAdvertisement() *AdNetworkList {
	if x != nil {
		if x, ok := x.Data.(*Page_Advertisement); ok {
			return x.Advertisement
		}
	}
	return nil
}

func (x *Page) GetInsertBannerList() *Page_BannerList {
	if x != nil {
		if x, ok := x.Data.(*Page_InsertBannerList); ok {
			return x.InsertBannerList
		}
	}
	return nil
}

type isPage_Data interface {
	isPage_Data()
}

type Page_MangaPage_ struct {
	MangaPage *Page_MangaPage `protobuf:"bytes,1,opt,name=manga_page,json=mangaPage,proto3,oneof"`
}

type Page_BannerList_ struct {
	BannerList *Page_BannerList `protobuf:"bytes,2,opt,name=banner_list,json=bannerList,proto3,oneof"`
}

type Page_LastPage_ struct {
	LastPage *Page_LastPage `protobuf:"bytes,3,opt,name=last_page,json=lastPage,proto3,oneof"`
}

type Page_Advertisement struct {
	Advertisement *AdNetworkList `protobuf:"bytes,4,opt,name=advertisement,proto3,oneof"`
}

type Page_InsertBannerList struct {
	InsertBannerList *Page_BannerList `protobuf:"bytes,5,opt,name=insert_banner_list,json=insertBannerList,proto3,oneof"`
}

func (*Page_MangaPage_) isPage_Data() {}

func (*Page_BannerList_) isPage_Data() {}

func (*Page_LastPage_) isPage_Data() {}

func (*Page_Advertisement) isPage_Data() {}

func (*Page_InsertBannerList) isPage_Data() {}

type Page_MangaPage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageUrl      string                 `protobuf:"bytes,1,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	Width         uint32                 `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	Height        uint32                 `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	Type          Page_PageType          `protobuf:"varint,4,opt,name=type,proto3,enum=jp.co.comic.jump.proto.Page_PageType" json:"type,omitempty"`
	EncryptionKey string                 `protobuf:"bytes,5,opt,name=encryption_key,json=encryptionKey,proto3" json:"encryption_key,omitempty"`
	MerchStoreUrl *string                `protobuf:"bytes,6,opt,name=merch_store_url,json=merchStoreUrl,proto3,oneof" json:"merch_store_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Page_MangaPage) Reset() {
	*x = Page_MangaPage{}
	mi := &file_page_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Page_MangaPage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Page_MangaPage) ProtoMessage() {}

func (x *Page_MangaPage) ProtoReflect() protoreflect.Message {
	mi := &file_page_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Page_MangaPage.ProtoReflect.Descriptor instead.
func (*Page_MangaPage) Descriptor() ([]byte, []int) {
	return file_page_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Page_MangaPage) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *Page_MangaPage) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Page_MangaPage) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Page_MangaPage) GetType() Page_PageType {
	if x != nil {
		return x.Type
	}
	return Page_SINGLE
}

func (x *Page_MangaPage) GetEncryptionKey() string {
	if x != nil {
		return x.EncryptionKey
	}
	return ""
}

func (x *Page_MangaPage) GetMerchStoreUrl() string {
	if x != nil && x.MerchStoreUrl != nil {
		return *x.MerchStoreUrl
	}
	return ""
}

type Page_LastPage struct {
	state                     protoimpl.MessageState          `protogen:"open.v1"`
	CurrentChapter            *Chapter                        `protobuf:"bytes,1,opt,name=current_chapter,json=currentChapter,proto3" json:"current_chapter,omitempty"`
	NextChapter               *Chapter                        `protobuf:"bytes,2,opt,name=next_chapter,json=nextChapter,proto3" json:"next_chapter,omitempty"`
	TopComments               []*Comment                      `protobuf:"bytes,3,rep,name=top_comments,json=topComments,proto3" json:"top_comments,omitempty"`
	IsSubscribed              bool                            `protobuf:"varint,4,opt,name=is_subscribed,json=isSubscribed,proto3" json:"is_subscribed,omitempty"`
	NextTimeStamp             uint32                          `protobuf:"varint,5,opt,name=next_time_stamp,json=nextTimeStamp,proto3" json:"next_time_stamp,omitempty"`
	ChapterType               Page_ChapterType                `protobuf:"varint,6,opt,name=chapter_type,json=chapterType,proto3,enum=jp.co.comic.jump.proto.Page_ChapterType" json:"chapter_type,omitempty"`
	Advertisement             *AdNetworkList                  `protobuf:"bytes,7,opt,name=advertisement,proto3" json:"advertisement,omitempty"`
	MovieReward               *Popup                          `protobuf:"bytes,8,opt,name=movie_reward,json=movieReward,proto3" json:"movie_reward,omitempty"`
	Banners                   []*Banner                       `protobuf:"bytes,9,rep,name=banners,proto3" json:"banners,omitempty"`
	TicketTitleList           []*Title                        `protobuf:"bytes,10,rep,name=ticket_title_list,json=ticketTitleList,proto3" json:"ticket_title_list,omitempty"`
	PublisherBanner           *Banner                         `protobuf:"bytes,11,opt,name=publisher_banner,json=publisherBanner,proto3" json:"publisher_banner,omitempty"`
	UserTickets               *UserTickets                    `protobuf:"bytes,12,opt,name=user_tickets,json=userTickets,proto3" json:"user_tickets,omitempty"`
	IsNextChapterReadByTicket bool                            `protobuf:"varint,13,opt,name=is_next_chapter_read_by_ticket,json=isNextChapterReadByTicket,proto3" json:"is_next_chapter_read_by_ticket,omitempty"`
	IsNextChapterOneTimeFree  bool                            `protobuf:"varint,14,opt,name=is_next_chapter_one_time_free,json=isNextChapterOneTimeFree,proto3" json:"is_next_chapter_one_time_free,omitempty"`
	FreeViewDialogue          *FreeViewDialogue               `protobuf:"bytes,15,opt,name=free_view_dialogue,json=freeViewDialogue,proto3" json:"free_view_dialogue,omitempty"`
	IsNextChapterSubscription bool                            `protobuf:"varint,16,opt,name=is_next_chapter_subscription,json=isNextChapterSubscription,proto3" json:"is_next_chapter_subscription,omitempty"`
	AdvertisementReward       *AdRewardNetworkList            `protobuf:"bytes,17,opt,name=advertisement_reward,json=advertisementReward,proto3" json:"advertisement_reward,omitempty"`
	ViewerEndAdvertisement    *AdNetworkList                  `protobuf:"bytes,18,opt,name=viewer_end_advertisement,json=viewerEndAdvertisement,proto3" json:"viewer_end_advertisement,omitempty"`
	PlanTypes                 []*PlanType                     `protobuf:"bytes,19,rep,name=plan_types,json=planTypes,proto3" json:"plan_types,omitempty"`
	UserHasUsedTrial          bool                            `protobuf:"varint,20,opt,name=user_has_used_trial,json=userHasUsedTrial,proto3" json:"user_has_used_trial,omitempty"`
	PlanBoxDescription        *SubscriptionPlanBoxDescription `protobuf:"bytes,21,opt,name=plan_box_description,json=planBoxDescription,proto3" json:"plan_box_description,omitempty"`
	Note                      *SubscriptionNote               `protobuf:"bytes,22,opt,name=note,proto3" json:"note,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *Page_LastPage) Reset() {
	*x = Page_LastPage{}
	mi := &file_page_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Page_LastPage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Page_LastPage) ProtoMessage() {}

func (x *Page_LastPage) ProtoReflect() protoreflect.Message {
	mi := &file_page_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Page_LastPage.ProtoReflect.Descriptor instead.
func (*Page_LastPage) Descriptor() ([]byte, []int) {
	return file_page_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Page_LastPage) GetCurrentChapter() *Chapter {
	if x != nil {
		return x.CurrentChapter
	}
	return nil
}

func (x *Page_LastPage) GetNextChapter() *Chapter {
	if x != nil {
		return x.NextChapter
	}
	return nil
}

func (x *Page_LastPage) GetTopComments() []*Comment {
	if x != nil {
		return x.TopComments
	}
	return nil
}

func (x *Page_LastPage) GetIsSubscribed() bool {
	if x != nil {
		return x.IsSubscribed
	}
	return false
}

func (x *Page_LastPage) GetNextTimeStamp() uint32 {
	if x != nil {
		return x.NextTimeStamp
	}
	return 0
}

func (x *Page_LastPage) GetChapterType() Page_ChapterType {
	if x != nil {
		return x.ChapterType
	}
	return Page_LATEST
}

func (x *Page_LastPage) GetAdvertisement() *AdNetworkList {
	if x != nil {
		return x.Advertisement
	}
	return nil
}

func (x *Page_LastPage) GetMovieReward() *Popup {
	if x != nil {
		return x.MovieReward
	}
	return nil
}

func (x *Page_LastPage) GetBanners() []*Banner {
	if x != nil {
		return x.Banners
	}
	return nil
}

func (x *Page_LastPage) GetTicketTitleList() []*Title {
	if x != nil {
		return x.TicketTitleList
	}
	return nil
}

func (x *Page_LastPage) GetPublisherBanner() *Banner {
	if x != nil {
		return x.PublisherBanner
	}
	return nil
}

func (x *Page_LastPage) GetUserTickets() *UserTickets {
	if x != nil {
		return x.UserTickets
	}
	return nil
}

func (x *Page_LastPage) GetIsNextChapterReadByTicket() bool {
	if x != nil {
		return x.IsNextChapterReadByTicket
	}
	return false
}

func (x *Page_LastPage) GetIsNextChapterOneTimeFree() bool {
	if x != nil {
		return x.IsNextChapterOneTimeFree
	}
	return false
}

func (x *Page_LastPage) GetFreeViewDialogue() *FreeViewDialogue {
	if x != nil {
		return x.FreeViewDialogue
	}
	return nil
}

func (x *Page_LastPage) GetIsNextChapterSubscription() bool {
	if x != nil {
		return x.IsNextChapterSubscription
	}
	return false
}

func (x *Page_LastPage) GetAdvertisementReward() *AdRewardNetworkList {
	if x != nil {
		return x.AdvertisementReward
	}
	return nil
}

func (x *Page_LastPage) GetViewerEndAdvertisement() *AdNetworkList {
	if x != nil {
		return x.ViewerEndAdvertisement
	}
	return nil
}

func (x *Page_LastPage) GetPlanTypes() []*PlanType {
	if x != nil {
		return x.PlanTypes
	}
	return nil
}

func (x *Page_LastPage) GetUserHasUsedTrial() bool {
	if x != nil {
		return x.UserHasUsedTrial
	}
	return false
}

func (x *Page_LastPage) GetPlanBoxDescription() *SubscriptionPlanBoxDescription {
	if x != nil {
		return x.PlanBoxDescription
	}
	return nil
}

func (x *Page_LastPage) GetNote() *SubscriptionNote {
	if x != nil {
		return x.Note
	}
	return nil
}

type Page_BannerList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BannerTitle   string                 `protobuf:"bytes,1,opt,name=banner_title,json=bannerTitle,proto3" json:"banner_title,omitempty"`
	Banners       []*Banner              `protobuf:"bytes,2,rep,name=banners,proto3" json:"banners,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Page_BannerList) Reset() {
	*x = Page_BannerList{}
	mi := &file_page_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Page_BannerList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Page_BannerList) ProtoMessage() {}

func (x *Page_BannerList) ProtoReflect() protoreflect.Message {
	mi := &file_page_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Page_BannerList.ProtoReflect.Descriptor instead.
func (*Page_BannerList) Descriptor() ([]byte, []int) {
	return file_page_proto_rawDescGZIP(), []int{0, 2}
}

func (x *Page_BannerList) GetBannerTitle() string {
	if x != nil {
		return x.BannerTitle
	}
	return ""
}

func (x *Page_BannerList) GetBanners() []*Banner {
	if x != nil {
		return x.Banners
	}
	return nil
}

var File_page_proto protoreflect.FileDescriptor

const file_page_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"page.proto\x12\x16jp.co.comic.jump.proto\x1a\x10ad_network.proto\x1a\fbanner.proto\x1a\rchapter.proto\x1a\rcomment.proto\x1a\x0edialogue.proto\x1a\vpopup.proto\x1a\x12subscription.proto\x1a\vtitle.proto\x1a\x12user_tickets.proto\"\x80\x13\n" +
	"\x04Page\x12G\n" +
	"\n" +
	"manga_page\x18\x01 \x01(\v2&.jp.co.comic.jump.proto.Page.MangaPageH\x00R\tmangaPage\x12J\n" +
	"\vbanner_list\x18\x02 \x01(\v2'.jp.co.comic.jump.proto.Page.BannerListH\x00R\n" +
	"bannerList\x12D\n" +
	"\tlast_page\x18\x03 \x01(\v2%.jp.co.comic.jump.proto.Page.LastPageH\x00R\blastPage\x12M\n" +
	"\radvertisement\x18\x04 \x01(\v2%.jp.co.comic.jump.proto.AdNetworkListH\x00R\radvertisement\x12W\n" +
	"\x12insert_banner_list\x18\x05 \x01(\v2'.jp.co.comic.jump.proto.Page.BannerListH\x00R\x10insertBannerList\x1a\xf9\x01\n" +
	"\tMangaPage\x12\x1b\n" +
	"\timage_url\x18\x01 \x01(\tR\bimageUrl\x12\x14\n" +
	"\x05width\x18\x02 \x01(\rR\x05width\x12\x16\n" +
	"\x06height\x18\x03 \x01(\rR\x06height\x129\n" +
	"\x04type\x18\x04 \x01(\x0e2%.jp.co.comic.jump.proto.Page.PageTypeR\x04type\x12%\n" +
	"\x0eencryption_key\x18\x05 \x01(\tR\rencryptionKey\x12+\n" +
	"\x0fmerch_store_url\x18\x06 \x01(\tH\x00R\rmerchStoreUrl\x88\x01\x01B\x12\n" +
	"\x10_merch_store_url\x1a\x93\f\n" +
	"\bLastPage\x12H\n" +
	"\x0fcurrent_chapter\x18\x01 \x01(\v2\x1f.jp.co.comic.jump.proto.ChapterR\x0ecurrentChapter\x12B\n" +
	"\fnext_chapter\x18\x02 \x01(\v2\x1f.jp.co.comic.jump.proto.ChapterR\vnextChapter\x12B\n" +
	"\ftop_comments\x18\x03 \x03(\v2\x1f.jp.co.comic.jump.proto.CommentR\vtopComments\x12#\n" +
	"\ris_subscribed\x18\x04 \x01(\bR\fisSubscribed\x12&\n" +
	"\x0fnext_time_stamp\x18\x05 \x01(\rR\rnextTimeStamp\x12K\n" +
	"\fchapter_type\x18\x06 \x01(\x0e2(.jp.co.comic.jump.proto.Page.ChapterTypeR\vchapterType\x12K\n" +
	"\radvertisement\x18\a \x01(\v2%.jp.co.comic.jump.proto.AdNetworkListR\radvertisement\x12@\n" +
	"\fmovie_reward\x18\b \x01(\v2\x1d.jp.co.comic.jump.proto.PopupR\vmovieReward\x128\n" +
	"\abanners\x18\t \x03(\v2\x1e.jp.co.comic.jump.proto.BannerR\abanners\x12I\n" +
	"\x11ticket_title_list\x18\n" +
	" \x03(\v2\x1d.jp.co.comic.jump.proto.TitleR\x0fticketTitleList\x12I\n" +
	"\x10publisher_banner\x18\v \x01(\v2\x1e.jp.co.comic.jump.proto.BannerR\x0fpublisherBanner\x12F\n" +
	"\fuser_tickets\x18\f \x01(\v2#.jp.co.comic.jump.proto.UserTicketsR\vuserTickets\x12A\n" +
	"\x1eis_next_chapter_read_by_ticket\x18\r \x01(\bR\x19isNextChapterReadByTicket\x12?\n" +
	"\x1dis_next_chapter_one_time_free\x18\x0e \x01(\bR\x18isNextChapterOneTimeFree\x12V\n" +
	"\x12free_view_dialogue\x18\x0f \x01(\v2(.jp.co.comic.jump.proto.FreeViewDialogueR\x10freeViewDialogue\x12?\n" +
	"\x1cis_next_chapter_subscription\x18\x10 \x01(\bR\x19isNextChapterSubscription\x12^\n" +
	"\x14advertisement_reward\x18\x11 \x01(\v2+.jp.co.comic.jump.proto.AdRewardNetworkListR\x13advertisementReward\x12_\n" +
	"\x18viewer_end_advertisement\x18\x12 \x01(\v2%.jp.co.comic.jump.proto.AdNetworkListR\x16viewerEndAdvertisement\x12?\n" +
	"\n" +
	"plan_types\x18\x13 \x03(\v2 .jp.co.comic.jump.proto.PlanTypeR\tplanTypes\x12-\n" +
	"\x13user_has_used_trial\x18\x14 \x01(\bR\x10userHasUsedTrial\x12h\n" +
	"\x14plan_box_description\x18\x15 \x01(\v26.jp.co.comic.jump.proto.SubscriptionPlanBoxDescriptionR\x12planBoxDescription\x12<\n" +
	"\x04note\x18\x16 \x01(\v2(.jp.co.comic.jump.proto.SubscriptionNoteR\x04note\x1ai\n" +
	"\n" +
	"BannerList\x12!\n" +
	"\fbanner_title\x18\x01 \x01(\tR\vbannerTitle\x128\n" +
	"\abanners\x18\x02 \x03(\v2\x1e.jp.co.comic.jump.proto.BannerR\abanners\"7\n" +
	"\vChapterType\x12\n" +
	"\n" +
	"\x06LATEST\x10\x00\x12\f\n" +
	"\bSEQUENCE\x10\x01\x12\x0e\n" +
	"\n" +
	"NOSEQUENCE\x10\x02\"7\n" +
	"\bPageType\x12\n" +
	"\n" +
	"\x06SINGLE\x10\x00\x12\b\n" +
	"\x04LEFT\x10\x01\x12\t\n" +
	"\x05RIGHT\x10\x02\x12\n" +
	"\n" +
	"\x06DOUBLE\x10\x03B\x06\n" +
	"\x04datab\x06proto3"

var (
	file_page_proto_rawDescOnce sync.Once
	file_page_proto_rawDescData []byte
)

func file_page_proto_rawDescGZIP() []byte {
	file_page_proto_rawDescOnce.Do(func() {
		file_page_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_page_proto_rawDesc), len(file_page_proto_rawDesc)))
	})
	return file_page_proto_rawDescData
}

var file_page_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_page_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_page_proto_goTypes = []any{
	(Page_ChapterType)(0),                  // 0: jp.co.comic.jump.proto.Page.ChapterType
	(Page_PageType)(0),                     // 1: jp.co.comic.jump.proto.Page.PageType
	(*Page)(nil),                           // 2: jp.co.comic.jump.proto.Page
	(*Page_MangaPage)(nil),                 // 3: jp.co.comic.jump.proto.Page.MangaPage
	(*Page_LastPage)(nil),                  // 4: jp.co.comic.jump.proto.Page.LastPage
	(*Page_BannerList)(nil),                // 5: jp.co.comic.jump.proto.Page.BannerList
	(*AdNetworkList)(nil),                  // 6: jp.co.comic.jump.proto.AdNetworkList
	(*Chapter)(nil),                        // 7: jp.co.comic.jump.proto.Chapter
	(*Comment)(nil),                        // 8: jp.co.comic.jump.proto.Comment
	(*Popup)(nil),                          // 9: jp.co.comic.jump.proto.Popup
	(*Banner)(nil),                         // 10: jp.co.comic.jump.proto.Banner
	(*Title)(nil),                          // 11: jp.co.comic.jump.proto.Title
	(*UserTickets)(nil),                    // 12: jp.co.comic.jump.proto.UserTickets
	(*FreeViewDialogue)(nil),               // 13: jp.co.comic.jump.proto.FreeViewDialogue
	(*AdRewardNetworkList)(nil),            // 14: jp.co.comic.jump.proto.AdRewardNetworkList
	(*PlanType)(nil),                       // 15: jp.co.comic.jump.proto.PlanType
	(*SubscriptionPlanBoxDescription)(nil), // 16: jp.co.comic.jump.proto.SubscriptionPlanBoxDescription
	(*SubscriptionNote)(nil),               // 17: jp.co.comic.jump.proto.SubscriptionNote
}
var file_page_proto_depIdxs = []int32{
	3,  // 0: jp.co.comic.jump.proto.Page.manga_page:type_name -> jp.co.comic.jump.proto.Page.MangaPage
	5,  // 1: jp.co.comic.jump.proto.Page.banner_list:type_name -> jp.co.comic.jump.proto.Page.BannerList
	4,  // 2: jp.co.comic.jump.proto.Page.last_page:type_name -> jp.co.comic.jump.proto.Page.LastPage
	6,  // 3: jp.co.comic.jump.proto.Page.advertisement:type_name -> jp.co.comic.jump.proto.AdNetworkList
	5,  // 4: jp.co.comic.jump.proto.Page.insert_banner_list:type_name -> jp.co.comic.jump.proto.Page.BannerList
	1,  // 5: jp.co.comic.jump.proto.Page.MangaPage.type:type_name -> jp.co.comic.jump.proto.Page.PageType
	7,  // 6: jp.co.comic.jump.proto.Page.LastPage.current_chapter:type_name -> jp.co.comic.jump.proto.Chapter
	7,  // 7: jp.co.comic.jump.proto.Page.LastPage.next_chapter:type_name -> jp.co.comic.jump.proto.Chapter
	8,  // 8: jp.co.comic.jump.proto.Page.LastPage.top_comments:type_name -> jp.co.comic.jump.proto.Comment
	0,  // 9: jp.co.comic.jump.proto.Page.LastPage.chapter_type:type_name -> jp.co.comic.jump.proto.Page.ChapterType
	6,  // 10: jp.co.comic.jump.proto.Page.LastPage.advertisement:type_name -> jp.co.comic.jump.proto.AdNetworkList
	9,  // 11: jp.co.comic.jump.proto.Page.LastPage.movie_reward:type_name -> jp.co.comic.jump.proto.Popup
	10, // 12: jp.co.comic.jump.proto.Page.LastPage.banners:type_name -> jp.co.comic.jump.proto.Banner
	11, // 13: jp.co.comic.jump.proto.Page.LastPage.ticket_title_list:type_name -> jp.co.comic.jump.proto.Title
	10, // 14: jp.co.comic.jump.proto.Page.LastPage.publisher_banner:type_name -> jp.co.comic.jump.proto.Banner
	12, // 15: jp.co.comic.jump.proto.Page.LastPage.user_tickets:type_name -> jp.co.comic.jump.proto.UserTickets
	13, // 16: jp.co.comic.jump.proto.Page.LastPage.free_view_dialogue:type_name -> jp.co.comic.jump.proto.FreeViewDialogue
	14, // 17: jp.co.comic.jump.proto.Page.LastPage.advertisement_reward:type_name -> jp.co.comic.jump.proto.AdRewardNetworkList
	6,  // 18: jp.co.comic.jump.proto.Page.LastPage.viewer_end_advertisement:type_name -> jp.co.comic.jump.proto.AdNetworkList
	15, // 19: jp.co.comic.jump.proto.Page.LastPage.plan_types:type_name -> jp.co.comic.jump.proto.PlanType
	16, // 20: jp.co.comic.jump.proto.Page.LastPage.plan_box_description:type_name -> jp.co.comic.jump.proto.SubscriptionPlanBoxDescription
	17, // 21: jp.co.comic.jump.proto.Page.LastPage.note:type_name -> jp.co.comic.jump.proto.SubscriptionNote
	10, // 22: jp.co.comic.jump.proto.Page.BannerList.banners:type_name -> jp.co.comic.jump.proto.Banner
	23, // [23:23] is the sub-list for method output_type
	23, // [23:23] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_page_proto_init() }
func file_page_proto_init() {
	if File_page_proto != nil {
		return
	}
	file_ad_network_proto_init()
	file_banner_proto_init()
	file_chapter_proto_init()
	file_comment_proto_init()
	file_dialogue_proto_init()
	file_popup_proto_init()
	file_subscription_proto_init()
	file_title_proto_init()
	file_user_tickets_proto_init()
	file_page_proto_msgTypes[0].OneofWrappers = []any{
		(*Page_MangaPage_)(nil),
		(*Page_BannerList_)(nil),
		(*Page_LastPage_)(nil),
		(*Page_Advertisement)(nil),
		(*Page_InsertBannerList)(nil),
	}
	file_page_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_page_proto_rawDesc), len(file_page_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_page_proto_goTypes,
		DependencyIndexes: file_page_proto_depIdxs,
		EnumInfos:         file_page_proto_enumTypes,
		MessageInfos:      file_page_proto_msgTypes,
	}.Build()
	File_page_proto = out.File
	file_page_proto_goTypes = nil
	file_page_proto_depIdxs = nil
}
