// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: popup.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Popup struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Popup:
	//
	//	*Popup_OsDefault
	//	*Popup_AppDefault_
	//	*Popup_MovieReward
	//	*Popup_OneImage_
	Popup         isPopup_Popup `protobuf_oneof:"popup"`
	PopupId       uint32        `protobuf:"varint,5,opt,name=popup_id,json=popupId,proto3" json:"popup_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Popup) Reset() {
	*x = Popup{}
	mi := &file_popup_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Popup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Popup) ProtoMessage() {}

func (x *Popup) ProtoReflect() protoreflect.Message {
	mi := &file_popup_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Popup.ProtoReflect.Descriptor instead.
func (*Popup) Descriptor() ([]byte, []int) {
	return file_popup_proto_rawDescGZIP(), []int{0}
}

func (x *Popup) GetPopup() isPopup_Popup {
	if x != nil {
		return x.Popup
	}
	return nil
}

func (x *Popup) GetOsDefault() *Popup_OSDefault {
	if x != nil {
		if x, ok := x.Popup.(*Popup_OsDefault); ok {
			return x.OsDefault
		}
	}
	return nil
}

func (x *Popup) GetAppDefault() *Popup_AppDefault {
	if x != nil {
		if x, ok := x.Popup.(*Popup_AppDefault_); ok {
			return x.AppDefault
		}
	}
	return nil
}

func (x *Popup) GetMovieReward() *MovieReward {
	if x != nil {
		if x, ok := x.Popup.(*Popup_MovieReward); ok {
			return x.MovieReward
		}
	}
	return nil
}

func (x *Popup) GetOneImage() *Popup_OneImage {
	if x != nil {
		if x, ok := x.Popup.(*Popup_OneImage_); ok {
			return x.OneImage
		}
	}
	return nil
}

func (x *Popup) GetPopupId() uint32 {
	if x != nil {
		return x.PopupId
	}
	return 0
}

type isPopup_Popup interface {
	isPopup_Popup()
}

type Popup_OsDefault struct {
	OsDefault *Popup_OSDefault `protobuf:"bytes,1,opt,name=os_default,json=osDefault,proto3,oneof"`
}

type Popup_AppDefault_ struct {
	AppDefault *Popup_AppDefault `protobuf:"bytes,2,opt,name=app_default,json=appDefault,proto3,oneof"`
}

type Popup_MovieReward struct {
	MovieReward *MovieReward `protobuf:"bytes,3,opt,name=movie_reward,json=movieReward,proto3,oneof"`
}

type Popup_OneImage_ struct {
	OneImage *Popup_OneImage `protobuf:"bytes,4,opt,name=one_image,json=oneImage,proto3,oneof"`
}

func (*Popup_OsDefault) isPopup_Popup() {}

func (*Popup_AppDefault_) isPopup_Popup() {}

func (*Popup_MovieReward) isPopup_Popup() {}

func (*Popup_OneImage_) isPopup_Popup() {}

type MovieReward struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageUrl      string                 `protobuf:"bytes,1,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	Advertisement *AdNetworkList         `protobuf:"bytes,2,opt,name=advertisement,proto3" json:"advertisement,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MovieReward) Reset() {
	*x = MovieReward{}
	mi := &file_popup_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MovieReward) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MovieReward) ProtoMessage() {}

func (x *MovieReward) ProtoReflect() protoreflect.Message {
	mi := &file_popup_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MovieReward.ProtoReflect.Descriptor instead.
func (*MovieReward) Descriptor() ([]byte, []int) {
	return file_popup_proto_rawDescGZIP(), []int{1}
}

func (x *MovieReward) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *MovieReward) GetAdvertisement() *AdNetworkList {
	if x != nil {
		return x.Advertisement
	}
	return nil
}

type Popup_OSDefault struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subject       string                 `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Body          string                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	OkButton      *Popup_Button          `protobuf:"bytes,3,opt,name=ok_button,json=okButton,proto3" json:"ok_button,omitempty"`
	NeutralButton *Popup_Button          `protobuf:"bytes,4,opt,name=neutral_button,json=neutralButton,proto3" json:"neutral_button,omitempty"`
	CancelButton  *Popup_Button          `protobuf:"bytes,5,opt,name=cancel_button,json=cancelButton,proto3" json:"cancel_button,omitempty"`
	Language      Language               `protobuf:"varint,6,opt,name=language,proto3,enum=jp.co.comic.jump.proto.Language" json:"language,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Popup_OSDefault) Reset() {
	*x = Popup_OSDefault{}
	mi := &file_popup_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Popup_OSDefault) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Popup_OSDefault) ProtoMessage() {}

func (x *Popup_OSDefault) ProtoReflect() protoreflect.Message {
	mi := &file_popup_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Popup_OSDefault.ProtoReflect.Descriptor instead.
func (*Popup_OSDefault) Descriptor() ([]byte, []int) {
	return file_popup_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Popup_OSDefault) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *Popup_OSDefault) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Popup_OSDefault) GetOkButton() *Popup_Button {
	if x != nil {
		return x.OkButton
	}
	return nil
}

func (x *Popup_OSDefault) GetNeutralButton() *Popup_Button {
	if x != nil {
		return x.NeutralButton
	}
	return nil
}

func (x *Popup_OSDefault) GetCancelButton() *Popup_Button {
	if x != nil {
		return x.CancelButton
	}
	return nil
}

func (x *Popup_OSDefault) GetLanguage() Language {
	if x != nil {
		return x.Language
	}
	return Language_ENGLISH
}

type Popup_AppDefault struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subject       string                 `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Body          string                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	Action        *TransitionAction      `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,4,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Popup_AppDefault) Reset() {
	*x = Popup_AppDefault{}
	mi := &file_popup_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Popup_AppDefault) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Popup_AppDefault) ProtoMessage() {}

func (x *Popup_AppDefault) ProtoReflect() protoreflect.Message {
	mi := &file_popup_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Popup_AppDefault.ProtoReflect.Descriptor instead.
func (*Popup_AppDefault) Descriptor() ([]byte, []int) {
	return file_popup_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Popup_AppDefault) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *Popup_AppDefault) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Popup_AppDefault) GetAction() *TransitionAction {
	if x != nil {
		return x.Action
	}
	return nil
}

func (x *Popup_AppDefault) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

type Popup_OneImage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        *TransitionAction      `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,2,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Popup_OneImage) Reset() {
	*x = Popup_OneImage{}
	mi := &file_popup_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Popup_OneImage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Popup_OneImage) ProtoMessage() {}

func (x *Popup_OneImage) ProtoReflect() protoreflect.Message {
	mi := &file_popup_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Popup_OneImage.ProtoReflect.Descriptor instead.
func (*Popup_OneImage) Descriptor() ([]byte, []int) {
	return file_popup_proto_rawDescGZIP(), []int{0, 2}
}

func (x *Popup_OneImage) GetAction() *TransitionAction {
	if x != nil {
		return x.Action
	}
	return nil
}

func (x *Popup_OneImage) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

type Popup_Button struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Action        *TransitionAction      `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Popup_Button) Reset() {
	*x = Popup_Button{}
	mi := &file_popup_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Popup_Button) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Popup_Button) ProtoMessage() {}

func (x *Popup_Button) ProtoReflect() protoreflect.Message {
	mi := &file_popup_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Popup_Button.ProtoReflect.Descriptor instead.
func (*Popup_Button) Descriptor() ([]byte, []int) {
	return file_popup_proto_rawDescGZIP(), []int{0, 3}
}

func (x *Popup_Button) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Popup_Button) GetAction() *TransitionAction {
	if x != nil {
		return x.Action
	}
	return nil
}

var File_popup_proto protoreflect.FileDescriptor

const file_popup_proto_rawDesc = "" +
	"\n" +
	"\vpopup.proto\x12\x16jp.co.comic.jump.proto\x1a\x10ad_network.proto\x1a\x0flanguages.proto\x1a\x17transition_action.proto\"\x8f\b\n" +
	"\x05Popup\x12H\n" +
	"\n" +
	"os_default\x18\x01 \x01(\v2'.jp.co.comic.jump.proto.Popup.OSDefaultH\x00R\tosDefault\x12K\n" +
	"\vapp_default\x18\x02 \x01(\v2(.jp.co.comic.jump.proto.Popup.AppDefaultH\x00R\n" +
	"appDefault\x12H\n" +
	"\fmovie_reward\x18\x03 \x01(\v2#.jp.co.comic.jump.proto.MovieRewardH\x00R\vmovieReward\x12E\n" +
	"\tone_image\x18\x04 \x01(\v2&.jp.co.comic.jump.proto.Popup.OneImageH\x00R\boneImage\x12\x19\n" +
	"\bpopup_id\x18\x05 \x01(\rR\apopupId\x1a\xd2\x02\n" +
	"\tOSDefault\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12\x12\n" +
	"\x04body\x18\x02 \x01(\tR\x04body\x12A\n" +
	"\tok_button\x18\x03 \x01(\v2$.jp.co.comic.jump.proto.Popup.ButtonR\bokButton\x12K\n" +
	"\x0eneutral_button\x18\x04 \x01(\v2$.jp.co.comic.jump.proto.Popup.ButtonR\rneutralButton\x12I\n" +
	"\rcancel_button\x18\x05 \x01(\v2$.jp.co.comic.jump.proto.Popup.ButtonR\fcancelButton\x12<\n" +
	"\blanguage\x18\x06 \x01(\x0e2 .jp.co.comic.jump.proto.LanguageR\blanguage\x1a\x99\x01\n" +
	"\n" +
	"AppDefault\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12\x12\n" +
	"\x04body\x18\x02 \x01(\tR\x04body\x12@\n" +
	"\x06action\x18\x03 \x01(\v2(.jp.co.comic.jump.proto.TransitionActionR\x06action\x12\x1b\n" +
	"\timage_url\x18\x04 \x01(\tR\bimageUrl\x1ai\n" +
	"\bOneImage\x12@\n" +
	"\x06action\x18\x01 \x01(\v2(.jp.co.comic.jump.proto.TransitionActionR\x06action\x12\x1b\n" +
	"\timage_url\x18\x02 \x01(\tR\bimageUrl\x1a^\n" +
	"\x06Button\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12@\n" +
	"\x06action\x18\x02 \x01(\v2(.jp.co.comic.jump.proto.TransitionActionR\x06actionB\a\n" +
	"\x05popup\"w\n" +
	"\vMovieReward\x12\x1b\n" +
	"\timage_url\x18\x01 \x01(\tR\bimageUrl\x12K\n" +
	"\radvertisement\x18\x02 \x01(\v2%.jp.co.comic.jump.proto.AdNetworkListR\radvertisementb\x06proto3"

var (
	file_popup_proto_rawDescOnce sync.Once
	file_popup_proto_rawDescData []byte
)

func file_popup_proto_rawDescGZIP() []byte {
	file_popup_proto_rawDescOnce.Do(func() {
		file_popup_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_popup_proto_rawDesc), len(file_popup_proto_rawDesc)))
	})
	return file_popup_proto_rawDescData
}

var file_popup_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_popup_proto_goTypes = []any{
	(*Popup)(nil),            // 0: jp.co.comic.jump.proto.Popup
	(*MovieReward)(nil),      // 1: jp.co.comic.jump.proto.MovieReward
	(*Popup_OSDefault)(nil),  // 2: jp.co.comic.jump.proto.Popup.OSDefault
	(*Popup_AppDefault)(nil), // 3: jp.co.comic.jump.proto.Popup.AppDefault
	(*Popup_OneImage)(nil),   // 4: jp.co.comic.jump.proto.Popup.OneImage
	(*Popup_Button)(nil),     // 5: jp.co.comic.jump.proto.Popup.Button
	(*AdNetworkList)(nil),    // 6: jp.co.comic.jump.proto.AdNetworkList
	(Language)(0),            // 7: jp.co.comic.jump.proto.Language
	(*TransitionAction)(nil), // 8: jp.co.comic.jump.proto.TransitionAction
}
var file_popup_proto_depIdxs = []int32{
	2,  // 0: jp.co.comic.jump.proto.Popup.os_default:type_name -> jp.co.comic.jump.proto.Popup.OSDefault
	3,  // 1: jp.co.comic.jump.proto.Popup.app_default:type_name -> jp.co.comic.jump.proto.Popup.AppDefault
	1,  // 2: jp.co.comic.jump.proto.Popup.movie_reward:type_name -> jp.co.comic.jump.proto.MovieReward
	4,  // 3: jp.co.comic.jump.proto.Popup.one_image:type_name -> jp.co.comic.jump.proto.Popup.OneImage
	6,  // 4: jp.co.comic.jump.proto.MovieReward.advertisement:type_name -> jp.co.comic.jump.proto.AdNetworkList
	5,  // 5: jp.co.comic.jump.proto.Popup.OSDefault.ok_button:type_name -> jp.co.comic.jump.proto.Popup.Button
	5,  // 6: jp.co.comic.jump.proto.Popup.OSDefault.neutral_button:type_name -> jp.co.comic.jump.proto.Popup.Button
	5,  // 7: jp.co.comic.jump.proto.Popup.OSDefault.cancel_button:type_name -> jp.co.comic.jump.proto.Popup.Button
	7,  // 8: jp.co.comic.jump.proto.Popup.OSDefault.language:type_name -> jp.co.comic.jump.proto.Language
	8,  // 9: jp.co.comic.jump.proto.Popup.AppDefault.action:type_name -> jp.co.comic.jump.proto.TransitionAction
	8,  // 10: jp.co.comic.jump.proto.Popup.OneImage.action:type_name -> jp.co.comic.jump.proto.TransitionAction
	8,  // 11: jp.co.comic.jump.proto.Popup.Button.action:type_name -> jp.co.comic.jump.proto.TransitionAction
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_popup_proto_init() }
func file_popup_proto_init() {
	if File_popup_proto != nil {
		return
	}
	file_ad_network_proto_init()
	file_languages_proto_init()
	file_transition_action_proto_init()
	file_popup_proto_msgTypes[0].OneofWrappers = []any{
		(*Popup_OsDefault)(nil),
		(*Popup_AppDefault_)(nil),
		(*Popup_MovieReward)(nil),
		(*Popup_OneImage_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_popup_proto_rawDesc), len(file_popup_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_popup_proto_goTypes,
		DependencyIndexes: file_popup_proto_depIdxs,
		MessageInfos:      file_popup_proto_msgTypes,
	}.Build()
	File_popup_proto = out.File
	file_popup_proto_goTypes = nil
	file_popup_proto_depIdxs = nil
}
