// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: profile_settings_view.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProfileSettingsView struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IconList      []*CommentIcon         `protobuf:"bytes,1,rep,name=icon_list,json=iconList,proto3" json:"icon_list,omitempty"`
	UserName      string                 `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	MyIcon        *CommentIcon           `protobuf:"bytes,3,opt,name=my_icon,json=myIcon,proto3" json:"my_icon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfileSettingsView) Reset() {
	*x = ProfileSettingsView{}
	mi := &file_profile_settings_view_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileSettingsView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileSettingsView) ProtoMessage() {}

func (x *ProfileSettingsView) ProtoReflect() protoreflect.Message {
	mi := &file_profile_settings_view_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileSettingsView.ProtoReflect.Descriptor instead.
func (*ProfileSettingsView) Descriptor() ([]byte, []int) {
	return file_profile_settings_view_proto_rawDescGZIP(), []int{0}
}

func (x *ProfileSettingsView) GetIconList() []*CommentIcon {
	if x != nil {
		return x.IconList
	}
	return nil
}

func (x *ProfileSettingsView) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *ProfileSettingsView) GetMyIcon() *CommentIcon {
	if x != nil {
		return x.MyIcon
	}
	return nil
}

var File_profile_settings_view_proto protoreflect.FileDescriptor

const file_profile_settings_view_proto_rawDesc = "" +
	"\n" +
	"\x1bprofile_settings_view.proto\x12\x16jp.co.comic.jump.proto\x1a\x12comment_icon.proto\"\xb2\x01\n" +
	"\x13ProfileSettingsView\x12@\n" +
	"\ticon_list\x18\x01 \x03(\v2#.jp.co.comic.jump.proto.CommentIconR\biconList\x12\x1b\n" +
	"\tuser_name\x18\x02 \x01(\tR\buserName\x12<\n" +
	"\amy_icon\x18\x03 \x01(\v2#.jp.co.comic.jump.proto.CommentIconR\x06myIconb\x06proto3"

var (
	file_profile_settings_view_proto_rawDescOnce sync.Once
	file_profile_settings_view_proto_rawDescData []byte
)

func file_profile_settings_view_proto_rawDescGZIP() []byte {
	file_profile_settings_view_proto_rawDescOnce.Do(func() {
		file_profile_settings_view_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_profile_settings_view_proto_rawDesc), len(file_profile_settings_view_proto_rawDesc)))
	})
	return file_profile_settings_view_proto_rawDescData
}

var file_profile_settings_view_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_profile_settings_view_proto_goTypes = []any{
	(*ProfileSettingsView)(nil), // 0: jp.co.comic.jump.proto.ProfileSettingsView
	(*CommentIcon)(nil),         // 1: jp.co.comic.jump.proto.CommentIcon
}
var file_profile_settings_view_proto_depIdxs = []int32{
	1, // 0: jp.co.comic.jump.proto.ProfileSettingsView.icon_list:type_name -> jp.co.comic.jump.proto.CommentIcon
	1, // 1: jp.co.comic.jump.proto.ProfileSettingsView.my_icon:type_name -> jp.co.comic.jump.proto.CommentIcon
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_profile_settings_view_proto_init() }
func file_profile_settings_view_proto_init() {
	if File_profile_settings_view_proto != nil {
		return
	}
	file_comment_icon_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_profile_settings_view_proto_rawDesc), len(file_profile_settings_view_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_profile_settings_view_proto_goTypes,
		DependencyIndexes: file_profile_settings_view_proto_depIdxs,
		MessageInfos:      file_profile_settings_view_proto_msgTypes,
	}.Build()
	File_profile_settings_view_proto = out.File
	file_profile_settings_view_proto_goTypes = nil
	file_profile_settings_view_proto_depIdxs = nil
}
