// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: publisher_news_list_view.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PublisherNewsListView struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublisherId   uint32                 `protobuf:"varint,1,opt,name=publisher_id,json=publisherId,proto3" json:"publisher_id,omitempty"`
	PublisherName string                 `protobuf:"bytes,2,opt,name=publisher_name,json=publisherName,proto3" json:"publisher_name,omitempty"`
	Banner        *Banner                `protobuf:"bytes,3,opt,name=banner,proto3" json:"banner,omitempty"`
	NewsList      []*PublisherNews       `protobuf:"bytes,4,rep,name=news_list,json=newsList,proto3" json:"news_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublisherNewsListView) Reset() {
	*x = PublisherNewsListView{}
	mi := &file_publisher_news_list_view_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublisherNewsListView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublisherNewsListView) ProtoMessage() {}

func (x *PublisherNewsListView) ProtoReflect() protoreflect.Message {
	mi := &file_publisher_news_list_view_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublisherNewsListView.ProtoReflect.Descriptor instead.
func (*PublisherNewsListView) Descriptor() ([]byte, []int) {
	return file_publisher_news_list_view_proto_rawDescGZIP(), []int{0}
}

func (x *PublisherNewsListView) GetPublisherId() uint32 {
	if x != nil {
		return x.PublisherId
	}
	return 0
}

func (x *PublisherNewsListView) GetPublisherName() string {
	if x != nil {
		return x.PublisherName
	}
	return ""
}

func (x *PublisherNewsListView) GetBanner() *Banner {
	if x != nil {
		return x.Banner
	}
	return nil
}

func (x *PublisherNewsListView) GetNewsList() []*PublisherNews {
	if x != nil {
		return x.NewsList
	}
	return nil
}

var File_publisher_news_list_view_proto protoreflect.FileDescriptor

const file_publisher_news_list_view_proto_rawDesc = "" +
	"\n" +
	"\x1epublisher_news_list_view.proto\x12\x16jp.co.comic.jump.proto\x1a\fbanner.proto\x1a\x14publisher_news.proto\"\xdd\x01\n" +
	"\x15PublisherNewsListView\x12!\n" +
	"\fpublisher_id\x18\x01 \x01(\rR\vpublisherId\x12%\n" +
	"\x0epublisher_name\x18\x02 \x01(\tR\rpublisherName\x126\n" +
	"\x06banner\x18\x03 \x01(\v2\x1e.jp.co.comic.jump.proto.BannerR\x06banner\x12B\n" +
	"\tnews_list\x18\x04 \x03(\v2%.jp.co.comic.jump.proto.PublisherNewsR\bnewsListb\x06proto3"

var (
	file_publisher_news_list_view_proto_rawDescOnce sync.Once
	file_publisher_news_list_view_proto_rawDescData []byte
)

func file_publisher_news_list_view_proto_rawDescGZIP() []byte {
	file_publisher_news_list_view_proto_rawDescOnce.Do(func() {
		file_publisher_news_list_view_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_publisher_news_list_view_proto_rawDesc), len(file_publisher_news_list_view_proto_rawDesc)))
	})
	return file_publisher_news_list_view_proto_rawDescData
}

var file_publisher_news_list_view_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_publisher_news_list_view_proto_goTypes = []any{
	(*PublisherNewsListView)(nil), // 0: jp.co.comic.jump.proto.PublisherNewsListView
	(*Banner)(nil),                // 1: jp.co.comic.jump.proto.Banner
	(*PublisherNews)(nil),         // 2: jp.co.comic.jump.proto.PublisherNews
}
var file_publisher_news_list_view_proto_depIdxs = []int32{
	1, // 0: jp.co.comic.jump.proto.PublisherNewsListView.banner:type_name -> jp.co.comic.jump.proto.Banner
	2, // 1: jp.co.comic.jump.proto.PublisherNewsListView.news_list:type_name -> jp.co.comic.jump.proto.PublisherNews
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_publisher_news_list_view_proto_init() }
func file_publisher_news_list_view_proto_init() {
	if File_publisher_news_list_view_proto != nil {
		return
	}
	file_banner_proto_init()
	file_publisher_news_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_publisher_news_list_view_proto_rawDesc), len(file_publisher_news_list_view_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_publisher_news_list_view_proto_goTypes,
		DependencyIndexes: file_publisher_news_list_view_proto_depIdxs,
		MessageInfos:      file_publisher_news_list_view_proto_msgTypes,
	}.Build()
	File_publisher_news_list_view_proto = out.File
	file_publisher_news_list_view_proto_goTypes = nil
	file_publisher_news_list_view_proto_depIdxs = nil
}
