// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: publisher_news.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PublisherNews struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PublisherId        uint32                 `protobuf:"varint,2,opt,name=publisher_id,json=publisherId,proto3" json:"publisher_id,omitempty"`
	PublisherName      string                 `protobuf:"bytes,3,opt,name=publisher_name,json=publisherName,proto3" json:"publisher_name,omitempty"`
	Subject            string                 `protobuf:"bytes,4,opt,name=subject,proto3" json:"subject,omitempty"`
	Body               string                 `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	PublishedTimeStamp uint32                 `protobuf:"varint,6,opt,name=published_time_stamp,json=publishedTimeStamp,proto3" json:"published_time_stamp,omitempty"`
	Action             *TransitionAction      `protobuf:"bytes,7,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PublisherNews) Reset() {
	*x = PublisherNews{}
	mi := &file_publisher_news_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublisherNews) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublisherNews) ProtoMessage() {}

func (x *PublisherNews) ProtoReflect() protoreflect.Message {
	mi := &file_publisher_news_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublisherNews.ProtoReflect.Descriptor instead.
func (*PublisherNews) Descriptor() ([]byte, []int) {
	return file_publisher_news_proto_rawDescGZIP(), []int{0}
}

func (x *PublisherNews) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PublisherNews) GetPublisherId() uint32 {
	if x != nil {
		return x.PublisherId
	}
	return 0
}

func (x *PublisherNews) GetPublisherName() string {
	if x != nil {
		return x.PublisherName
	}
	return ""
}

func (x *PublisherNews) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *PublisherNews) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *PublisherNews) GetPublishedTimeStamp() uint32 {
	if x != nil {
		return x.PublishedTimeStamp
	}
	return 0
}

func (x *PublisherNews) GetAction() *TransitionAction {
	if x != nil {
		return x.Action
	}
	return nil
}

var File_publisher_news_proto protoreflect.FileDescriptor

const file_publisher_news_proto_rawDesc = "" +
	"\n" +
	"\x14publisher_news.proto\x12\x16jp.co.comic.jump.proto\x1a\x17transition_action.proto\"\x8b\x02\n" +
	"\rPublisherNews\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12!\n" +
	"\fpublisher_id\x18\x02 \x01(\rR\vpublisherId\x12%\n" +
	"\x0epublisher_name\x18\x03 \x01(\tR\rpublisherName\x12\x18\n" +
	"\asubject\x18\x04 \x01(\tR\asubject\x12\x12\n" +
	"\x04body\x18\x05 \x01(\tR\x04body\x120\n" +
	"\x14published_time_stamp\x18\x06 \x01(\rR\x12publishedTimeStamp\x12@\n" +
	"\x06action\x18\a \x01(\v2(.jp.co.comic.jump.proto.TransitionActionR\x06actionb\x06proto3"

var (
	file_publisher_news_proto_rawDescOnce sync.Once
	file_publisher_news_proto_rawDescData []byte
)

func file_publisher_news_proto_rawDescGZIP() []byte {
	file_publisher_news_proto_rawDescOnce.Do(func() {
		file_publisher_news_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_publisher_news_proto_rawDesc), len(file_publisher_news_proto_rawDesc)))
	})
	return file_publisher_news_proto_rawDescData
}

var file_publisher_news_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_publisher_news_proto_goTypes = []any{
	(*PublisherNews)(nil),    // 0: jp.co.comic.jump.proto.PublisherNews
	(*TransitionAction)(nil), // 1: jp.co.comic.jump.proto.TransitionAction
}
var file_publisher_news_proto_depIdxs = []int32{
	1, // 0: jp.co.comic.jump.proto.PublisherNews.action:type_name -> jp.co.comic.jump.proto.TransitionAction
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_publisher_news_proto_init() }
func file_publisher_news_proto_init() {
	if File_publisher_news_proto != nil {
		return
	}
	file_transition_action_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_publisher_news_proto_rawDesc), len(file_publisher_news_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_publisher_news_proto_goTypes,
		DependencyIndexes: file_publisher_news_proto_depIdxs,
		MessageInfos:      file_publisher_news_proto_msgTypes,
	}.Build()
	File_publisher_news_proto = out.File
	file_publisher_news_proto_goTypes = nil
	file_publisher_news_proto_depIdxs = nil
}
