// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: push_token_view.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PushTokenView struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Token          string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	TokenTimeStamp uint32                 `protobuf:"varint,2,opt,name=token_time_stamp,json=tokenTimeStamp,proto3" json:"token_time_stamp,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PushTokenView) Reset() {
	*x = PushTokenView{}
	mi := &file_push_token_view_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushTokenView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushTokenView) ProtoMessage() {}

func (x *PushTokenView) ProtoReflect() protoreflect.Message {
	mi := &file_push_token_view_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushTokenView.ProtoReflect.Descriptor instead.
func (*PushTokenView) Descriptor() ([]byte, []int) {
	return file_push_token_view_proto_rawDescGZIP(), []int{0}
}

func (x *PushTokenView) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *PushTokenView) GetTokenTimeStamp() uint32 {
	if x != nil {
		return x.TokenTimeStamp
	}
	return 0
}

var File_push_token_view_proto protoreflect.FileDescriptor

const file_push_token_view_proto_rawDesc = "" +
	"\n" +
	"\x15push_token_view.proto\x12\x16jp.co.comic.jump.proto\"O\n" +
	"\rPushTokenView\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12(\n" +
	"\x10token_time_stamp\x18\x02 \x01(\rR\x0etokenTimeStampb\x06proto3"

var (
	file_push_token_view_proto_rawDescOnce sync.Once
	file_push_token_view_proto_rawDescData []byte
)

func file_push_token_view_proto_rawDescGZIP() []byte {
	file_push_token_view_proto_rawDescOnce.Do(func() {
		file_push_token_view_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_push_token_view_proto_rawDesc), len(file_push_token_view_proto_rawDesc)))
	})
	return file_push_token_view_proto_rawDescData
}

var file_push_token_view_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_push_token_view_proto_goTypes = []any{
	(*PushTokenView)(nil), // 0: jp.co.comic.jump.proto.PushTokenView
}
var file_push_token_view_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_push_token_view_proto_init() }
func file_push_token_view_proto_init() {
	if File_push_token_view_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_push_token_view_proto_rawDesc), len(file_push_token_view_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_push_token_view_proto_goTypes,
		DependencyIndexes: file_push_token_view_proto_depIdxs,
		MessageInfos:      file_push_token_view_proto_msgTypes,
	}.Build()
	File_push_token_view_proto = out.File
	file_push_token_view_proto_goTypes = nil
	file_push_token_view_proto_depIdxs = nil
}
