// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: questionnaire.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Questionnaire struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Description     string                 `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	Selection       []string               `protobuf:"bytes,2,rep,name=selection,proto3" json:"selection,omitempty"`
	NumberOfChoices uint32                 `protobuf:"varint,3,opt,name=numberOfChoices,proto3" json:"numberOfChoices,omitempty"`
	HideFreeform    bool                   `protobuf:"varint,4,opt,name=hideFreeform,proto3" json:"hideFreeform,omitempty"`
	FreeForm        string                 `protobuf:"bytes,5,opt,name=freeForm,proto3" json:"freeForm,omitempty"`
	CanSkip         bool                   `protobuf:"varint,6,opt,name=canSkip,proto3" json:"canSkip,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Questionnaire) Reset() {
	*x = Questionnaire{}
	mi := &file_questionnaire_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Questionnaire) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Questionnaire) ProtoMessage() {}

func (x *Questionnaire) ProtoReflect() protoreflect.Message {
	mi := &file_questionnaire_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Questionnaire.ProtoReflect.Descriptor instead.
func (*Questionnaire) Descriptor() ([]byte, []int) {
	return file_questionnaire_proto_rawDescGZIP(), []int{0}
}

func (x *Questionnaire) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Questionnaire) GetSelection() []string {
	if x != nil {
		return x.Selection
	}
	return nil
}

func (x *Questionnaire) GetNumberOfChoices() uint32 {
	if x != nil {
		return x.NumberOfChoices
	}
	return 0
}

func (x *Questionnaire) GetHideFreeform() bool {
	if x != nil {
		return x.HideFreeform
	}
	return false
}

func (x *Questionnaire) GetFreeForm() string {
	if x != nil {
		return x.FreeForm
	}
	return ""
}

func (x *Questionnaire) GetCanSkip() bool {
	if x != nil {
		return x.CanSkip
	}
	return false
}

var File_questionnaire_proto protoreflect.FileDescriptor

const file_questionnaire_proto_rawDesc = "" +
	"\n" +
	"\x13questionnaire.proto\x12\x16jp.co.comic.jump.proto\"\xd3\x01\n" +
	"\rQuestionnaire\x12 \n" +
	"\vdescription\x18\x01 \x01(\tR\vdescription\x12\x1c\n" +
	"\tselection\x18\x02 \x03(\tR\tselection\x12(\n" +
	"\x0fnumberOfChoices\x18\x03 \x01(\rR\x0fnumberOfChoices\x12\"\n" +
	"\fhideFreeform\x18\x04 \x01(\bR\fhideFreeform\x12\x1a\n" +
	"\bfreeForm\x18\x05 \x01(\tR\bfreeForm\x12\x18\n" +
	"\acanSkip\x18\x06 \x01(\bR\acanSkipb\x06proto3"

var (
	file_questionnaire_proto_rawDescOnce sync.Once
	file_questionnaire_proto_rawDescData []byte
)

func file_questionnaire_proto_rawDescGZIP() []byte {
	file_questionnaire_proto_rawDescOnce.Do(func() {
		file_questionnaire_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_questionnaire_proto_rawDesc), len(file_questionnaire_proto_rawDesc)))
	})
	return file_questionnaire_proto_rawDescData
}

var file_questionnaire_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_questionnaire_proto_goTypes = []any{
	(*Questionnaire)(nil), // 0: jp.co.comic.jump.proto.Questionnaire
}
var file_questionnaire_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_questionnaire_proto_init() }
func file_questionnaire_proto_init() {
	if File_questionnaire_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_questionnaire_proto_rawDesc), len(file_questionnaire_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_questionnaire_proto_goTypes,
		DependencyIndexes: file_questionnaire_proto_depIdxs,
		MessageInfos:      file_questionnaire_proto_msgTypes,
	}.Build()
	File_questionnaire_proto = out.File
	file_questionnaire_proto_goTypes = nil
	file_questionnaire_proto_depIdxs = nil
}
