// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: questionnaire_view.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QuestionnaireView struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsAnswered    bool                   `protobuf:"varint,1,opt,name=is_answered,json=isAnswered,proto3" json:"is_answered,omitempty"`
	Subject       string                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	Questions     []*Questionnaire       `protobuf:"bytes,3,rep,name=questions,proto3" json:"questions,omitempty"`
	Language      Language               `protobuf:"varint,4,opt,name=language,proto3,enum=jp.co.comic.jump.proto.Language" json:"language,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuestionnaireView) Reset() {
	*x = QuestionnaireView{}
	mi := &file_questionnaire_view_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuestionnaireView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuestionnaireView) ProtoMessage() {}

func (x *QuestionnaireView) ProtoReflect() protoreflect.Message {
	mi := &file_questionnaire_view_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuestionnaireView.ProtoReflect.Descriptor instead.
func (*QuestionnaireView) Descriptor() ([]byte, []int) {
	return file_questionnaire_view_proto_rawDescGZIP(), []int{0}
}

func (x *QuestionnaireView) GetIsAnswered() bool {
	if x != nil {
		return x.IsAnswered
	}
	return false
}

func (x *QuestionnaireView) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *QuestionnaireView) GetQuestions() []*Questionnaire {
	if x != nil {
		return x.Questions
	}
	return nil
}

func (x *QuestionnaireView) GetLanguage() Language {
	if x != nil {
		return x.Language
	}
	return Language_ENGLISH
}

var File_questionnaire_view_proto protoreflect.FileDescriptor

const file_questionnaire_view_proto_rawDesc = "" +
	"\n" +
	"\x18questionnaire_view.proto\x12\x16jp.co.comic.jump.proto\x1a\x0flanguages.proto\x1a\x13questionnaire.proto\"\xd1\x01\n" +
	"\x11QuestionnaireView\x12\x1f\n" +
	"\vis_answered\x18\x01 \x01(\bR\n" +
	"isAnswered\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12C\n" +
	"\tquestions\x18\x03 \x03(\v2%.jp.co.comic.jump.proto.QuestionnaireR\tquestions\x12<\n" +
	"\blanguage\x18\x04 \x01(\x0e2 .jp.co.comic.jump.proto.LanguageR\blanguageb\x06proto3"

var (
	file_questionnaire_view_proto_rawDescOnce sync.Once
	file_questionnaire_view_proto_rawDescData []byte
)

func file_questionnaire_view_proto_rawDescGZIP() []byte {
	file_questionnaire_view_proto_rawDescOnce.Do(func() {
		file_questionnaire_view_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_questionnaire_view_proto_rawDesc), len(file_questionnaire_view_proto_rawDesc)))
	})
	return file_questionnaire_view_proto_rawDescData
}

var file_questionnaire_view_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_questionnaire_view_proto_goTypes = []any{
	(*QuestionnaireView)(nil), // 0: jp.co.comic.jump.proto.QuestionnaireView
	(*Questionnaire)(nil),     // 1: jp.co.comic.jump.proto.Questionnaire
	(Language)(0),             // 2: jp.co.comic.jump.proto.Language
}
var file_questionnaire_view_proto_depIdxs = []int32{
	1, // 0: jp.co.comic.jump.proto.QuestionnaireView.questions:type_name -> jp.co.comic.jump.proto.Questionnaire
	2, // 1: jp.co.comic.jump.proto.QuestionnaireView.language:type_name -> jp.co.comic.jump.proto.Language
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_questionnaire_view_proto_init() }
func file_questionnaire_view_proto_init() {
	if File_questionnaire_view_proto != nil {
		return
	}
	file_languages_proto_init()
	file_questionnaire_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_questionnaire_view_proto_rawDesc), len(file_questionnaire_view_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_questionnaire_view_proto_goTypes,
		DependencyIndexes: file_questionnaire_view_proto_depIdxs,
		MessageInfos:      file_questionnaire_view_proto_msgTypes,
	}.Build()
	File_questionnaire_view_proto = out.File
	file_questionnaire_view_proto_goTypes = nil
	file_questionnaire_view_proto_depIdxs = nil
}
