// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: registration_data.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegistrationData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceSecret  string                 `protobuf:"bytes,1,opt,name=device_secret,json=deviceSecret,proto3" json:"device_secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistrationData) Reset() {
	*x = RegistrationData{}
	mi := &file_registration_data_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistrationData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationData) ProtoMessage() {}

func (x *RegistrationData) ProtoReflect() protoreflect.Message {
	mi := &file_registration_data_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationData.ProtoReflect.Descriptor instead.
func (*RegistrationData) Descriptor() ([]byte, []int) {
	return file_registration_data_proto_rawDescGZIP(), []int{0}
}

func (x *RegistrationData) GetDeviceSecret() string {
	if x != nil {
		return x.DeviceSecret
	}
	return ""
}

var File_registration_data_proto protoreflect.FileDescriptor

const file_registration_data_proto_rawDesc = "" +
	"\n" +
	"\x17registration_data.proto\x12\x16jp.co.comic.jump.proto\"7\n" +
	"\x10RegistrationData\x12#\n" +
	"\rdevice_secret\x18\x01 \x01(\tR\fdeviceSecretb\x06proto3"

var (
	file_registration_data_proto_rawDescOnce sync.Once
	file_registration_data_proto_rawDescData []byte
)

func file_registration_data_proto_rawDescGZIP() []byte {
	file_registration_data_proto_rawDescOnce.Do(func() {
		file_registration_data_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_registration_data_proto_rawDesc), len(file_registration_data_proto_rawDesc)))
	})
	return file_registration_data_proto_rawDescData
}

var file_registration_data_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_registration_data_proto_goTypes = []any{
	(*RegistrationData)(nil), // 0: jp.co.comic.jump.proto.RegistrationData
}
var file_registration_data_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_registration_data_proto_init() }
func file_registration_data_proto_init() {
	if File_registration_data_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_registration_data_proto_rawDesc), len(file_registration_data_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_registration_data_proto_goTypes,
		DependencyIndexes: file_registration_data_proto_depIdxs,
		MessageInfos:      file_registration_data_proto_msgTypes,
	}.Build()
	File_registration_data_proto = out.File
	file_registration_data_proto_goTypes = nil
	file_registration_data_proto_depIdxs = nil
}
