// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: search_view.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchView struct {
	state            protoimpl.MessageState         `protogen:"open.v1"`
	TopSearchBanners []*Banner                      `protobuf:"bytes,1,rep,name=top_search_banners,json=topSearchBanners,proto3" json:"top_search_banners,omitempty"`
	AllTags          []*Tag                         `protobuf:"bytes,2,rep,name=all_tags,json=allTags,proto3" json:"all_tags,omitempty"`
	AllTitlesGroup   []*AllTitlesGroup              `protobuf:"bytes,3,rep,name=all_titles_group,json=allTitlesGroup,proto3" json:"all_titles_group,omitempty"`
	Contents         []*FeaturedTitlesView_Contents `protobuf:"bytes,5,rep,name=contents,proto3" json:"contents,omitempty"`
	AllLabels        []*LabelV2                     `protobuf:"bytes,6,rep,name=all_labels,json=allLabels,proto3" json:"all_labels,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SearchView) Reset() {
	*x = SearchView{}
	mi := &file_search_view_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchView) ProtoMessage() {}

func (x *SearchView) ProtoReflect() protoreflect.Message {
	mi := &file_search_view_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchView.ProtoReflect.Descriptor instead.
func (*SearchView) Descriptor() ([]byte, []int) {
	return file_search_view_proto_rawDescGZIP(), []int{0}
}

func (x *SearchView) GetTopSearchBanners() []*Banner {
	if x != nil {
		return x.TopSearchBanners
	}
	return nil
}

func (x *SearchView) GetAllTags() []*Tag {
	if x != nil {
		return x.AllTags
	}
	return nil
}

func (x *SearchView) GetAllTitlesGroup() []*AllTitlesGroup {
	if x != nil {
		return x.AllTitlesGroup
	}
	return nil
}

func (x *SearchView) GetContents() []*FeaturedTitlesView_Contents {
	if x != nil {
		return x.Contents
	}
	return nil
}

func (x *SearchView) GetAllLabels() []*LabelV2 {
	if x != nil {
		return x.AllLabels
	}
	return nil
}

type SearchView_Contents struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Banner           *Banner                `protobuf:"bytes,1,opt,name=banner,proto3" json:"banner,omitempty"`
	TitleList        *TitleList             `protobuf:"bytes,2,opt,name=title_list,json=titleList,proto3" json:"title_list,omitempty"`
	RankedTitles     []*TitleRankingGroup   `protobuf:"bytes,3,rep,name=ranked_titles,json=rankedTitles,proto3" json:"ranked_titles,omitempty"`
	AllLabels        []*Label               `protobuf:"bytes,4,rep,name=all_labels,json=allLabels,proto3" json:"all_labels,omitempty"`
	ChapterPagesList *ChapterPageList       `protobuf:"bytes,5,opt,name=chapter_pages_list,json=chapterPagesList,proto3" json:"chapter_pages_list,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SearchView_Contents) Reset() {
	*x = SearchView_Contents{}
	mi := &file_search_view_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchView_Contents) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchView_Contents) ProtoMessage() {}

func (x *SearchView_Contents) ProtoReflect() protoreflect.Message {
	mi := &file_search_view_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchView_Contents.ProtoReflect.Descriptor instead.
func (*SearchView_Contents) Descriptor() ([]byte, []int) {
	return file_search_view_proto_rawDescGZIP(), []int{0, 0}
}

func (x *SearchView_Contents) GetBanner() *Banner {
	if x != nil {
		return x.Banner
	}
	return nil
}

func (x *SearchView_Contents) GetTitleList() *TitleList {
	if x != nil {
		return x.TitleList
	}
	return nil
}

func (x *SearchView_Contents) GetRankedTitles() []*TitleRankingGroup {
	if x != nil {
		return x.RankedTitles
	}
	return nil
}

func (x *SearchView_Contents) GetAllLabels() []*Label {
	if x != nil {
		return x.AllLabels
	}
	return nil
}

func (x *SearchView_Contents) GetChapterPagesList() *ChapterPageList {
	if x != nil {
		return x.ChapterPagesList
	}
	return nil
}

var File_search_view_proto protoreflect.FileDescriptor

const file_search_view_proto_rawDesc = "" +
	"\n" +
	"\x11search_view.proto\x12\x16jp.co.comic.jump.proto\x1a\fbanner.proto\x1a\x1afeatured_titles_view.proto\x1a\vlabel.proto\x1a\x0elabel_v2.proto\x1a\ttag.proto\x1a\x10title_list.proto\x1a\x16title_list_group.proto\"\xe1\x05\n" +
	"\n" +
	"SearchView\x12L\n" +
	"\x12top_search_banners\x18\x01 \x03(\v2\x1e.jp.co.comic.jump.proto.BannerR\x10topSearchBanners\x126\n" +
	"\ball_tags\x18\x02 \x03(\v2\x1b.jp.co.comic.jump.proto.TagR\aallTags\x12P\n" +
	"\x10all_titles_group\x18\x03 \x03(\v2&.jp.co.comic.jump.proto.AllTitlesGroupR\x0eallTitlesGroup\x12O\n" +
	"\bcontents\x18\x05 \x03(\v23.jp.co.comic.jump.proto.FeaturedTitlesView.ContentsR\bcontents\x12>\n" +
	"\n" +
	"all_labels\x18\x06 \x03(\v2\x1f.jp.co.comic.jump.proto.LabelV2R\tallLabels\x1a\xe9\x02\n" +
	"\bContents\x126\n" +
	"\x06banner\x18\x01 \x01(\v2\x1e.jp.co.comic.jump.proto.BannerR\x06banner\x12@\n" +
	"\n" +
	"title_list\x18\x02 \x01(\v2!.jp.co.comic.jump.proto.TitleListR\ttitleList\x12N\n" +
	"\rranked_titles\x18\x03 \x03(\v2).jp.co.comic.jump.proto.TitleRankingGroupR\frankedTitles\x12<\n" +
	"\n" +
	"all_labels\x18\x04 \x03(\v2\x1d.jp.co.comic.jump.proto.LabelR\tallLabels\x12U\n" +
	"\x12chapter_pages_list\x18\x05 \x01(\v2'.jp.co.comic.jump.proto.ChapterPageListR\x10chapterPagesListb\x06proto3"

var (
	file_search_view_proto_rawDescOnce sync.Once
	file_search_view_proto_rawDescData []byte
)

func file_search_view_proto_rawDescGZIP() []byte {
	file_search_view_proto_rawDescOnce.Do(func() {
		file_search_view_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_search_view_proto_rawDesc), len(file_search_view_proto_rawDesc)))
	})
	return file_search_view_proto_rawDescData
}

var file_search_view_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_search_view_proto_goTypes = []any{
	(*SearchView)(nil),                  // 0: jp.co.comic.jump.proto.SearchView
	(*SearchView_Contents)(nil),         // 1: jp.co.comic.jump.proto.SearchView.Contents
	(*Banner)(nil),                      // 2: jp.co.comic.jump.proto.Banner
	(*Tag)(nil),                         // 3: jp.co.comic.jump.proto.Tag
	(*AllTitlesGroup)(nil),              // 4: jp.co.comic.jump.proto.AllTitlesGroup
	(*FeaturedTitlesView_Contents)(nil), // 5: jp.co.comic.jump.proto.FeaturedTitlesView.Contents
	(*LabelV2)(nil),                     // 6: jp.co.comic.jump.proto.LabelV2
	(*TitleList)(nil),                   // 7: jp.co.comic.jump.proto.TitleList
	(*TitleRankingGroup)(nil),           // 8: jp.co.comic.jump.proto.TitleRankingGroup
	(*Label)(nil),                       // 9: jp.co.comic.jump.proto.Label
	(*ChapterPageList)(nil),             // 10: jp.co.comic.jump.proto.ChapterPageList
}
var file_search_view_proto_depIdxs = []int32{
	2,  // 0: jp.co.comic.jump.proto.SearchView.top_search_banners:type_name -> jp.co.comic.jump.proto.Banner
	3,  // 1: jp.co.comic.jump.proto.SearchView.all_tags:type_name -> jp.co.comic.jump.proto.Tag
	4,  // 2: jp.co.comic.jump.proto.SearchView.all_titles_group:type_name -> jp.co.comic.jump.proto.AllTitlesGroup
	5,  // 3: jp.co.comic.jump.proto.SearchView.contents:type_name -> jp.co.comic.jump.proto.FeaturedTitlesView.Contents
	6,  // 4: jp.co.comic.jump.proto.SearchView.all_labels:type_name -> jp.co.comic.jump.proto.LabelV2
	2,  // 5: jp.co.comic.jump.proto.SearchView.Contents.banner:type_name -> jp.co.comic.jump.proto.Banner
	7,  // 6: jp.co.comic.jump.proto.SearchView.Contents.title_list:type_name -> jp.co.comic.jump.proto.TitleList
	8,  // 7: jp.co.comic.jump.proto.SearchView.Contents.ranked_titles:type_name -> jp.co.comic.jump.proto.TitleRankingGroup
	9,  // 8: jp.co.comic.jump.proto.SearchView.Contents.all_labels:type_name -> jp.co.comic.jump.proto.Label
	10, // 9: jp.co.comic.jump.proto.SearchView.Contents.chapter_pages_list:type_name -> jp.co.comic.jump.proto.ChapterPageList
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_search_view_proto_init() }
func file_search_view_proto_init() {
	if File_search_view_proto != nil {
		return
	}
	file_banner_proto_init()
	file_featured_titles_view_proto_init()
	file_label_proto_init()
	file_label_v2_proto_init()
	file_tag_proto_init()
	file_title_list_proto_init()
	file_title_list_group_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_search_view_proto_rawDesc), len(file_search_view_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_search_view_proto_goTypes,
		DependencyIndexes: file_search_view_proto_depIdxs,
		MessageInfos:      file_search_view_proto_msgTypes,
	}.Build()
	File_search_view_proto = out.File
	file_search_view_proto_goTypes = nil
	file_search_view_proto_depIdxs = nil
}
