// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: service_announcement.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServiceAnnouncement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Body          string                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	Date          int32                  `protobuf:"varint,3,opt,name=date,proto3" json:"date,omitempty"`
	Id            int32                  `protobuf:"varint,4,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceAnnouncement) Reset() {
	*x = ServiceAnnouncement{}
	mi := &file_service_announcement_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceAnnouncement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceAnnouncement) ProtoMessage() {}

func (x *ServiceAnnouncement) ProtoReflect() protoreflect.Message {
	mi := &file_service_announcement_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceAnnouncement.ProtoReflect.Descriptor instead.
func (*ServiceAnnouncement) Descriptor() ([]byte, []int) {
	return file_service_announcement_proto_rawDescGZIP(), []int{0}
}

func (x *ServiceAnnouncement) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ServiceAnnouncement) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *ServiceAnnouncement) GetDate() int32 {
	if x != nil {
		return x.Date
	}
	return 0
}

func (x *ServiceAnnouncement) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_service_announcement_proto protoreflect.FileDescriptor

const file_service_announcement_proto_rawDesc = "" +
	"\n" +
	"\x1aservice_announcement.proto\x12\x16jp.co.comic.jump.proto\"c\n" +
	"\x13ServiceAnnouncement\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x12\n" +
	"\x04body\x18\x02 \x01(\tR\x04body\x12\x12\n" +
	"\x04date\x18\x03 \x01(\x05R\x04date\x12\x0e\n" +
	"\x02id\x18\x04 \x01(\x05R\x02idb\x06proto3"

var (
	file_service_announcement_proto_rawDescOnce sync.Once
	file_service_announcement_proto_rawDescData []byte
)

func file_service_announcement_proto_rawDescGZIP() []byte {
	file_service_announcement_proto_rawDescOnce.Do(func() {
		file_service_announcement_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_announcement_proto_rawDesc), len(file_service_announcement_proto_rawDesc)))
	})
	return file_service_announcement_proto_rawDescData
}

var file_service_announcement_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_service_announcement_proto_goTypes = []any{
	(*ServiceAnnouncement)(nil), // 0: jp.co.comic.jump.proto.ServiceAnnouncement
}
var file_service_announcement_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_service_announcement_proto_init() }
func file_service_announcement_proto_init() {
	if File_service_announcement_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_announcement_proto_rawDesc), len(file_service_announcement_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_service_announcement_proto_goTypes,
		DependencyIndexes: file_service_announcement_proto_depIdxs,
		MessageInfos:      file_service_announcement_proto_msgTypes,
	}.Build()
	File_service_announcement_proto = out.File
	file_service_announcement_proto_goTypes = nil
	file_service_announcement_proto_depIdxs = nil
}
