// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: settings_view.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SettingsView struct {
	state                             protoimpl.MessageState `protogen:"open.v1"`
	MyIcon                            *CommentIcon           `protobuf:"bytes,1,opt,name=my_icon,json=myIcon,proto3" json:"my_icon,omitempty"`
	UserName                          string                 `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	NoticeOfNewsAndEvents             bool                   `protobuf:"varint,3,opt,name=notice_of_news_and_events,json=noticeOfNewsAndEvents,proto3" json:"notice_of_news_and_events,omitempty"`
	NoticeOfUpdatesOfSubscribedTitles bool                   `protobuf:"varint,4,opt,name=notice_of_updates_of_subscribed_titles,json=noticeOfUpdatesOfSubscribedTitles,proto3" json:"notice_of_updates_of_subscribed_titles,omitempty"`
	EnglishTitlesCount                uint32                 `protobuf:"varint,5,opt,name=english_titles_count,json=englishTitlesCount,proto3" json:"english_titles_count,omitempty"`
	SpanishTitlesCount                uint32                 `protobuf:"varint,6,opt,name=spanish_titles_count,json=spanishTitlesCount,proto3" json:"spanish_titles_count,omitempty"`
	unknownFields                     protoimpl.UnknownFields
	sizeCache                         protoimpl.SizeCache
}

func (x *SettingsView) Reset() {
	*x = SettingsView{}
	mi := &file_settings_view_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettingsView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettingsView) ProtoMessage() {}

func (x *SettingsView) ProtoReflect() protoreflect.Message {
	mi := &file_settings_view_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettingsView.ProtoReflect.Descriptor instead.
func (*SettingsView) Descriptor() ([]byte, []int) {
	return file_settings_view_proto_rawDescGZIP(), []int{0}
}

func (x *SettingsView) GetMyIcon() *CommentIcon {
	if x != nil {
		return x.MyIcon
	}
	return nil
}

func (x *SettingsView) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *SettingsView) GetNoticeOfNewsAndEvents() bool {
	if x != nil {
		return x.NoticeOfNewsAndEvents
	}
	return false
}

func (x *SettingsView) GetNoticeOfUpdatesOfSubscribedTitles() bool {
	if x != nil {
		return x.NoticeOfUpdatesOfSubscribedTitles
	}
	return false
}

func (x *SettingsView) GetEnglishTitlesCount() uint32 {
	if x != nil {
		return x.EnglishTitlesCount
	}
	return 0
}

func (x *SettingsView) GetSpanishTitlesCount() uint32 {
	if x != nil {
		return x.SpanishTitlesCount
	}
	return 0
}

var File_settings_view_proto protoreflect.FileDescriptor

const file_settings_view_proto_rawDesc = "" +
	"\n" +
	"\x13settings_view.proto\x12\x16jp.co.comic.jump.proto\x1a\x12comment_icon.proto\"\xda\x02\n" +
	"\fSettingsView\x12<\n" +
	"\amy_icon\x18\x01 \x01(\v2#.jp.co.comic.jump.proto.CommentIconR\x06myIcon\x12\x1b\n" +
	"\tuser_name\x18\x02 \x01(\tR\buserName\x128\n" +
	"\x19notice_of_news_and_events\x18\x03 \x01(\bR\x15noticeOfNewsAndEvents\x12Q\n" +
	"&notice_of_updates_of_subscribed_titles\x18\x04 \x01(\bR!noticeOfUpdatesOfSubscribedTitles\x120\n" +
	"\x14english_titles_count\x18\x05 \x01(\rR\x12englishTitlesCount\x120\n" +
	"\x14spanish_titles_count\x18\x06 \x01(\rR\x12spanishTitlesCountb\x06proto3"

var (
	file_settings_view_proto_rawDescOnce sync.Once
	file_settings_view_proto_rawDescData []byte
)

func file_settings_view_proto_rawDescGZIP() []byte {
	file_settings_view_proto_rawDescOnce.Do(func() {
		file_settings_view_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_settings_view_proto_rawDesc), len(file_settings_view_proto_rawDesc)))
	})
	return file_settings_view_proto_rawDescData
}

var file_settings_view_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_settings_view_proto_goTypes = []any{
	(*SettingsView)(nil), // 0: jp.co.comic.jump.proto.SettingsView
	(*CommentIcon)(nil),  // 1: jp.co.comic.jump.proto.CommentIcon
}
var file_settings_view_proto_depIdxs = []int32{
	1, // 0: jp.co.comic.jump.proto.SettingsView.my_icon:type_name -> jp.co.comic.jump.proto.CommentIcon
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_settings_view_proto_init() }
func file_settings_view_proto_init() {
	if File_settings_view_proto != nil {
		return
	}
	file_comment_icon_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_settings_view_proto_rawDesc), len(file_settings_view_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_settings_view_proto_goTypes,
		DependencyIndexes: file_settings_view_proto_depIdxs,
		MessageInfos:      file_settings_view_proto_msgTypes,
	}.Build()
	File_settings_view_proto = out.File
	file_settings_view_proto_goTypes = nil
	file_settings_view_proto_depIdxs = nil
}
