// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: settings_view_v2.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SettingsViewV2 struct {
	state                             protoimpl.MessageState `protogen:"open.v1"`
	MyIcon                            *CommentIcon           `protobuf:"bytes,1,opt,name=my_icon,json=myIcon,proto3" json:"my_icon,omitempty"`
	UserName                          string                 `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	NoticeOfNewsAndEvents             bool                   `protobuf:"varint,3,opt,name=notice_of_news_and_events,json=noticeOfNewsAndEvents,proto3" json:"notice_of_news_and_events,omitempty"`
	NoticeOfUpdatesOfSubscribedTitles bool                   `protobuf:"varint,4,opt,name=notice_of_updates_of_subscribed_titles,json=noticeOfUpdatesOfSubscribedTitles,proto3" json:"notice_of_updates_of_subscribed_titles,omitempty"`
	AvailableLanguages                []*AvailableLanguages  `protobuf:"bytes,5,rep,name=available_languages,json=availableLanguages,proto3" json:"available_languages,omitempty"`
	UserSubscription                  *Subscription          `protobuf:"bytes,6,opt,name=user_subscription,json=userSubscription,proto3" json:"user_subscription,omitempty"`
	Banner                            *Banner                `protobuf:"bytes,7,opt,name=banner,proto3" json:"banner,omitempty"`
	AvailableCustomCodes              []*CustomCodeDialogue  `protobuf:"bytes,8,rep,name=available_custom_codes,json=availableCustomCodes,proto3" json:"available_custom_codes,omitempty"`
	FavoriteTitles                    []*TitleRankingGroup   `protobuf:"bytes,9,rep,name=favorite_titles,json=favoriteTitles,proto3" json:"favorite_titles,omitempty"`
	unknownFields                     protoimpl.UnknownFields
	sizeCache                         protoimpl.SizeCache
}

func (x *SettingsViewV2) Reset() {
	*x = SettingsViewV2{}
	mi := &file_settings_view_v2_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettingsViewV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettingsViewV2) ProtoMessage() {}

func (x *SettingsViewV2) ProtoReflect() protoreflect.Message {
	mi := &file_settings_view_v2_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettingsViewV2.ProtoReflect.Descriptor instead.
func (*SettingsViewV2) Descriptor() ([]byte, []int) {
	return file_settings_view_v2_proto_rawDescGZIP(), []int{0}
}

func (x *SettingsViewV2) GetMyIcon() *CommentIcon {
	if x != nil {
		return x.MyIcon
	}
	return nil
}

func (x *SettingsViewV2) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *SettingsViewV2) GetNoticeOfNewsAndEvents() bool {
	if x != nil {
		return x.NoticeOfNewsAndEvents
	}
	return false
}

func (x *SettingsViewV2) GetNoticeOfUpdatesOfSubscribedTitles() bool {
	if x != nil {
		return x.NoticeOfUpdatesOfSubscribedTitles
	}
	return false
}

func (x *SettingsViewV2) GetAvailableLanguages() []*AvailableLanguages {
	if x != nil {
		return x.AvailableLanguages
	}
	return nil
}

func (x *SettingsViewV2) GetUserSubscription() *Subscription {
	if x != nil {
		return x.UserSubscription
	}
	return nil
}

func (x *SettingsViewV2) GetBanner() *Banner {
	if x != nil {
		return x.Banner
	}
	return nil
}

func (x *SettingsViewV2) GetAvailableCustomCodes() []*CustomCodeDialogue {
	if x != nil {
		return x.AvailableCustomCodes
	}
	return nil
}

func (x *SettingsViewV2) GetFavoriteTitles() []*TitleRankingGroup {
	if x != nil {
		return x.FavoriteTitles
	}
	return nil
}

type CustomCodeDialogue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlanType      string                 `protobuf:"bytes,1,opt,name=plan_type,json=planType,proto3" json:"plan_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomCodeDialogue) Reset() {
	*x = CustomCodeDialogue{}
	mi := &file_settings_view_v2_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomCodeDialogue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomCodeDialogue) ProtoMessage() {}

func (x *CustomCodeDialogue) ProtoReflect() protoreflect.Message {
	mi := &file_settings_view_v2_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomCodeDialogue.ProtoReflect.Descriptor instead.
func (*CustomCodeDialogue) Descriptor() ([]byte, []int) {
	return file_settings_view_v2_proto_rawDescGZIP(), []int{1}
}

func (x *CustomCodeDialogue) GetPlanType() string {
	if x != nil {
		return x.PlanType
	}
	return ""
}

var File_settings_view_v2_proto protoreflect.FileDescriptor

const file_settings_view_v2_proto_rawDesc = "" +
	"\n" +
	"\x16settings_view_v2.proto\x12\x16jp.co.comic.jump.proto\x1a\fbanner.proto\x1a\x12comment_icon.proto\x1a\x0flanguages.proto\x1a\x12subscription.proto\x1a\x16title_list_group.proto\"\x96\x05\n" +
	"\x0eSettingsViewV2\x12<\n" +
	"\amy_icon\x18\x01 \x01(\v2#.jp.co.comic.jump.proto.CommentIconR\x06myIcon\x12\x1b\n" +
	"\tuser_name\x18\x02 \x01(\tR\buserName\x128\n" +
	"\x19notice_of_news_and_events\x18\x03 \x01(\bR\x15noticeOfNewsAndEvents\x12Q\n" +
	"&notice_of_updates_of_subscribed_titles\x18\x04 \x01(\bR!noticeOfUpdatesOfSubscribedTitles\x12[\n" +
	"\x13available_languages\x18\x05 \x03(\v2*.jp.co.comic.jump.proto.AvailableLanguagesR\x12availableLanguages\x12Q\n" +
	"\x11user_subscription\x18\x06 \x01(\v2$.jp.co.comic.jump.proto.SubscriptionR\x10userSubscription\x126\n" +
	"\x06banner\x18\a \x01(\v2\x1e.jp.co.comic.jump.proto.BannerR\x06banner\x12`\n" +
	"\x16available_custom_codes\x18\b \x03(\v2*.jp.co.comic.jump.proto.CustomCodeDialogueR\x14availableCustomCodes\x12R\n" +
	"\x0ffavorite_titles\x18\t \x03(\v2).jp.co.comic.jump.proto.TitleRankingGroupR\x0efavoriteTitles\"1\n" +
	"\x12CustomCodeDialogue\x12\x1b\n" +
	"\tplan_type\x18\x01 \x01(\tR\bplanTypeb\x06proto3"

var (
	file_settings_view_v2_proto_rawDescOnce sync.Once
	file_settings_view_v2_proto_rawDescData []byte
)

func file_settings_view_v2_proto_rawDescGZIP() []byte {
	file_settings_view_v2_proto_rawDescOnce.Do(func() {
		file_settings_view_v2_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_settings_view_v2_proto_rawDesc), len(file_settings_view_v2_proto_rawDesc)))
	})
	return file_settings_view_v2_proto_rawDescData
}

var file_settings_view_v2_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_settings_view_v2_proto_goTypes = []any{
	(*SettingsViewV2)(nil),     // 0: jp.co.comic.jump.proto.SettingsViewV2
	(*CustomCodeDialogue)(nil), // 1: jp.co.comic.jump.proto.CustomCodeDialogue
	(*CommentIcon)(nil),        // 2: jp.co.comic.jump.proto.CommentIcon
	(*AvailableLanguages)(nil), // 3: jp.co.comic.jump.proto.AvailableLanguages
	(*Subscription)(nil),       // 4: jp.co.comic.jump.proto.Subscription
	(*Banner)(nil),             // 5: jp.co.comic.jump.proto.Banner
	(*TitleRankingGroup)(nil),  // 6: jp.co.comic.jump.proto.TitleRankingGroup
}
var file_settings_view_v2_proto_depIdxs = []int32{
	2, // 0: jp.co.comic.jump.proto.SettingsViewV2.my_icon:type_name -> jp.co.comic.jump.proto.CommentIcon
	3, // 1: jp.co.comic.jump.proto.SettingsViewV2.available_languages:type_name -> jp.co.comic.jump.proto.AvailableLanguages
	4, // 2: jp.co.comic.jump.proto.SettingsViewV2.user_subscription:type_name -> jp.co.comic.jump.proto.Subscription
	5, // 3: jp.co.comic.jump.proto.SettingsViewV2.banner:type_name -> jp.co.comic.jump.proto.Banner
	1, // 4: jp.co.comic.jump.proto.SettingsViewV2.available_custom_codes:type_name -> jp.co.comic.jump.proto.CustomCodeDialogue
	6, // 5: jp.co.comic.jump.proto.SettingsViewV2.favorite_titles:type_name -> jp.co.comic.jump.proto.TitleRankingGroup
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_settings_view_v2_proto_init() }
func file_settings_view_v2_proto_init() {
	if File_settings_view_v2_proto != nil {
		return
	}
	file_banner_proto_init()
	file_comment_icon_proto_init()
	file_languages_proto_init()
	file_subscription_proto_init()
	file_title_list_group_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_settings_view_v2_proto_rawDesc), len(file_settings_view_v2_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_settings_view_v2_proto_goTypes,
		DependencyIndexes: file_settings_view_v2_proto_depIdxs,
		MessageInfos:      file_settings_view_v2_proto_msgTypes,
	}.Build()
	File_settings_view_v2_proto = out.File
	file_settings_view_v2_proto_goTypes = nil
	file_settings_view_v2_proto_depIdxs = nil
}
