// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: subscription_offers.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SaleType int32

const (
	SaleType_DISCOUNT   SaleType = 0
	SaleType_FREE_TRIAL SaleType = 1
)

// Enum value maps for SaleType.
var (
	SaleType_name = map[int32]string{
		0: "DISCOUNT",
		1: "FREE_TRIAL",
	}
	SaleType_value = map[string]int32{
		"DISCOUNT":   0,
		"FREE_TRIAL": 1,
	}
)

func (x SaleType) Enum() *SaleType {
	p := new(SaleType)
	*p = x
	return p
}

func (x SaleType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SaleType) Descriptor() protoreflect.EnumDescriptor {
	return file_subscription_offers_proto_enumTypes[0].Descriptor()
}

func (SaleType) Type() protoreflect.EnumType {
	return &file_subscription_offers_proto_enumTypes[0]
}

func (x SaleType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SaleType.Descriptor instead.
func (SaleType) EnumDescriptor() ([]byte, []int) {
	return file_subscription_offers_proto_rawDescGZIP(), []int{0}
}

type IosSubscriptionOffer_OfferType int32

const (
	IosSubscriptionOffer_NO_OFFER     IosSubscriptionOffer_OfferType = 0
	IosSubscriptionOffer_INTRODUCTORY IosSubscriptionOffer_OfferType = 1
	IosSubscriptionOffer_PROMOTIONAL  IosSubscriptionOffer_OfferType = 2
)

// Enum value maps for IosSubscriptionOffer_OfferType.
var (
	IosSubscriptionOffer_OfferType_name = map[int32]string{
		0: "NO_OFFER",
		1: "INTRODUCTORY",
		2: "PROMOTIONAL",
	}
	IosSubscriptionOffer_OfferType_value = map[string]int32{
		"NO_OFFER":     0,
		"INTRODUCTORY": 1,
		"PROMOTIONAL":  2,
	}
)

func (x IosSubscriptionOffer_OfferType) Enum() *IosSubscriptionOffer_OfferType {
	p := new(IosSubscriptionOffer_OfferType)
	*p = x
	return p
}

func (x IosSubscriptionOffer_OfferType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IosSubscriptionOffer_OfferType) Descriptor() protoreflect.EnumDescriptor {
	return file_subscription_offers_proto_enumTypes[1].Descriptor()
}

func (IosSubscriptionOffer_OfferType) Type() protoreflect.EnumType {
	return &file_subscription_offers_proto_enumTypes[1]
}

func (x IosSubscriptionOffer_OfferType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IosSubscriptionOffer_OfferType.Descriptor instead.
func (IosSubscriptionOffer_OfferType) EnumDescriptor() ([]byte, []int) {
	return file_subscription_offers_proto_rawDescGZIP(), []int{0, 0}
}

type IosSubscriptionOffer struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	OfferType     IosSubscriptionOffer_OfferType `protobuf:"varint,1,opt,name=offer_type,json=offerType,proto3,enum=jp.co.comic.jump.proto.IosSubscriptionOffer_OfferType" json:"offer_type,omitempty"`
	Signature     string                         `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	AppleKey      string                         `protobuf:"bytes,3,opt,name=apple_key,json=appleKey,proto3" json:"apple_key,omitempty"`
	Nonce         string                         `protobuf:"bytes,4,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Timestamp     string                         `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Identifier    string                         `protobuf:"bytes,6,opt,name=identifier,proto3" json:"identifier,omitempty"`
	SaleType      SaleType                       `protobuf:"varint,7,opt,name=sale_type,json=saleType,proto3,enum=jp.co.comic.jump.proto.SaleType" json:"sale_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IosSubscriptionOffer) Reset() {
	*x = IosSubscriptionOffer{}
	mi := &file_subscription_offers_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IosSubscriptionOffer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IosSubscriptionOffer) ProtoMessage() {}

func (x *IosSubscriptionOffer) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_offers_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IosSubscriptionOffer.ProtoReflect.Descriptor instead.
func (*IosSubscriptionOffer) Descriptor() ([]byte, []int) {
	return file_subscription_offers_proto_rawDescGZIP(), []int{0}
}

func (x *IosSubscriptionOffer) GetOfferType() IosSubscriptionOffer_OfferType {
	if x != nil {
		return x.OfferType
	}
	return IosSubscriptionOffer_NO_OFFER
}

func (x *IosSubscriptionOffer) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *IosSubscriptionOffer) GetAppleKey() string {
	if x != nil {
		return x.AppleKey
	}
	return ""
}

func (x *IosSubscriptionOffer) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

func (x *IosSubscriptionOffer) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *IosSubscriptionOffer) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

func (x *IosSubscriptionOffer) GetSaleType() SaleType {
	if x != nil {
		return x.SaleType
	}
	return SaleType_DISCOUNT
}

type AndroidSubscriptionOfferTags struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tag           string                 `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	SaleType      SaleType               `protobuf:"varint,2,opt,name=sale_type,json=saleType,proto3,enum=jp.co.comic.jump.proto.SaleType" json:"sale_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AndroidSubscriptionOfferTags) Reset() {
	*x = AndroidSubscriptionOfferTags{}
	mi := &file_subscription_offers_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AndroidSubscriptionOfferTags) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AndroidSubscriptionOfferTags) ProtoMessage() {}

func (x *AndroidSubscriptionOfferTags) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_offers_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AndroidSubscriptionOfferTags.ProtoReflect.Descriptor instead.
func (*AndroidSubscriptionOfferTags) Descriptor() ([]byte, []int) {
	return file_subscription_offers_proto_rawDescGZIP(), []int{1}
}

func (x *AndroidSubscriptionOfferTags) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *AndroidSubscriptionOfferTags) GetSaleType() SaleType {
	if x != nil {
		return x.SaleType
	}
	return SaleType_DISCOUNT
}

var File_subscription_offers_proto protoreflect.FileDescriptor

const file_subscription_offers_proto_rawDesc = "" +
	"\n" +
	"\x19subscription_offers.proto\x12\x16jp.co.comic.jump.proto\"\xf9\x02\n" +
	"\x14IosSubscriptionOffer\x12U\n" +
	"\n" +
	"offer_type\x18\x01 \x01(\x0e26.jp.co.comic.jump.proto.IosSubscriptionOffer.OfferTypeR\tofferType\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\tR\tsignature\x12\x1b\n" +
	"\tapple_key\x18\x03 \x01(\tR\bappleKey\x12\x14\n" +
	"\x05nonce\x18\x04 \x01(\tR\x05nonce\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\tR\ttimestamp\x12\x1e\n" +
	"\n" +
	"identifier\x18\x06 \x01(\tR\n" +
	"identifier\x12=\n" +
	"\tsale_type\x18\a \x01(\x0e2 .jp.co.comic.jump.proto.SaleTypeR\bsaleType\"<\n" +
	"\tOfferType\x12\f\n" +
	"\bNO_OFFER\x10\x00\x12\x10\n" +
	"\fINTRODUCTORY\x10\x01\x12\x0f\n" +
	"\vPROMOTIONAL\x10\x02\"o\n" +
	"\x1cAndroidSubscriptionOfferTags\x12\x10\n" +
	"\x03tag\x18\x01 \x01(\tR\x03tag\x12=\n" +
	"\tsale_type\x18\x02 \x01(\x0e2 .jp.co.comic.jump.proto.SaleTypeR\bsaleType*(\n" +
	"\bSaleType\x12\f\n" +
	"\bDISCOUNT\x10\x00\x12\x0e\n" +
	"\n" +
	"FREE_TRIAL\x10\x01b\x06proto3"

var (
	file_subscription_offers_proto_rawDescOnce sync.Once
	file_subscription_offers_proto_rawDescData []byte
)

func file_subscription_offers_proto_rawDescGZIP() []byte {
	file_subscription_offers_proto_rawDescOnce.Do(func() {
		file_subscription_offers_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_subscription_offers_proto_rawDesc), len(file_subscription_offers_proto_rawDesc)))
	})
	return file_subscription_offers_proto_rawDescData
}

var file_subscription_offers_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_subscription_offers_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_subscription_offers_proto_goTypes = []any{
	(SaleType)(0),                        // 0: jp.co.comic.jump.proto.SaleType
	(IosSubscriptionOffer_OfferType)(0),  // 1: jp.co.comic.jump.proto.IosSubscriptionOffer.OfferType
	(*IosSubscriptionOffer)(nil),         // 2: jp.co.comic.jump.proto.IosSubscriptionOffer
	(*AndroidSubscriptionOfferTags)(nil), // 3: jp.co.comic.jump.proto.AndroidSubscriptionOfferTags
}
var file_subscription_offers_proto_depIdxs = []int32{
	1, // 0: jp.co.comic.jump.proto.IosSubscriptionOffer.offer_type:type_name -> jp.co.comic.jump.proto.IosSubscriptionOffer.OfferType
	0, // 1: jp.co.comic.jump.proto.IosSubscriptionOffer.sale_type:type_name -> jp.co.comic.jump.proto.SaleType
	0, // 2: jp.co.comic.jump.proto.AndroidSubscriptionOfferTags.sale_type:type_name -> jp.co.comic.jump.proto.SaleType
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_subscription_offers_proto_init() }
func file_subscription_offers_proto_init() {
	if File_subscription_offers_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_subscription_offers_proto_rawDesc), len(file_subscription_offers_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_subscription_offers_proto_goTypes,
		DependencyIndexes: file_subscription_offers_proto_depIdxs,
		EnumInfos:         file_subscription_offers_proto_enumTypes,
		MessageInfos:      file_subscription_offers_proto_msgTypes,
	}.Build()
	File_subscription_offers_proto = out.File
	file_subscription_offers_proto_goTypes = nil
	file_subscription_offers_proto_depIdxs = nil
}
