// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: subscribed_titles_view.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubscribedTitlesView struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Titles         []*Title               `protobuf:"bytes,1,rep,name=titles,proto3" json:"titles,omitempty"`
	HistoryBanners []*Banner              `protobuf:"bytes,2,rep,name=history_banners,json=historyBanners,proto3" json:"history_banners,omitempty"`
	ViewHistory    []*Title               `protobuf:"bytes,3,rep,name=view_history,json=viewHistory,proto3" json:"view_history,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SubscribedTitlesView) Reset() {
	*x = SubscribedTitlesView{}
	mi := &file_subscribed_titles_view_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribedTitlesView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribedTitlesView) ProtoMessage() {}

func (x *SubscribedTitlesView) ProtoReflect() protoreflect.Message {
	mi := &file_subscribed_titles_view_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribedTitlesView.ProtoReflect.Descriptor instead.
func (*SubscribedTitlesView) Descriptor() ([]byte, []int) {
	return file_subscribed_titles_view_proto_rawDescGZIP(), []int{0}
}

func (x *SubscribedTitlesView) GetTitles() []*Title {
	if x != nil {
		return x.Titles
	}
	return nil
}

func (x *SubscribedTitlesView) GetHistoryBanners() []*Banner {
	if x != nil {
		return x.HistoryBanners
	}
	return nil
}

func (x *SubscribedTitlesView) GetViewHistory() []*Title {
	if x != nil {
		return x.ViewHistory
	}
	return nil
}

var File_subscribed_titles_view_proto protoreflect.FileDescriptor

const file_subscribed_titles_view_proto_rawDesc = "" +
	"\n" +
	"\x1csubscribed_titles_view.proto\x12\x16jp.co.comic.jump.proto\x1a\fbanner.proto\x1a\vtitle.proto\"\xd8\x01\n" +
	"\x14SubscribedTitlesView\x125\n" +
	"\x06titles\x18\x01 \x03(\v2\x1d.jp.co.comic.jump.proto.TitleR\x06titles\x12G\n" +
	"\x0fhistory_banners\x18\x02 \x03(\v2\x1e.jp.co.comic.jump.proto.BannerR\x0ehistoryBanners\x12@\n" +
	"\fview_history\x18\x03 \x03(\v2\x1d.jp.co.comic.jump.proto.TitleR\vviewHistoryb\x06proto3"

var (
	file_subscribed_titles_view_proto_rawDescOnce sync.Once
	file_subscribed_titles_view_proto_rawDescData []byte
)

func file_subscribed_titles_view_proto_rawDescGZIP() []byte {
	file_subscribed_titles_view_proto_rawDescOnce.Do(func() {
		file_subscribed_titles_view_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_subscribed_titles_view_proto_rawDesc), len(file_subscribed_titles_view_proto_rawDesc)))
	})
	return file_subscribed_titles_view_proto_rawDescData
}

var file_subscribed_titles_view_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_subscribed_titles_view_proto_goTypes = []any{
	(*SubscribedTitlesView)(nil), // 0: jp.co.comic.jump.proto.SubscribedTitlesView
	(*Title)(nil),                // 1: jp.co.comic.jump.proto.Title
	(*Banner)(nil),               // 2: jp.co.comic.jump.proto.Banner
}
var file_subscribed_titles_view_proto_depIdxs = []int32{
	1, // 0: jp.co.comic.jump.proto.SubscribedTitlesView.titles:type_name -> jp.co.comic.jump.proto.Title
	2, // 1: jp.co.comic.jump.proto.SubscribedTitlesView.history_banners:type_name -> jp.co.comic.jump.proto.Banner
	1, // 2: jp.co.comic.jump.proto.SubscribedTitlesView.view_history:type_name -> jp.co.comic.jump.proto.Title
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_subscribed_titles_view_proto_init() }
func file_subscribed_titles_view_proto_init() {
	if File_subscribed_titles_view_proto != nil {
		return
	}
	file_banner_proto_init()
	file_title_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_subscribed_titles_view_proto_rawDesc), len(file_subscribed_titles_view_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_subscribed_titles_view_proto_goTypes,
		DependencyIndexes: file_subscribed_titles_view_proto_depIdxs,
		MessageInfos:      file_subscribed_titles_view_proto_msgTypes,
	}.Build()
	File_subscribed_titles_view_proto = out.File
	file_subscribed_titles_view_proto_goTypes = nil
	file_subscribed_titles_view_proto_depIdxs = nil
}
