// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: subscription.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Subscription struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	PlanType           string                 `protobuf:"bytes,1,opt,name=plan_type,json=planType,proto3" json:"plan_type,omitempty"`
	NextPaymentDate    uint32                 `protobuf:"varint,2,opt,name=next_payment_date,json=nextPaymentDate,proto3" json:"next_payment_date,omitempty"`
	IsFreeTrial        bool                   `protobuf:"varint,3,opt,name=is_free_trial,json=isFreeTrial,proto3" json:"is_free_trial,omitempty"`
	IsPendingDowngrade bool                   `protobuf:"varint,4,opt,name=is_pending_downgrade,json=isPendingDowngrade,proto3" json:"is_pending_downgrade,omitempty"`
	IsFirstTimeUser    bool                   `protobuf:"varint,5,opt,name=is_first_time_user,json=isFirstTimeUser,proto3" json:"is_first_time_user,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Subscription) Reset() {
	*x = Subscription{}
	mi := &file_subscription_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subscription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subscription) ProtoMessage() {}

func (x *Subscription) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subscription.ProtoReflect.Descriptor instead.
func (*Subscription) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{0}
}

func (x *Subscription) GetPlanType() string {
	if x != nil {
		return x.PlanType
	}
	return ""
}

func (x *Subscription) GetNextPaymentDate() uint32 {
	if x != nil {
		return x.NextPaymentDate
	}
	return 0
}

func (x *Subscription) GetIsFreeTrial() bool {
	if x != nil {
		return x.IsFreeTrial
	}
	return false
}

func (x *Subscription) GetIsPendingDowngrade() bool {
	if x != nil {
		return x.IsPendingDowngrade
	}
	return false
}

func (x *Subscription) GetIsFirstTimeUser() bool {
	if x != nil {
		return x.IsFirstTimeUser
	}
	return false
}

type PlanType struct {
	state             protoimpl.MessageState          `protogen:"open.v1"`
	Plan              string                          `protobuf:"bytes,1,opt,name=plan,proto3" json:"plan,omitempty"`
	Description       string                          `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	ProductId         string                          `protobuf:"bytes,3,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	SubscriptionOffer *IosSubscriptionOffer           `protobuf:"bytes,4,opt,name=subscription_offer,json=subscriptionOffer,proto3" json:"subscription_offer,omitempty"`
	AndroidOfferTags  []*AndroidSubscriptionOfferTags `protobuf:"bytes,5,rep,name=android_offer_tags,json=androidOfferTags,proto3" json:"android_offer_tags,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PlanType) Reset() {
	*x = PlanType{}
	mi := &file_subscription_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanType) ProtoMessage() {}

func (x *PlanType) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanType.ProtoReflect.Descriptor instead.
func (*PlanType) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{1}
}

func (x *PlanType) GetPlan() string {
	if x != nil {
		return x.Plan
	}
	return ""
}

func (x *PlanType) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PlanType) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *PlanType) GetSubscriptionOffer() *IosSubscriptionOffer {
	if x != nil {
		return x.SubscriptionOffer
	}
	return nil
}

func (x *PlanType) GetAndroidOfferTags() []*AndroidSubscriptionOfferTags {
	if x != nil {
		return x.AndroidOfferTags
	}
	return nil
}

type SubscriptionPlanBoxDescription struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscriptionPlanBoxDescription) Reset() {
	*x = SubscriptionPlanBoxDescription{}
	mi := &file_subscription_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriptionPlanBoxDescription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionPlanBoxDescription) ProtoMessage() {}

func (x *SubscriptionPlanBoxDescription) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionPlanBoxDescription.ProtoReflect.Descriptor instead.
func (*SubscriptionPlanBoxDescription) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{2}
}

func (x *SubscriptionPlanBoxDescription) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SubscriptionPlanBoxDescription) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type SubscriptionNote struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscriptionNote) Reset() {
	*x = SubscriptionNote{}
	mi := &file_subscription_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriptionNote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionNote) ProtoMessage() {}

func (x *SubscriptionNote) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionNote.ProtoReflect.Descriptor instead.
func (*SubscriptionNote) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{3}
}

func (x *SubscriptionNote) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SubscriptionNote) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

var File_subscription_proto protoreflect.FileDescriptor

const file_subscription_proto_rawDesc = "" +
	"\n" +
	"\x12subscription.proto\x12\x16jp.co.comic.jump.proto\x1a\x19subscription_offers.proto\"\xda\x01\n" +
	"\fSubscription\x12\x1b\n" +
	"\tplan_type\x18\x01 \x01(\tR\bplanType\x12*\n" +
	"\x11next_payment_date\x18\x02 \x01(\rR\x0fnextPaymentDate\x12\"\n" +
	"\ris_free_trial\x18\x03 \x01(\bR\visFreeTrial\x120\n" +
	"\x14is_pending_downgrade\x18\x04 \x01(\bR\x12isPendingDowngrade\x12+\n" +
	"\x12is_first_time_user\x18\x05 \x01(\bR\x0fisFirstTimeUser\"\xa0\x02\n" +
	"\bPlanType\x12\x12\n" +
	"\x04plan\x18\x01 \x01(\tR\x04plan\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"product_id\x18\x03 \x01(\tR\tproductId\x12[\n" +
	"\x12subscription_offer\x18\x04 \x01(\v2,.jp.co.comic.jump.proto.IosSubscriptionOfferR\x11subscriptionOffer\x12b\n" +
	"\x12android_offer_tags\x18\x05 \x03(\v24.jp.co.comic.jump.proto.AndroidSubscriptionOfferTagsR\x10androidOfferTags\"J\n" +
	"\x1eSubscriptionPlanBoxDescription\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"<\n" +
	"\x10SubscriptionNote\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04textb\x06proto3"

var (
	file_subscription_proto_rawDescOnce sync.Once
	file_subscription_proto_rawDescData []byte
)

func file_subscription_proto_rawDescGZIP() []byte {
	file_subscription_proto_rawDescOnce.Do(func() {
		file_subscription_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_subscription_proto_rawDesc), len(file_subscription_proto_rawDesc)))
	})
	return file_subscription_proto_rawDescData
}

var file_subscription_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_subscription_proto_goTypes = []any{
	(*Subscription)(nil),                   // 0: jp.co.comic.jump.proto.Subscription
	(*PlanType)(nil),                       // 1: jp.co.comic.jump.proto.PlanType
	(*SubscriptionPlanBoxDescription)(nil), // 2: jp.co.comic.jump.proto.SubscriptionPlanBoxDescription
	(*SubscriptionNote)(nil),               // 3: jp.co.comic.jump.proto.SubscriptionNote
	(*IosSubscriptionOffer)(nil),           // 4: jp.co.comic.jump.proto.IosSubscriptionOffer
	(*AndroidSubscriptionOfferTags)(nil),   // 5: jp.co.comic.jump.proto.AndroidSubscriptionOfferTags
}
var file_subscription_proto_depIdxs = []int32{
	4, // 0: jp.co.comic.jump.proto.PlanType.subscription_offer:type_name -> jp.co.comic.jump.proto.IosSubscriptionOffer
	5, // 1: jp.co.comic.jump.proto.PlanType.android_offer_tags:type_name -> jp.co.comic.jump.proto.AndroidSubscriptionOfferTags
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_subscription_proto_init() }
func file_subscription_proto_init() {
	if File_subscription_proto != nil {
		return
	}
	file_subscription_offers_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_subscription_proto_rawDesc), len(file_subscription_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_subscription_proto_goTypes,
		DependencyIndexes: file_subscription_proto_depIdxs,
		MessageInfos:      file_subscription_proto_msgTypes,
	}.Build()
	File_subscription_proto = out.File
	file_subscription_proto_goTypes = nil
	file_subscription_proto_depIdxs = nil
}
