// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: subscription_view.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubscriptionView struct {
	state              protoimpl.MessageState          `protogen:"open.v1"`
	UserSubscription   *Subscription                   `protobuf:"bytes,1,opt,name=user_subscription,json=userSubscription,proto3" json:"user_subscription,omitempty"`
	PlanTypes          []*PlanType                     `protobuf:"bytes,2,rep,name=plan_types,json=planTypes,proto3" json:"plan_types,omitempty"`
	SubscriptionTitles []*TitleSubscriptionGroup       `protobuf:"bytes,3,rep,name=subscription_titles,json=subscriptionTitles,proto3" json:"subscription_titles,omitempty"`
	UserHasUsedTrial   bool                            `protobuf:"varint,4,opt,name=user_has_used_trial,json=userHasUsedTrial,proto3" json:"user_has_used_trial,omitempty"`
	Banner             *Banner                         `protobuf:"bytes,5,opt,name=banner,proto3" json:"banner,omitempty"`
	PlanBoxDescription *SubscriptionPlanBoxDescription `protobuf:"bytes,6,opt,name=plan_box_description,json=planBoxDescription,proto3" json:"plan_box_description,omitempty"`
	Note               *SubscriptionNote               `protobuf:"bytes,7,opt,name=note,proto3" json:"note,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SubscriptionView) Reset() {
	*x = SubscriptionView{}
	mi := &file_subscription_view_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriptionView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionView) ProtoMessage() {}

func (x *SubscriptionView) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_view_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionView.ProtoReflect.Descriptor instead.
func (*SubscriptionView) Descriptor() ([]byte, []int) {
	return file_subscription_view_proto_rawDescGZIP(), []int{0}
}

func (x *SubscriptionView) GetUserSubscription() *Subscription {
	if x != nil {
		return x.UserSubscription
	}
	return nil
}

func (x *SubscriptionView) GetPlanTypes() []*PlanType {
	if x != nil {
		return x.PlanTypes
	}
	return nil
}

func (x *SubscriptionView) GetSubscriptionTitles() []*TitleSubscriptionGroup {
	if x != nil {
		return x.SubscriptionTitles
	}
	return nil
}

func (x *SubscriptionView) GetUserHasUsedTrial() bool {
	if x != nil {
		return x.UserHasUsedTrial
	}
	return false
}

func (x *SubscriptionView) GetBanner() *Banner {
	if x != nil {
		return x.Banner
	}
	return nil
}

func (x *SubscriptionView) GetPlanBoxDescription() *SubscriptionPlanBoxDescription {
	if x != nil {
		return x.PlanBoxDescription
	}
	return nil
}

func (x *SubscriptionView) GetNote() *SubscriptionNote {
	if x != nil {
		return x.Note
	}
	return nil
}

var File_subscription_view_proto protoreflect.FileDescriptor

const file_subscription_view_proto_rawDesc = "" +
	"\n" +
	"\x17subscription_view.proto\x12\x16jp.co.comic.jump.proto\x1a\fbanner.proto\x1a\x12subscription.proto\x1a\x16title_list_group.proto\"\x96\x04\n" +
	"\x10SubscriptionView\x12Q\n" +
	"\x11user_subscription\x18\x01 \x01(\v2$.jp.co.comic.jump.proto.SubscriptionR\x10userSubscription\x12?\n" +
	"\n" +
	"plan_types\x18\x02 \x03(\v2 .jp.co.comic.jump.proto.PlanTypeR\tplanTypes\x12_\n" +
	"\x13subscription_titles\x18\x03 \x03(\v2..jp.co.comic.jump.proto.TitleSubscriptionGroupR\x12subscriptionTitles\x12-\n" +
	"\x13user_has_used_trial\x18\x04 \x01(\bR\x10userHasUsedTrial\x126\n" +
	"\x06banner\x18\x05 \x01(\v2\x1e.jp.co.comic.jump.proto.BannerR\x06banner\x12h\n" +
	"\x14plan_box_description\x18\x06 \x01(\v26.jp.co.comic.jump.proto.SubscriptionPlanBoxDescriptionR\x12planBoxDescription\x12<\n" +
	"\x04note\x18\a \x01(\v2(.jp.co.comic.jump.proto.SubscriptionNoteR\x04noteb\x06proto3"

var (
	file_subscription_view_proto_rawDescOnce sync.Once
	file_subscription_view_proto_rawDescData []byte
)

func file_subscription_view_proto_rawDescGZIP() []byte {
	file_subscription_view_proto_rawDescOnce.Do(func() {
		file_subscription_view_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_subscription_view_proto_rawDesc), len(file_subscription_view_proto_rawDesc)))
	})
	return file_subscription_view_proto_rawDescData
}

var file_subscription_view_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_subscription_view_proto_goTypes = []any{
	(*SubscriptionView)(nil),               // 0: jp.co.comic.jump.proto.SubscriptionView
	(*Subscription)(nil),                   // 1: jp.co.comic.jump.proto.Subscription
	(*PlanType)(nil),                       // 2: jp.co.comic.jump.proto.PlanType
	(*TitleSubscriptionGroup)(nil),         // 3: jp.co.comic.jump.proto.TitleSubscriptionGroup
	(*Banner)(nil),                         // 4: jp.co.comic.jump.proto.Banner
	(*SubscriptionPlanBoxDescription)(nil), // 5: jp.co.comic.jump.proto.SubscriptionPlanBoxDescription
	(*SubscriptionNote)(nil),               // 6: jp.co.comic.jump.proto.SubscriptionNote
}
var file_subscription_view_proto_depIdxs = []int32{
	1, // 0: jp.co.comic.jump.proto.SubscriptionView.user_subscription:type_name -> jp.co.comic.jump.proto.Subscription
	2, // 1: jp.co.comic.jump.proto.SubscriptionView.plan_types:type_name -> jp.co.comic.jump.proto.PlanType
	3, // 2: jp.co.comic.jump.proto.SubscriptionView.subscription_titles:type_name -> jp.co.comic.jump.proto.TitleSubscriptionGroup
	4, // 3: jp.co.comic.jump.proto.SubscriptionView.banner:type_name -> jp.co.comic.jump.proto.Banner
	5, // 4: jp.co.comic.jump.proto.SubscriptionView.plan_box_description:type_name -> jp.co.comic.jump.proto.SubscriptionPlanBoxDescription
	6, // 5: jp.co.comic.jump.proto.SubscriptionView.note:type_name -> jp.co.comic.jump.proto.SubscriptionNote
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_subscription_view_proto_init() }
func file_subscription_view_proto_init() {
	if File_subscription_view_proto != nil {
		return
	}
	file_banner_proto_init()
	file_subscription_proto_init()
	file_title_list_group_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_subscription_view_proto_rawDesc), len(file_subscription_view_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_subscription_view_proto_goTypes,
		DependencyIndexes: file_subscription_view_proto_depIdxs,
		MessageInfos:      file_subscription_view_proto_msgTypes,
	}.Build()
	File_subscription_view_proto = out.File
	file_subscription_view_proto_goTypes = nil
	file_subscription_view_proto_depIdxs = nil
}
