// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: title_detail_view.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TitleDetailView_ReleaseSchedule int32

const (
	TitleDetailView_DISABLED   TitleDetailView_ReleaseSchedule = 0
	TitleDetailView_EVERYDAY   TitleDetailView_ReleaseSchedule = 1
	TitleDetailView_WEEKLY     TitleDetailView_ReleaseSchedule = 2
	TitleDetailView_BIWEEKLY   TitleDetailView_ReleaseSchedule = 3
	TitleDetailView_MONTHLY    TitleDetailView_ReleaseSchedule = 4
	TitleDetailView_BIMONTHLY  TitleDetailView_ReleaseSchedule = 5
	TitleDetailView_TRIMONTHLY TitleDetailView_ReleaseSchedule = 6
	TitleDetailView_OTHER      TitleDetailView_ReleaseSchedule = 7
	TitleDetailView_COMPLETED  TitleDetailView_ReleaseSchedule = 8
	TitleDetailView_ONE_SHOT   TitleDetailView_ReleaseSchedule = 9
	TitleDetailView_HIATUS     TitleDetailView_ReleaseSchedule = 10
)

// Enum value maps for TitleDetailView_ReleaseSchedule.
var (
	TitleDetailView_ReleaseSchedule_name = map[int32]string{
		0:  "DISABLED",
		1:  "EVERYDAY",
		2:  "WEEKLY",
		3:  "BIWEEKLY",
		4:  "MONTHLY",
		5:  "BIMONTHLY",
		6:  "TRIMONTHLY",
		7:  "OTHER",
		8:  "COMPLETED",
		9:  "ONE_SHOT",
		10: "HIATUS",
	}
	TitleDetailView_ReleaseSchedule_value = map[string]int32{
		"DISABLED":   0,
		"EVERYDAY":   1,
		"WEEKLY":     2,
		"BIWEEKLY":   3,
		"MONTHLY":    4,
		"BIMONTHLY":  5,
		"TRIMONTHLY": 6,
		"OTHER":      7,
		"COMPLETED":  8,
		"ONE_SHOT":   9,
		"HIATUS":     10,
	}
)

func (x TitleDetailView_ReleaseSchedule) Enum() *TitleDetailView_ReleaseSchedule {
	p := new(TitleDetailView_ReleaseSchedule)
	*p = x
	return p
}

func (x TitleDetailView_ReleaseSchedule) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TitleDetailView_ReleaseSchedule) Descriptor() protoreflect.EnumDescriptor {
	return file_title_detail_view_proto_enumTypes[0].Descriptor()
}

func (TitleDetailView_ReleaseSchedule) Type() protoreflect.EnumType {
	return &file_title_detail_view_proto_enumTypes[0]
}

func (x TitleDetailView_ReleaseSchedule) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TitleDetailView_ReleaseSchedule.Descriptor instead.
func (TitleDetailView_ReleaseSchedule) EnumDescriptor() ([]byte, []int) {
	return file_title_detail_view_proto_rawDescGZIP(), []int{0, 0}
}

type TitleDetailView_UpdateTiming int32

const (
	TitleDetailView_NOT_REGULARLY TitleDetailView_UpdateTiming = 0
	TitleDetailView_MONDAY        TitleDetailView_UpdateTiming = 1
	TitleDetailView_TUESDAY       TitleDetailView_UpdateTiming = 2
	TitleDetailView_WEDNESDAY     TitleDetailView_UpdateTiming = 3
	TitleDetailView_THURSDAY      TitleDetailView_UpdateTiming = 4
	TitleDetailView_FRIDAY        TitleDetailView_UpdateTiming = 5
	TitleDetailView_SATURDAY      TitleDetailView_UpdateTiming = 6
	TitleDetailView_SUNDAY        TitleDetailView_UpdateTiming = 7
	TitleDetailView_DAY           TitleDetailView_UpdateTiming = 8
)

// Enum value maps for TitleDetailView_UpdateTiming.
var (
	TitleDetailView_UpdateTiming_name = map[int32]string{
		0: "NOT_REGULARLY",
		1: "MONDAY",
		2: "TUESDAY",
		3: "WEDNESDAY",
		4: "THURSDAY",
		5: "FRIDAY",
		6: "SATURDAY",
		7: "SUNDAY",
		8: "DAY",
	}
	TitleDetailView_UpdateTiming_value = map[string]int32{
		"NOT_REGULARLY": 0,
		"MONDAY":        1,
		"TUESDAY":       2,
		"WEDNESDAY":     3,
		"THURSDAY":      4,
		"FRIDAY":        5,
		"SATURDAY":      6,
		"SUNDAY":        7,
		"DAY":           8,
	}
)

func (x TitleDetailView_UpdateTiming) Enum() *TitleDetailView_UpdateTiming {
	p := new(TitleDetailView_UpdateTiming)
	*p = x
	return p
}

func (x TitleDetailView_UpdateTiming) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TitleDetailView_UpdateTiming) Descriptor() protoreflect.EnumDescriptor {
	return file_title_detail_view_proto_enumTypes[1].Descriptor()
}

func (TitleDetailView_UpdateTiming) Type() protoreflect.EnumType {
	return &file_title_detail_view_proto_enumTypes[1]
}

func (x TitleDetailView_UpdateTiming) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TitleDetailView_UpdateTiming.Descriptor instead.
func (TitleDetailView_UpdateTiming) EnumDescriptor() ([]byte, []int) {
	return file_title_detail_view_proto_rawDescGZIP(), []int{0, 1}
}

type TitleDetailView_Rating int32

const (
	TitleDetailView_ALLAGE   TitleDetailView_Rating = 0
	TitleDetailView_TEEN     TitleDetailView_Rating = 1
	TitleDetailView_TEENPLUS TitleDetailView_Rating = 2
	TitleDetailView_MATURE   TitleDetailView_Rating = 3
)

// Enum value maps for TitleDetailView_Rating.
var (
	TitleDetailView_Rating_name = map[int32]string{
		0: "ALLAGE",
		1: "TEEN",
		2: "TEENPLUS",
		3: "MATURE",
	}
	TitleDetailView_Rating_value = map[string]int32{
		"ALLAGE":   0,
		"TEEN":     1,
		"TEENPLUS": 2,
		"MATURE":   3,
	}
)

func (x TitleDetailView_Rating) Enum() *TitleDetailView_Rating {
	p := new(TitleDetailView_Rating)
	*p = x
	return p
}

func (x TitleDetailView_Rating) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TitleDetailView_Rating) Descriptor() protoreflect.EnumDescriptor {
	return file_title_detail_view_proto_enumTypes[2].Descriptor()
}

func (TitleDetailView_Rating) Type() protoreflect.EnumType {
	return &file_title_detail_view_proto_enumTypes[2]
}

func (x TitleDetailView_Rating) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TitleDetailView_Rating.Descriptor instead.
func (TitleDetailView_Rating) EnumDescriptor() ([]byte, []int) {
	return file_title_detail_view_proto_rawDescGZIP(), []int{0, 2}
}

type TitleDetailView struct {
	state                    protoimpl.MessageState                  `protogen:"open.v1"`
	Title                    *Title                                  `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	TitleImageUrl            string                                  `protobuf:"bytes,2,opt,name=title_image_url,json=titleImageUrl,proto3" json:"title_image_url,omitempty"`
	Overview                 string                                  `protobuf:"bytes,3,opt,name=overview,proto3" json:"overview,omitempty"`
	BackgroundImageUrl       string                                  `protobuf:"bytes,4,opt,name=background_image_url,json=backgroundImageUrl,proto3" json:"background_image_url,omitempty"`
	NextTimeStamp            uint32                                  `protobuf:"varint,5,opt,name=next_time_stamp,json=nextTimeStamp,proto3" json:"next_time_stamp,omitempty"`
	UpdateTiming             TitleDetailView_UpdateTiming            `protobuf:"varint,6,opt,name=update_timing,json=updateTiming,proto3,enum=jp.co.comic.jump.proto.TitleDetailView_UpdateTiming" json:"update_timing,omitempty"`
	ViewingPeriodDescription string                                  `protobuf:"bytes,7,opt,name=viewing_period_description,json=viewingPeriodDescription,proto3" json:"viewing_period_description,omitempty"`
	NonAppearanceInfo        string                                  `protobuf:"bytes,8,opt,name=non_appearance_info,json=nonAppearanceInfo,proto3" json:"non_appearance_info,omitempty"`
	FirstChapterList         []*Chapter                              `protobuf:"bytes,9,rep,name=first_chapter_list,json=firstChapterList,proto3" json:"first_chapter_list,omitempty"`
	LastChapterList          []*Chapter                              `protobuf:"bytes,10,rep,name=last_chapter_list,json=lastChapterList,proto3" json:"last_chapter_list,omitempty"`
	Banners                  []*Banner                               `protobuf:"bytes,11,rep,name=banners,proto3" json:"banners,omitempty"`
	RecommendedTitleList     []*Title                                `protobuf:"bytes,12,rep,name=recommended_title_list,json=recommendedTitleList,proto3" json:"recommended_title_list,omitempty"`
	Sns                      *Sns                                    `protobuf:"bytes,13,opt,name=sns,proto3" json:"sns,omitempty"`
	IsSimulReleased          bool                                    `protobuf:"varint,14,opt,name=is_simul_released,json=isSimulReleased,proto3" json:"is_simul_released,omitempty"`
	IsSubscribed             bool                                    `protobuf:"varint,15,opt,name=is_subscribed,json=isSubscribed,proto3" json:"is_subscribed,omitempty"`
	Rating                   TitleDetailView_Rating                  `protobuf:"varint,16,opt,name=rating,proto3,enum=jp.co.comic.jump.proto.TitleDetailView_Rating" json:"rating,omitempty"`
	ChaptersDescending       bool                                    `protobuf:"varint,17,opt,name=chaptersDescending,proto3" json:"chaptersDescending,omitempty"`
	NumberOfViews            uint32                                  `protobuf:"varint,18,opt,name=numberOfViews,proto3" json:"numberOfViews,omitempty"`
	PublisherItems           []*TitleDetailView_PublisherItem        `protobuf:"bytes,19,rep,name=publisher_items,json=publisherItems,proto3" json:"publisher_items,omitempty"`
	TitleBanners             []*Banner                               `protobuf:"bytes,20,rep,name=title_banners,json=titleBanners,proto3" json:"title_banners,omitempty"`
	UserTickets              *UserTickets                            `protobuf:"bytes,21,opt,name=user_tickets,json=userTickets,proto3" json:"user_tickets,omitempty"`
	TicketChapterList        []*Chapter                              `protobuf:"bytes,22,rep,name=ticket_chapter_list,json=ticketChapterList,proto3" json:"ticket_chapter_list,omitempty"`
	TicketTitleList          []*Title                                `protobuf:"bytes,23,rep,name=ticket_title_list,json=ticketTitleList,proto3" json:"ticket_title_list,omitempty"`
	HasChaptersBetween       bool                                    `protobuf:"varint,24,opt,name=has_chapters_between,json=hasChaptersBetween,proto3" json:"has_chapters_between,omitempty"`
	PublisherBanner          *Banner                                 `protobuf:"bytes,25,opt,name=publisher_banner,json=publisherBanner,proto3" json:"publisher_banner,omitempty"`
	Advertisement            *AdNetworkList                          `protobuf:"bytes,26,opt,name=advertisement,proto3" json:"advertisement,omitempty"`
	TitleLanguages           []*TitleDetailView_TitleLanguages       `protobuf:"bytes,27,rep,name=title_languages,json=titleLanguages,proto3" json:"title_languages,omitempty"`
	ChapterListGroup         []*TitleDetailView_ChapterGroup         `protobuf:"bytes,28,rep,name=chapter_list_group,json=chapterListGroup,proto3" json:"chapter_list_group,omitempty"`
	FreeViewDialogue         *FreeViewDialogue                       `protobuf:"bytes,29,opt,name=free_view_dialogue,json=freeViewDialogue,proto3" json:"free_view_dialogue,omitempty"`
	RegionCode               string                                  `protobuf:"bytes,30,opt,name=region_code,json=regionCode,proto3" json:"region_code,omitempty"`
	Tags                     []*Tag                                  `protobuf:"bytes,31,rep,name=tags,proto3" json:"tags,omitempty"`
	TitleLabels              *TitleDetailView_TitleLabels            `protobuf:"bytes,32,opt,name=title_labels,json=titleLabels,proto3" json:"title_labels,omitempty"`
	UserSubscription         *Subscription                           `protobuf:"bytes,33,opt,name=user_subscription,json=userSubscription,proto3" json:"user_subscription,omitempty"`
	Label                    *Label                                  `protobuf:"bytes,34,opt,name=label,proto3" json:"label,omitempty"`
	IsFirstTimeFree          bool                                    `protobuf:"varint,35,opt,name=is_first_time_free,json=isFirstTimeFree,proto3" json:"is_first_time_free,omitempty"`
	MetaInfo                 *MetaInfo                               `protobuf:"bytes,36,opt,name=meta_info,json=metaInfo,proto3" json:"meta_info,omitempty"`
	RatingPopup              *Popup                                  `protobuf:"bytes,37,opt,name=rating_popup,json=ratingPopup,proto3" json:"rating_popup,omitempty"`
	ChapterListV2            []*Chapter                              `protobuf:"bytes,38,rep,name=chapter_list_v2,json=chapterListV2,proto3" json:"chapter_list_v2,omitempty"`
	LabelV2                  *LabelV2                                `protobuf:"bytes,39,opt,name=label_v2,json=labelV2,proto3" json:"label_v2,omitempty"`
	MiddleChapterNeighbors   *TitleDetailView_MiddleChapterNeighbors `protobuf:"bytes,40,opt,name=middle_chapter_neighbors,json=middleChapterNeighbors,proto3" json:"middle_chapter_neighbors,omitempty"`
	IsMerchAvailable         bool                                    `protobuf:"varint,41,opt,name=is_merch_available,json=isMerchAvailable,proto3" json:"is_merch_available,omitempty"`
	PlanTypes                []*PlanType                             `protobuf:"bytes,42,rep,name=plan_types,json=planTypes,proto3" json:"plan_types,omitempty"`
	UserHasUsedTrial         bool                                    `protobuf:"varint,43,opt,name=user_has_used_trial,json=userHasUsedTrial,proto3" json:"user_has_used_trial,omitempty"`
	PlanBoxDescription       *SubscriptionPlanBoxDescription         `protobuf:"bytes,44,opt,name=plan_box_description,json=planBoxDescription,proto3" json:"plan_box_description,omitempty"`
	Note                     *SubscriptionNote                       `protobuf:"bytes,45,opt,name=note,proto3" json:"note,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *TitleDetailView) Reset() {
	*x = TitleDetailView{}
	mi := &file_title_detail_view_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TitleDetailView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TitleDetailView) ProtoMessage() {}

func (x *TitleDetailView) ProtoReflect() protoreflect.Message {
	mi := &file_title_detail_view_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TitleDetailView.ProtoReflect.Descriptor instead.
func (*TitleDetailView) Descriptor() ([]byte, []int) {
	return file_title_detail_view_proto_rawDescGZIP(), []int{0}
}

func (x *TitleDetailView) GetTitle() *Title {
	if x != nil {
		return x.Title
	}
	return nil
}

func (x *TitleDetailView) GetTitleImageUrl() string {
	if x != nil {
		return x.TitleImageUrl
	}
	return ""
}

func (x *TitleDetailView) GetOverview() string {
	if x != nil {
		return x.Overview
	}
	return ""
}

func (x *TitleDetailView) GetBackgroundImageUrl() string {
	if x != nil {
		return x.BackgroundImageUrl
	}
	return ""
}

func (x *TitleDetailView) GetNextTimeStamp() uint32 {
	if x != nil {
		return x.NextTimeStamp
	}
	return 0
}

func (x *TitleDetailView) GetUpdateTiming() TitleDetailView_UpdateTiming {
	if x != nil {
		return x.UpdateTiming
	}
	return TitleDetailView_NOT_REGULARLY
}

func (x *TitleDetailView) GetViewingPeriodDescription() string {
	if x != nil {
		return x.ViewingPeriodDescription
	}
	return ""
}

func (x *TitleDetailView) GetNonAppearanceInfo() string {
	if x != nil {
		return x.NonAppearanceInfo
	}
	return ""
}

func (x *TitleDetailView) GetFirstChapterList() []*Chapter {
	if x != nil {
		return x.FirstChapterList
	}
	return nil
}

func (x *TitleDetailView) GetLastChapterList() []*Chapter {
	if x != nil {
		return x.LastChapterList
	}
	return nil
}

func (x *TitleDetailView) GetBanners() []*Banner {
	if x != nil {
		return x.Banners
	}
	return nil
}

func (x *TitleDetailView) GetRecommendedTitleList() []*Title {
	if x != nil {
		return x.RecommendedTitleList
	}
	return nil
}

func (x *TitleDetailView) GetSns() *Sns {
	if x != nil {
		return x.Sns
	}
	return nil
}

func (x *TitleDetailView) GetIsSimulReleased() bool {
	if x != nil {
		return x.IsSimulReleased
	}
	return false
}

func (x *TitleDetailView) GetIsSubscribed() bool {
	if x != nil {
		return x.IsSubscribed
	}
	return false
}

func (x *TitleDetailView) GetRating() TitleDetailView_Rating {
	if x != nil {
		return x.Rating
	}
	return TitleDetailView_ALLAGE
}

func (x *TitleDetailView) GetChaptersDescending() bool {
	if x != nil {
		return x.ChaptersDescending
	}
	return false
}

func (x *TitleDetailView) GetNumberOfViews() uint32 {
	if x != nil {
		return x.NumberOfViews
	}
	return 0
}

func (x *TitleDetailView) GetPublisherItems() []*TitleDetailView_PublisherItem {
	if x != nil {
		return x.PublisherItems
	}
	return nil
}

func (x *TitleDetailView) GetTitleBanners() []*Banner {
	if x != nil {
		return x.TitleBanners
	}
	return nil
}

func (x *TitleDetailView) GetUserTickets() *UserTickets {
	if x != nil {
		return x.UserTickets
	}
	return nil
}

func (x *TitleDetailView) GetTicketChapterList() []*Chapter {
	if x != nil {
		return x.TicketChapterList
	}
	return nil
}

func (x *TitleDetailView) GetTicketTitleList() []*Title {
	if x != nil {
		return x.TicketTitleList
	}
	return nil
}

func (x *TitleDetailView) GetHasChaptersBetween() bool {
	if x != nil {
		return x.HasChaptersBetween
	}
	return false
}

func (x *TitleDetailView) GetPublisherBanner() *Banner {
	if x != nil {
		return x.PublisherBanner
	}
	return nil
}

func (x *TitleDetailView) GetAdvertisement() *AdNetworkList {
	if x != nil {
		return x.Advertisement
	}
	return nil
}

func (x *TitleDetailView) GetTitleLanguages() []*TitleDetailView_TitleLanguages {
	if x != nil {
		return x.TitleLanguages
	}
	return nil
}

func (x *TitleDetailView) GetChapterListGroup() []*TitleDetailView_ChapterGroup {
	if x != nil {
		return x.ChapterListGroup
	}
	return nil
}

func (x *TitleDetailView) GetFreeViewDialogue() *FreeViewDialogue {
	if x != nil {
		return x.FreeViewDialogue
	}
	return nil
}

func (x *TitleDetailView) GetRegionCode() string {
	if x != nil {
		return x.RegionCode
	}
	return ""
}

func (x *TitleDetailView) GetTags() []*Tag {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *TitleDetailView) GetTitleLabels() *TitleDetailView_TitleLabels {
	if x != nil {
		return x.TitleLabels
	}
	return nil
}

func (x *TitleDetailView) GetUserSubscription() *Subscription {
	if x != nil {
		return x.UserSubscription
	}
	return nil
}

func (x *TitleDetailView) GetLabel() *Label {
	if x != nil {
		return x.Label
	}
	return nil
}

func (x *TitleDetailView) GetIsFirstTimeFree() bool {
	if x != nil {
		return x.IsFirstTimeFree
	}
	return false
}

func (x *TitleDetailView) GetMetaInfo() *MetaInfo {
	if x != nil {
		return x.MetaInfo
	}
	return nil
}

func (x *TitleDetailView) GetRatingPopup() *Popup {
	if x != nil {
		return x.RatingPopup
	}
	return nil
}

func (x *TitleDetailView) GetChapterListV2() []*Chapter {
	if x != nil {
		return x.ChapterListV2
	}
	return nil
}

func (x *TitleDetailView) GetLabelV2() *LabelV2 {
	if x != nil {
		return x.LabelV2
	}
	return nil
}

func (x *TitleDetailView) GetMiddleChapterNeighbors() *TitleDetailView_MiddleChapterNeighbors {
	if x != nil {
		return x.MiddleChapterNeighbors
	}
	return nil
}

func (x *TitleDetailView) GetIsMerchAvailable() bool {
	if x != nil {
		return x.IsMerchAvailable
	}
	return false
}

func (x *TitleDetailView) GetPlanTypes() []*PlanType {
	if x != nil {
		return x.PlanTypes
	}
	return nil
}

func (x *TitleDetailView) GetUserHasUsedTrial() bool {
	if x != nil {
		return x.UserHasUsedTrial
	}
	return false
}

func (x *TitleDetailView) GetPlanBoxDescription() *SubscriptionPlanBoxDescription {
	if x != nil {
		return x.PlanBoxDescription
	}
	return nil
}

func (x *TitleDetailView) GetNote() *SubscriptionNote {
	if x != nil {
		return x.Note
	}
	return nil
}

type TitleDetailView_TitleLabels struct {
	state           protoimpl.MessageState          `protogen:"open.v1"`
	ReleaseSchedule TitleDetailView_ReleaseSchedule `protobuf:"varint,1,opt,name=release_schedule,json=releaseSchedule,proto3,enum=jp.co.comic.jump.proto.TitleDetailView_ReleaseSchedule" json:"release_schedule,omitempty"`
	IsSimulpub      bool                            `protobuf:"varint,2,opt,name=is_simulpub,json=isSimulpub,proto3" json:"is_simulpub,omitempty"`
	PlanType        string                          `protobuf:"bytes,3,opt,name=plan_type,json=planType,proto3" json:"plan_type,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TitleDetailView_TitleLabels) Reset() {
	*x = TitleDetailView_TitleLabels{}
	mi := &file_title_detail_view_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TitleDetailView_TitleLabels) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TitleDetailView_TitleLabels) ProtoMessage() {}

func (x *TitleDetailView_TitleLabels) ProtoReflect() protoreflect.Message {
	mi := &file_title_detail_view_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TitleDetailView_TitleLabels.ProtoReflect.Descriptor instead.
func (*TitleDetailView_TitleLabels) Descriptor() ([]byte, []int) {
	return file_title_detail_view_proto_rawDescGZIP(), []int{0, 0}
}

func (x *TitleDetailView_TitleLabels) GetReleaseSchedule() TitleDetailView_ReleaseSchedule {
	if x != nil {
		return x.ReleaseSchedule
	}
	return TitleDetailView_DISABLED
}

func (x *TitleDetailView_TitleLabels) GetIsSimulpub() bool {
	if x != nil {
		return x.IsSimulpub
	}
	return false
}

func (x *TitleDetailView_TitleLabels) GetPlanType() string {
	if x != nil {
		return x.PlanType
	}
	return ""
}

type TitleDetailView_PublisherItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Banner        *Banner                `protobuf:"bytes,1,opt,name=banner,proto3" json:"banner,omitempty"`
	PublisherNews *PublisherNews         `protobuf:"bytes,2,opt,name=publisher_news,json=publisherNews,proto3" json:"publisher_news,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TitleDetailView_PublisherItem) Reset() {
	*x = TitleDetailView_PublisherItem{}
	mi := &file_title_detail_view_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TitleDetailView_PublisherItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TitleDetailView_PublisherItem) ProtoMessage() {}

func (x *TitleDetailView_PublisherItem) ProtoReflect() protoreflect.Message {
	mi := &file_title_detail_view_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TitleDetailView_PublisherItem.ProtoReflect.Descriptor instead.
func (*TitleDetailView_PublisherItem) Descriptor() ([]byte, []int) {
	return file_title_detail_view_proto_rawDescGZIP(), []int{0, 1}
}

func (x *TitleDetailView_PublisherItem) GetBanner() *Banner {
	if x != nil {
		return x.Banner
	}
	return nil
}

func (x *TitleDetailView_PublisherItem) GetPublisherNews() *PublisherNews {
	if x != nil {
		return x.PublisherNews
	}
	return nil
}

type TitleDetailView_TitleLanguages struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TitleId       uint32                 `protobuf:"varint,1,opt,name=title_id,json=titleId,proto3" json:"title_id,omitempty"`
	Language      Language               `protobuf:"varint,2,opt,name=language,proto3,enum=jp.co.comic.jump.proto.Language" json:"language,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TitleDetailView_TitleLanguages) Reset() {
	*x = TitleDetailView_TitleLanguages{}
	mi := &file_title_detail_view_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TitleDetailView_TitleLanguages) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TitleDetailView_TitleLanguages) ProtoMessage() {}

func (x *TitleDetailView_TitleLanguages) ProtoReflect() protoreflect.Message {
	mi := &file_title_detail_view_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TitleDetailView_TitleLanguages.ProtoReflect.Descriptor instead.
func (*TitleDetailView_TitleLanguages) Descriptor() ([]byte, []int) {
	return file_title_detail_view_proto_rawDescGZIP(), []int{0, 2}
}

func (x *TitleDetailView_TitleLanguages) GetTitleId() uint32 {
	if x != nil {
		return x.TitleId
	}
	return 0
}

func (x *TitleDetailView_TitleLanguages) GetLanguage() Language {
	if x != nil {
		return x.Language
	}
	return Language_ENGLISH
}

type TitleDetailView_ChapterGroup struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ChapterNumbers   string                 `protobuf:"bytes,1,opt,name=chapter_numbers,json=chapterNumbers,proto3" json:"chapter_numbers,omitempty"`
	FirstChapterList []*Chapter             `protobuf:"bytes,2,rep,name=first_chapter_list,json=firstChapterList,proto3" json:"first_chapter_list,omitempty"`
	MidChapterList   []*Chapter             `protobuf:"bytes,3,rep,name=mid_chapter_list,json=midChapterList,proto3" json:"mid_chapter_list,omitempty"`
	LastChapterList  []*Chapter             `protobuf:"bytes,4,rep,name=last_chapter_list,json=lastChapterList,proto3" json:"last_chapter_list,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TitleDetailView_ChapterGroup) Reset() {
	*x = TitleDetailView_ChapterGroup{}
	mi := &file_title_detail_view_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TitleDetailView_ChapterGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TitleDetailView_ChapterGroup) ProtoMessage() {}

func (x *TitleDetailView_ChapterGroup) ProtoReflect() protoreflect.Message {
	mi := &file_title_detail_view_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TitleDetailView_ChapterGroup.ProtoReflect.Descriptor instead.
func (*TitleDetailView_ChapterGroup) Descriptor() ([]byte, []int) {
	return file_title_detail_view_proto_rawDescGZIP(), []int{0, 3}
}

func (x *TitleDetailView_ChapterGroup) GetChapterNumbers() string {
	if x != nil {
		return x.ChapterNumbers
	}
	return ""
}

func (x *TitleDetailView_ChapterGroup) GetFirstChapterList() []*Chapter {
	if x != nil {
		return x.FirstChapterList
	}
	return nil
}

func (x *TitleDetailView_ChapterGroup) GetMidChapterList() []*Chapter {
	if x != nil {
		return x.MidChapterList
	}
	return nil
}

func (x *TitleDetailView_ChapterGroup) GetLastChapterList() []*Chapter {
	if x != nil {
		return x.LastChapterList
	}
	return nil
}

type TitleDetailView_MiddleChapterNeighbors struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PreviousChapterId uint32                 `protobuf:"varint,1,opt,name=previous_chapter_id,json=previousChapterId,proto3" json:"previous_chapter_id,omitempty"`
	NextChapterId     uint32                 `protobuf:"varint,2,opt,name=next_chapter_id,json=nextChapterId,proto3" json:"next_chapter_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TitleDetailView_MiddleChapterNeighbors) Reset() {
	*x = TitleDetailView_MiddleChapterNeighbors{}
	mi := &file_title_detail_view_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TitleDetailView_MiddleChapterNeighbors) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TitleDetailView_MiddleChapterNeighbors) ProtoMessage() {}

func (x *TitleDetailView_MiddleChapterNeighbors) ProtoReflect() protoreflect.Message {
	mi := &file_title_detail_view_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TitleDetailView_MiddleChapterNeighbors.ProtoReflect.Descriptor instead.
func (*TitleDetailView_MiddleChapterNeighbors) Descriptor() ([]byte, []int) {
	return file_title_detail_view_proto_rawDescGZIP(), []int{0, 4}
}

func (x *TitleDetailView_MiddleChapterNeighbors) GetPreviousChapterId() uint32 {
	if x != nil {
		return x.PreviousChapterId
	}
	return 0
}

func (x *TitleDetailView_MiddleChapterNeighbors) GetNextChapterId() uint32 {
	if x != nil {
		return x.NextChapterId
	}
	return 0
}

var File_title_detail_view_proto protoreflect.FileDescriptor

const file_title_detail_view_proto_rawDesc = "" +
	"\n" +
	"\x17title_detail_view.proto\x12\x16jp.co.comic.jump.proto\x1a\x10ad_network.proto\x1a\fbanner.proto\x1a\rchapter.proto\x1a\x0edialogue.proto\x1a\vlabel.proto\x1a\x0elabel_v2.proto\x1a\x0flanguages.proto\x1a\x0fmeta_info.proto\x1a\vpopup.proto\x1a\x14publisher_news.proto\x1a\tsns.proto\x1a\x12subscription.proto\x1a\ttag.proto\x1a\vtitle.proto\x1a\x12user_tickets.proto\"\xc0 \n" +
	"\x0fTitleDetailView\x123\n" +
	"\x05title\x18\x01 \x01(\v2\x1d.jp.co.comic.jump.proto.TitleR\x05title\x12&\n" +
	"\x0ftitle_image_url\x18\x02 \x01(\tR\rtitleImageUrl\x12\x1a\n" +
	"\boverview\x18\x03 \x01(\tR\boverview\x120\n" +
	"\x14background_image_url\x18\x04 \x01(\tR\x12backgroundImageUrl\x12&\n" +
	"\x0fnext_time_stamp\x18\x05 \x01(\rR\rnextTimeStamp\x12Y\n" +
	"\rupdate_timing\x18\x06 \x01(\x0e24.jp.co.comic.jump.proto.TitleDetailView.UpdateTimingR\fupdateTiming\x12<\n" +
	"\x1aviewing_period_description\x18\a \x01(\tR\x18viewingPeriodDescription\x12.\n" +
	"\x13non_appearance_info\x18\b \x01(\tR\x11nonAppearanceInfo\x12M\n" +
	"\x12first_chapter_list\x18\t \x03(\v2\x1f.jp.co.comic.jump.proto.ChapterR\x10firstChapterList\x12K\n" +
	"\x11last_chapter_list\x18\n" +
	" \x03(\v2\x1f.jp.co.comic.jump.proto.ChapterR\x0flastChapterList\x128\n" +
	"\abanners\x18\v \x03(\v2\x1e.jp.co.comic.jump.proto.BannerR\abanners\x12S\n" +
	"\x16recommended_title_list\x18\f \x03(\v2\x1d.jp.co.comic.jump.proto.TitleR\x14recommendedTitleList\x12-\n" +
	"\x03sns\x18\r \x01(\v2\x1b.jp.co.comic.jump.proto.SnsR\x03sns\x12*\n" +
	"\x11is_simul_released\x18\x0e \x01(\bR\x0fisSimulReleased\x12#\n" +
	"\ris_subscribed\x18\x0f \x01(\bR\fisSubscribed\x12F\n" +
	"\x06rating\x18\x10 \x01(\x0e2..jp.co.comic.jump.proto.TitleDetailView.RatingR\x06rating\x12.\n" +
	"\x12chaptersDescending\x18\x11 \x01(\bR\x12chaptersDescending\x12$\n" +
	"\rnumberOfViews\x18\x12 \x01(\rR\rnumberOfViews\x12^\n" +
	"\x0fpublisher_items\x18\x13 \x03(\v25.jp.co.comic.jump.proto.TitleDetailView.PublisherItemR\x0epublisherItems\x12C\n" +
	"\rtitle_banners\x18\x14 \x03(\v2\x1e.jp.co.comic.jump.proto.BannerR\ftitleBanners\x12F\n" +
	"\fuser_tickets\x18\x15 \x01(\v2#.jp.co.comic.jump.proto.UserTicketsR\vuserTickets\x12O\n" +
	"\x13ticket_chapter_list\x18\x16 \x03(\v2\x1f.jp.co.comic.jump.proto.ChapterR\x11ticketChapterList\x12I\n" +
	"\x11ticket_title_list\x18\x17 \x03(\v2\x1d.jp.co.comic.jump.proto.TitleR\x0fticketTitleList\x120\n" +
	"\x14has_chapters_between\x18\x18 \x01(\bR\x12hasChaptersBetween\x12I\n" +
	"\x10publisher_banner\x18\x19 \x01(\v2\x1e.jp.co.comic.jump.proto.BannerR\x0fpublisherBanner\x12K\n" +
	"\radvertisement\x18\x1a \x01(\v2%.jp.co.comic.jump.proto.AdNetworkListR\radvertisement\x12_\n" +
	"\x0ftitle_languages\x18\x1b \x03(\v26.jp.co.comic.jump.proto.TitleDetailView.TitleLanguagesR\x0etitleLanguages\x12b\n" +
	"\x12chapter_list_group\x18\x1c \x03(\v24.jp.co.comic.jump.proto.TitleDetailView.ChapterGroupR\x10chapterListGroup\x12V\n" +
	"\x12free_view_dialogue\x18\x1d \x01(\v2(.jp.co.comic.jump.proto.FreeViewDialogueR\x10freeViewDialogue\x12\x1f\n" +
	"\vregion_code\x18\x1e \x01(\tR\n" +
	"regionCode\x12/\n" +
	"\x04tags\x18\x1f \x03(\v2\x1b.jp.co.comic.jump.proto.TagR\x04tags\x12V\n" +
	"\ftitle_labels\x18  \x01(\v23.jp.co.comic.jump.proto.TitleDetailView.TitleLabelsR\vtitleLabels\x12Q\n" +
	"\x11user_subscription\x18! \x01(\v2$.jp.co.comic.jump.proto.SubscriptionR\x10userSubscription\x123\n" +
	"\x05label\x18\" \x01(\v2\x1d.jp.co.comic.jump.proto.LabelR\x05label\x12+\n" +
	"\x12is_first_time_free\x18# \x01(\bR\x0fisFirstTimeFree\x12=\n" +
	"\tmeta_info\x18$ \x01(\v2 .jp.co.comic.jump.proto.MetaInfoR\bmetaInfo\x12@\n" +
	"\frating_popup\x18% \x01(\v2\x1d.jp.co.comic.jump.proto.PopupR\vratingPopup\x12G\n" +
	"\x0fchapter_list_v2\x18& \x03(\v2\x1f.jp.co.comic.jump.proto.ChapterR\rchapterListV2\x12:\n" +
	"\blabel_v2\x18' \x01(\v2\x1f.jp.co.comic.jump.proto.LabelV2R\alabelV2\x12x\n" +
	"\x18middle_chapter_neighbors\x18( \x01(\v2>.jp.co.comic.jump.proto.TitleDetailView.MiddleChapterNeighborsR\x16middleChapterNeighbors\x12,\n" +
	"\x12is_merch_available\x18) \x01(\bR\x10isMerchAvailable\x12?\n" +
	"\n" +
	"plan_types\x18* \x03(\v2 .jp.co.comic.jump.proto.PlanTypeR\tplanTypes\x12-\n" +
	"\x13user_has_used_trial\x18+ \x01(\bR\x10userHasUsedTrial\x12h\n" +
	"\x14plan_box_description\x18, \x01(\v26.jp.co.comic.jump.proto.SubscriptionPlanBoxDescriptionR\x12planBoxDescription\x12<\n" +
	"\x04note\x18- \x01(\v2(.jp.co.comic.jump.proto.SubscriptionNoteR\x04note\x1a\xaf\x01\n" +
	"\vTitleLabels\x12b\n" +
	"\x10release_schedule\x18\x01 \x01(\x0e27.jp.co.comic.jump.proto.TitleDetailView.ReleaseScheduleR\x0freleaseSchedule\x12\x1f\n" +
	"\vis_simulpub\x18\x02 \x01(\bR\n" +
	"isSimulpub\x12\x1b\n" +
	"\tplan_type\x18\x03 \x01(\tR\bplanType\x1a\x95\x01\n" +
	"\rPublisherItem\x126\n" +
	"\x06banner\x18\x01 \x01(\v2\x1e.jp.co.comic.jump.proto.BannerR\x06banner\x12L\n" +
	"\x0epublisher_news\x18\x02 \x01(\v2%.jp.co.comic.jump.proto.PublisherNewsR\rpublisherNews\x1ai\n" +
	"\x0eTitleLanguages\x12\x19\n" +
	"\btitle_id\x18\x01 \x01(\rR\atitleId\x12<\n" +
	"\blanguage\x18\x02 \x01(\x0e2 .jp.co.comic.jump.proto.LanguageR\blanguage\x1a\x9e\x02\n" +
	"\fChapterGroup\x12'\n" +
	"\x0fchapter_numbers\x18\x01 \x01(\tR\x0echapterNumbers\x12M\n" +
	"\x12first_chapter_list\x18\x02 \x03(\v2\x1f.jp.co.comic.jump.proto.ChapterR\x10firstChapterList\x12I\n" +
	"\x10mid_chapter_list\x18\x03 \x03(\v2\x1f.jp.co.comic.jump.proto.ChapterR\x0emidChapterList\x12K\n" +
	"\x11last_chapter_list\x18\x04 \x03(\v2\x1f.jp.co.comic.jump.proto.ChapterR\x0flastChapterList\x1ap\n" +
	"\x16MiddleChapterNeighbors\x12.\n" +
	"\x13previous_chapter_id\x18\x01 \x01(\rR\x11previousChapterId\x12&\n" +
	"\x0fnext_chapter_id\x18\x02 \x01(\rR\rnextChapterId\"\xa7\x01\n" +
	"\x0fReleaseSchedule\x12\f\n" +
	"\bDISABLED\x10\x00\x12\f\n" +
	"\bEVERYDAY\x10\x01\x12\n" +
	"\n" +
	"\x06WEEKLY\x10\x02\x12\f\n" +
	"\bBIWEEKLY\x10\x03\x12\v\n" +
	"\aMONTHLY\x10\x04\x12\r\n" +
	"\tBIMONTHLY\x10\x05\x12\x0e\n" +
	"\n" +
	"TRIMONTHLY\x10\x06\x12\t\n" +
	"\x05OTHER\x10\a\x12\r\n" +
	"\tCOMPLETED\x10\b\x12\f\n" +
	"\bONE_SHOT\x10\t\x12\n" +
	"\n" +
	"\x06HIATUS\x10\n" +
	"\"\x86\x01\n" +
	"\fUpdateTiming\x12\x11\n" +
	"\rNOT_REGULARLY\x10\x00\x12\n" +
	"\n" +
	"\x06MONDAY\x10\x01\x12\v\n" +
	"\aTUESDAY\x10\x02\x12\r\n" +
	"\tWEDNESDAY\x10\x03\x12\f\n" +
	"\bTHURSDAY\x10\x04\x12\n" +
	"\n" +
	"\x06FRIDAY\x10\x05\x12\f\n" +
	"\bSATURDAY\x10\x06\x12\n" +
	"\n" +
	"\x06SUNDAY\x10\a\x12\a\n" +
	"\x03DAY\x10\b\"8\n" +
	"\x06Rating\x12\n" +
	"\n" +
	"\x06ALLAGE\x10\x00\x12\b\n" +
	"\x04TEEN\x10\x01\x12\f\n" +
	"\bTEENPLUS\x10\x02\x12\n" +
	"\n" +
	"\x06MATURE\x10\x03b\x06proto3"

var (
	file_title_detail_view_proto_rawDescOnce sync.Once
	file_title_detail_view_proto_rawDescData []byte
)

func file_title_detail_view_proto_rawDescGZIP() []byte {
	file_title_detail_view_proto_rawDescOnce.Do(func() {
		file_title_detail_view_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_title_detail_view_proto_rawDesc), len(file_title_detail_view_proto_rawDesc)))
	})
	return file_title_detail_view_proto_rawDescData
}

var file_title_detail_view_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_title_detail_view_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_title_detail_view_proto_goTypes = []any{
	(TitleDetailView_ReleaseSchedule)(0),           // 0: jp.co.comic.jump.proto.TitleDetailView.ReleaseSchedule
	(TitleDetailView_UpdateTiming)(0),              // 1: jp.co.comic.jump.proto.TitleDetailView.UpdateTiming
	(TitleDetailView_Rating)(0),                    // 2: jp.co.comic.jump.proto.TitleDetailView.Rating
	(*TitleDetailView)(nil),                        // 3: jp.co.comic.jump.proto.TitleDetailView
	(*TitleDetailView_TitleLabels)(nil),            // 4: jp.co.comic.jump.proto.TitleDetailView.TitleLabels
	(*TitleDetailView_PublisherItem)(nil),          // 5: jp.co.comic.jump.proto.TitleDetailView.PublisherItem
	(*TitleDetailView_TitleLanguages)(nil),         // 6: jp.co.comic.jump.proto.TitleDetailView.TitleLanguages
	(*TitleDetailView_ChapterGroup)(nil),           // 7: jp.co.comic.jump.proto.TitleDetailView.ChapterGroup
	(*TitleDetailView_MiddleChapterNeighbors)(nil), // 8: jp.co.comic.jump.proto.TitleDetailView.MiddleChapterNeighbors
	(*Title)(nil),                          // 9: jp.co.comic.jump.proto.Title
	(*Chapter)(nil),                        // 10: jp.co.comic.jump.proto.Chapter
	(*Banner)(nil),                         // 11: jp.co.comic.jump.proto.Banner
	(*Sns)(nil),                            // 12: jp.co.comic.jump.proto.Sns
	(*UserTickets)(nil),                    // 13: jp.co.comic.jump.proto.UserTickets
	(*AdNetworkList)(nil),                  // 14: jp.co.comic.jump.proto.AdNetworkList
	(*FreeViewDialogue)(nil),               // 15: jp.co.comic.jump.proto.FreeViewDialogue
	(*Tag)(nil),                            // 16: jp.co.comic.jump.proto.Tag
	(*Subscription)(nil),                   // 17: jp.co.comic.jump.proto.Subscription
	(*Label)(nil),                          // 18: jp.co.comic.jump.proto.Label
	(*MetaInfo)(nil),                       // 19: jp.co.comic.jump.proto.MetaInfo
	(*Popup)(nil),                          // 20: jp.co.comic.jump.proto.Popup
	(*LabelV2)(nil),                        // 21: jp.co.comic.jump.proto.LabelV2
	(*PlanType)(nil),                       // 22: jp.co.comic.jump.proto.PlanType
	(*SubscriptionPlanBoxDescription)(nil), // 23: jp.co.comic.jump.proto.SubscriptionPlanBoxDescription
	(*SubscriptionNote)(nil),               // 24: jp.co.comic.jump.proto.SubscriptionNote
	(*PublisherNews)(nil),                  // 25: jp.co.comic.jump.proto.PublisherNews
	(Language)(0),                          // 26: jp.co.comic.jump.proto.Language
}
var file_title_detail_view_proto_depIdxs = []int32{
	9,  // 0: jp.co.comic.jump.proto.TitleDetailView.title:type_name -> jp.co.comic.jump.proto.Title
	1,  // 1: jp.co.comic.jump.proto.TitleDetailView.update_timing:type_name -> jp.co.comic.jump.proto.TitleDetailView.UpdateTiming
	10, // 2: jp.co.comic.jump.proto.TitleDetailView.first_chapter_list:type_name -> jp.co.comic.jump.proto.Chapter
	10, // 3: jp.co.comic.jump.proto.TitleDetailView.last_chapter_list:type_name -> jp.co.comic.jump.proto.Chapter
	11, // 4: jp.co.comic.jump.proto.TitleDetailView.banners:type_name -> jp.co.comic.jump.proto.Banner
	9,  // 5: jp.co.comic.jump.proto.TitleDetailView.recommended_title_list:type_name -> jp.co.comic.jump.proto.Title
	12, // 6: jp.co.comic.jump.proto.TitleDetailView.sns:type_name -> jp.co.comic.jump.proto.Sns
	2,  // 7: jp.co.comic.jump.proto.TitleDetailView.rating:type_name -> jp.co.comic.jump.proto.TitleDetailView.Rating
	5,  // 8: jp.co.comic.jump.proto.TitleDetailView.publisher_items:type_name -> jp.co.comic.jump.proto.TitleDetailView.PublisherItem
	11, // 9: jp.co.comic.jump.proto.TitleDetailView.title_banners:type_name -> jp.co.comic.jump.proto.Banner
	13, // 10: jp.co.comic.jump.proto.TitleDetailView.user_tickets:type_name -> jp.co.comic.jump.proto.UserTickets
	10, // 11: jp.co.comic.jump.proto.TitleDetailView.ticket_chapter_list:type_name -> jp.co.comic.jump.proto.Chapter
	9,  // 12: jp.co.comic.jump.proto.TitleDetailView.ticket_title_list:type_name -> jp.co.comic.jump.proto.Title
	11, // 13: jp.co.comic.jump.proto.TitleDetailView.publisher_banner:type_name -> jp.co.comic.jump.proto.Banner
	14, // 14: jp.co.comic.jump.proto.TitleDetailView.advertisement:type_name -> jp.co.comic.jump.proto.AdNetworkList
	6,  // 15: jp.co.comic.jump.proto.TitleDetailView.title_languages:type_name -> jp.co.comic.jump.proto.TitleDetailView.TitleLanguages
	7,  // 16: jp.co.comic.jump.proto.TitleDetailView.chapter_list_group:type_name -> jp.co.comic.jump.proto.TitleDetailView.ChapterGroup
	15, // 17: jp.co.comic.jump.proto.TitleDetailView.free_view_dialogue:type_name -> jp.co.comic.jump.proto.FreeViewDialogue
	16, // 18: jp.co.comic.jump.proto.TitleDetailView.tags:type_name -> jp.co.comic.jump.proto.Tag
	4,  // 19: jp.co.comic.jump.proto.TitleDetailView.title_labels:type_name -> jp.co.comic.jump.proto.TitleDetailView.TitleLabels
	17, // 20: jp.co.comic.jump.proto.TitleDetailView.user_subscription:type_name -> jp.co.comic.jump.proto.Subscription
	18, // 21: jp.co.comic.jump.proto.TitleDetailView.label:type_name -> jp.co.comic.jump.proto.Label
	19, // 22: jp.co.comic.jump.proto.TitleDetailView.meta_info:type_name -> jp.co.comic.jump.proto.MetaInfo
	20, // 23: jp.co.comic.jump.proto.TitleDetailView.rating_popup:type_name -> jp.co.comic.jump.proto.Popup
	10, // 24: jp.co.comic.jump.proto.TitleDetailView.chapter_list_v2:type_name -> jp.co.comic.jump.proto.Chapter
	21, // 25: jp.co.comic.jump.proto.TitleDetailView.label_v2:type_name -> jp.co.comic.jump.proto.LabelV2
	8,  // 26: jp.co.comic.jump.proto.TitleDetailView.middle_chapter_neighbors:type_name -> jp.co.comic.jump.proto.TitleDetailView.MiddleChapterNeighbors
	22, // 27: jp.co.comic.jump.proto.TitleDetailView.plan_types:type_name -> jp.co.comic.jump.proto.PlanType
	23, // 28: jp.co.comic.jump.proto.TitleDetailView.plan_box_description:type_name -> jp.co.comic.jump.proto.SubscriptionPlanBoxDescription
	24, // 29: jp.co.comic.jump.proto.TitleDetailView.note:type_name -> jp.co.comic.jump.proto.SubscriptionNote
	0,  // 30: jp.co.comic.jump.proto.TitleDetailView.TitleLabels.release_schedule:type_name -> jp.co.comic.jump.proto.TitleDetailView.ReleaseSchedule
	11, // 31: jp.co.comic.jump.proto.TitleDetailView.PublisherItem.banner:type_name -> jp.co.comic.jump.proto.Banner
	25, // 32: jp.co.comic.jump.proto.TitleDetailView.PublisherItem.publisher_news:type_name -> jp.co.comic.jump.proto.PublisherNews
	26, // 33: jp.co.comic.jump.proto.TitleDetailView.TitleLanguages.language:type_name -> jp.co.comic.jump.proto.Language
	10, // 34: jp.co.comic.jump.proto.TitleDetailView.ChapterGroup.first_chapter_list:type_name -> jp.co.comic.jump.proto.Chapter
	10, // 35: jp.co.comic.jump.proto.TitleDetailView.ChapterGroup.mid_chapter_list:type_name -> jp.co.comic.jump.proto.Chapter
	10, // 36: jp.co.comic.jump.proto.TitleDetailView.ChapterGroup.last_chapter_list:type_name -> jp.co.comic.jump.proto.Chapter
	37, // [37:37] is the sub-list for method output_type
	37, // [37:37] is the sub-list for method input_type
	37, // [37:37] is the sub-list for extension type_name
	37, // [37:37] is the sub-list for extension extendee
	0,  // [0:37] is the sub-list for field type_name
}

func init() { file_title_detail_view_proto_init() }
func file_title_detail_view_proto_init() {
	if File_title_detail_view_proto != nil {
		return
	}
	file_ad_network_proto_init()
	file_banner_proto_init()
	file_chapter_proto_init()
	file_dialogue_proto_init()
	file_label_proto_init()
	file_label_v2_proto_init()
	file_languages_proto_init()
	file_meta_info_proto_init()
	file_popup_proto_init()
	file_publisher_news_proto_init()
	file_sns_proto_init()
	file_subscription_proto_init()
	file_tag_proto_init()
	file_title_proto_init()
	file_user_tickets_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_title_detail_view_proto_rawDesc), len(file_title_detail_view_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_title_detail_view_proto_goTypes,
		DependencyIndexes: file_title_detail_view_proto_depIdxs,
		EnumInfos:         file_title_detail_view_proto_enumTypes,
		MessageInfos:      file_title_detail_view_proto_msgTypes,
	}.Build()
	File_title_detail_view_proto = out.File
	file_title_detail_view_proto_goTypes = nil
	file_title_detail_view_proto_depIdxs = nil
}
