// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: title_ranking_view_v2.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TitleRankingViewV2 struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RankingBanners   []*Banner              `protobuf:"bytes,1,rep,name=ranking_banners,json=rankingBanners,proto3" json:"ranking_banners,omitempty"`
	UpdatedTimeStamp uint32                 `protobuf:"varint,2,opt,name=updated_time_stamp,json=updatedTimeStamp,proto3" json:"updated_time_stamp,omitempty"`
	RankedTitles     []*TitleRankingGroup   `protobuf:"bytes,3,rep,name=ranked_titles,json=rankedTitles,proto3" json:"ranked_titles,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TitleRankingViewV2) Reset() {
	*x = TitleRankingViewV2{}
	mi := &file_title_ranking_view_v2_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TitleRankingViewV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TitleRankingViewV2) ProtoMessage() {}

func (x *TitleRankingViewV2) ProtoReflect() protoreflect.Message {
	mi := &file_title_ranking_view_v2_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TitleRankingViewV2.ProtoReflect.Descriptor instead.
func (*TitleRankingViewV2) Descriptor() ([]byte, []int) {
	return file_title_ranking_view_v2_proto_rawDescGZIP(), []int{0}
}

func (x *TitleRankingViewV2) GetRankingBanners() []*Banner {
	if x != nil {
		return x.RankingBanners
	}
	return nil
}

func (x *TitleRankingViewV2) GetUpdatedTimeStamp() uint32 {
	if x != nil {
		return x.UpdatedTimeStamp
	}
	return 0
}

func (x *TitleRankingViewV2) GetRankedTitles() []*TitleRankingGroup {
	if x != nil {
		return x.RankedTitles
	}
	return nil
}

var File_title_ranking_view_v2_proto protoreflect.FileDescriptor

const file_title_ranking_view_v2_proto_rawDesc = "" +
	"\n" +
	"\x1btitle_ranking_view_v2.proto\x12\x16jp.co.comic.jump.proto\x1a\fbanner.proto\x1a\x16title_list_group.proto\"\xdb\x01\n" +
	"\x12TitleRankingViewV2\x12G\n" +
	"\x0franking_banners\x18\x01 \x03(\v2\x1e.jp.co.comic.jump.proto.BannerR\x0erankingBanners\x12,\n" +
	"\x12updated_time_stamp\x18\x02 \x01(\rR\x10updatedTimeStamp\x12N\n" +
	"\rranked_titles\x18\x03 \x03(\v2).jp.co.comic.jump.proto.TitleRankingGroupR\frankedTitlesb\x06proto3"

var (
	file_title_ranking_view_v2_proto_rawDescOnce sync.Once
	file_title_ranking_view_v2_proto_rawDescData []byte
)

func file_title_ranking_view_v2_proto_rawDescGZIP() []byte {
	file_title_ranking_view_v2_proto_rawDescOnce.Do(func() {
		file_title_ranking_view_v2_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_title_ranking_view_v2_proto_rawDesc), len(file_title_ranking_view_v2_proto_rawDesc)))
	})
	return file_title_ranking_view_v2_proto_rawDescData
}

var file_title_ranking_view_v2_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_title_ranking_view_v2_proto_goTypes = []any{
	(*TitleRankingViewV2)(nil), // 0: jp.co.comic.jump.proto.TitleRankingViewV2
	(*Banner)(nil),             // 1: jp.co.comic.jump.proto.Banner
	(*TitleRankingGroup)(nil),  // 2: jp.co.comic.jump.proto.TitleRankingGroup
}
var file_title_ranking_view_v2_proto_depIdxs = []int32{
	1, // 0: jp.co.comic.jump.proto.TitleRankingViewV2.ranking_banners:type_name -> jp.co.comic.jump.proto.Banner
	2, // 1: jp.co.comic.jump.proto.TitleRankingViewV2.ranked_titles:type_name -> jp.co.comic.jump.proto.TitleRankingGroup
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_title_ranking_view_v2_proto_init() }
func file_title_ranking_view_v2_proto_init() {
	if File_title_ranking_view_v2_proto != nil {
		return
	}
	file_banner_proto_init()
	file_title_list_group_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_title_ranking_view_v2_proto_rawDesc), len(file_title_ranking_view_v2_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_title_ranking_view_v2_proto_goTypes,
		DependencyIndexes: file_title_ranking_view_v2_proto_depIdxs,
		MessageInfos:      file_title_ranking_view_v2_proto_msgTypes,
	}.Build()
	File_title_ranking_view_v2_proto = out.File
	file_title_ranking_view_v2_proto_goTypes = nil
	file_title_ranking_view_v2_proto_depIdxs = nil
}
