// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: title_list_group.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AllTitlesGroup struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	TheTitle                  string                 `protobuf:"bytes,1,opt,name=the_title,json=theTitle,proto3" json:"the_title,omitempty"`
	Titles                    []*Title               `protobuf:"bytes,2,rep,name=titles,proto3" json:"titles,omitempty"`
	Tags                      []*Tag                 `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	Label                     *Label                 `protobuf:"bytes,4,opt,name=label,proto3" json:"label,omitempty"`
	NextChapterStartTimestamp uint32                 `protobuf:"varint,5,opt,name=next_chapter_start_timestamp,json=nextChapterStartTimestamp,proto3" json:"next_chapter_start_timestamp,omitempty"`
	LabelV2                   *LabelV2               `protobuf:"bytes,6,opt,name=label_v2,json=labelV2,proto3" json:"label_v2,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *AllTitlesGroup) Reset() {
	*x = AllTitlesGroup{}
	mi := &file_title_list_group_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllTitlesGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllTitlesGroup) ProtoMessage() {}

func (x *AllTitlesGroup) ProtoReflect() protoreflect.Message {
	mi := &file_title_list_group_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllTitlesGroup.ProtoReflect.Descriptor instead.
func (*AllTitlesGroup) Descriptor() ([]byte, []int) {
	return file_title_list_group_proto_rawDescGZIP(), []int{0}
}

func (x *AllTitlesGroup) GetTheTitle() string {
	if x != nil {
		return x.TheTitle
	}
	return ""
}

func (x *AllTitlesGroup) GetTitles() []*Title {
	if x != nil {
		return x.Titles
	}
	return nil
}

func (x *AllTitlesGroup) GetTags() []*Tag {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *AllTitlesGroup) GetLabel() *Label {
	if x != nil {
		return x.Label
	}
	return nil
}

func (x *AllTitlesGroup) GetNextChapterStartTimestamp() uint32 {
	if x != nil {
		return x.NextChapterStartTimestamp
	}
	return 0
}

func (x *AllTitlesGroup) GetLabelV2() *LabelV2 {
	if x != nil {
		return x.LabelV2
	}
	return nil
}

type TitleRankingGroup struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	OriginalTitleId uint32                 `protobuf:"varint,1,opt,name=original_title_id,json=originalTitleId,proto3" json:"original_title_id,omitempty"`
	Titles          []*Title               `protobuf:"bytes,2,rep,name=titles,proto3" json:"titles,omitempty"`
	Score           uint32                 `protobuf:"varint,3,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TitleRankingGroup) Reset() {
	*x = TitleRankingGroup{}
	mi := &file_title_list_group_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TitleRankingGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TitleRankingGroup) ProtoMessage() {}

func (x *TitleRankingGroup) ProtoReflect() protoreflect.Message {
	mi := &file_title_list_group_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TitleRankingGroup.ProtoReflect.Descriptor instead.
func (*TitleRankingGroup) Descriptor() ([]byte, []int) {
	return file_title_list_group_proto_rawDescGZIP(), []int{1}
}

func (x *TitleRankingGroup) GetOriginalTitleId() uint32 {
	if x != nil {
		return x.OriginalTitleId
	}
	return 0
}

func (x *TitleRankingGroup) GetTitles() []*Title {
	if x != nil {
		return x.Titles
	}
	return nil
}

func (x *TitleRankingGroup) GetScore() uint32 {
	if x != nil {
		return x.Score
	}
	return 0
}

type TitleUpdatedGroup struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	UpdatedTitleTimestamp uint32                 `protobuf:"varint,1,opt,name=updated_title_timestamp,json=updatedTitleTimestamp,proto3" json:"updated_title_timestamp,omitempty"`
	LatestTitle           []*AllTitlesGroup      `protobuf:"bytes,2,rep,name=latest_title,json=latestTitle,proto3" json:"latest_title,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *TitleUpdatedGroup) Reset() {
	*x = TitleUpdatedGroup{}
	mi := &file_title_list_group_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TitleUpdatedGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TitleUpdatedGroup) ProtoMessage() {}

func (x *TitleUpdatedGroup) ProtoReflect() protoreflect.Message {
	mi := &file_title_list_group_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TitleUpdatedGroup.ProtoReflect.Descriptor instead.
func (*TitleUpdatedGroup) Descriptor() ([]byte, []int) {
	return file_title_list_group_proto_rawDescGZIP(), []int{2}
}

func (x *TitleUpdatedGroup) GetUpdatedTitleTimestamp() uint32 {
	if x != nil {
		return x.UpdatedTitleTimestamp
	}
	return 0
}

func (x *TitleUpdatedGroup) GetLatestTitle() []*AllTitlesGroup {
	if x != nil {
		return x.LatestTitle
	}
	return nil
}

type LabeledTitlesGroup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TheTitle      string                 `protobuf:"bytes,1,opt,name=the_title,json=theTitle,proto3" json:"the_title,omitempty"`
	Titles        []*Title               `protobuf:"bytes,2,rep,name=titles,proto3" json:"titles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LabeledTitlesGroup) Reset() {
	*x = LabeledTitlesGroup{}
	mi := &file_title_list_group_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LabeledTitlesGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LabeledTitlesGroup) ProtoMessage() {}

func (x *LabeledTitlesGroup) ProtoReflect() protoreflect.Message {
	mi := &file_title_list_group_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LabeledTitlesGroup.ProtoReflect.Descriptor instead.
func (*LabeledTitlesGroup) Descriptor() ([]byte, []int) {
	return file_title_list_group_proto_rawDescGZIP(), []int{3}
}

func (x *LabeledTitlesGroup) GetTheTitle() string {
	if x != nil {
		return x.TheTitle
	}
	return ""
}

func (x *LabeledTitlesGroup) GetTitles() []*Title {
	if x != nil {
		return x.Titles
	}
	return nil
}

type TitleSubscriptionGroup struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Plan           string                 `protobuf:"bytes,1,opt,name=plan,proto3" json:"plan,omitempty"`
	Titles         []*Title               `protobuf:"bytes,2,rep,name=titles,proto3" json:"titles,omitempty"`
	TitleCountText string                 `protobuf:"bytes,3,opt,name=title_count_text,json=titleCountText,proto3" json:"title_count_text,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TitleSubscriptionGroup) Reset() {
	*x = TitleSubscriptionGroup{}
	mi := &file_title_list_group_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TitleSubscriptionGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TitleSubscriptionGroup) ProtoMessage() {}

func (x *TitleSubscriptionGroup) ProtoReflect() protoreflect.Message {
	mi := &file_title_list_group_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TitleSubscriptionGroup.ProtoReflect.Descriptor instead.
func (*TitleSubscriptionGroup) Descriptor() ([]byte, []int) {
	return file_title_list_group_proto_rawDescGZIP(), []int{4}
}

func (x *TitleSubscriptionGroup) GetPlan() string {
	if x != nil {
		return x.Plan
	}
	return ""
}

func (x *TitleSubscriptionGroup) GetTitles() []*Title {
	if x != nil {
		return x.Titles
	}
	return nil
}

func (x *TitleSubscriptionGroup) GetTitleCountText() string {
	if x != nil {
		return x.TitleCountText
	}
	return ""
}

var File_title_list_group_proto protoreflect.FileDescriptor

const file_title_list_group_proto_rawDesc = "" +
	"\n" +
	"\x16title_list_group.proto\x12\x16jp.co.comic.jump.proto\x1a\vlabel.proto\x1a\x0elabel_v2.proto\x1a\ttag.proto\x1a\vtitle.proto\"\xc7\x02\n" +
	"\x0eAllTitlesGroup\x12\x1b\n" +
	"\tthe_title\x18\x01 \x01(\tR\btheTitle\x125\n" +
	"\x06titles\x18\x02 \x03(\v2\x1d.jp.co.comic.jump.proto.TitleR\x06titles\x12/\n" +
	"\x04tags\x18\x03 \x03(\v2\x1b.jp.co.comic.jump.proto.TagR\x04tags\x123\n" +
	"\x05label\x18\x04 \x01(\v2\x1d.jp.co.comic.jump.proto.LabelR\x05label\x12?\n" +
	"\x1cnext_chapter_start_timestamp\x18\x05 \x01(\rR\x19nextChapterStartTimestamp\x12:\n" +
	"\blabel_v2\x18\x06 \x01(\v2\x1f.jp.co.comic.jump.proto.LabelV2R\alabelV2\"\x8c\x01\n" +
	"\x11TitleRankingGroup\x12*\n" +
	"\x11original_title_id\x18\x01 \x01(\rR\x0foriginalTitleId\x125\n" +
	"\x06titles\x18\x02 \x03(\v2\x1d.jp.co.comic.jump.proto.TitleR\x06titles\x12\x14\n" +
	"\x05score\x18\x03 \x01(\rR\x05score\"\x96\x01\n" +
	"\x11TitleUpdatedGroup\x126\n" +
	"\x17updated_title_timestamp\x18\x01 \x01(\rR\x15updatedTitleTimestamp\x12I\n" +
	"\flatest_title\x18\x02 \x03(\v2&.jp.co.comic.jump.proto.AllTitlesGroupR\vlatestTitle\"h\n" +
	"\x12LabeledTitlesGroup\x12\x1b\n" +
	"\tthe_title\x18\x01 \x01(\tR\btheTitle\x125\n" +
	"\x06titles\x18\x02 \x03(\v2\x1d.jp.co.comic.jump.proto.TitleR\x06titles\"\x8d\x01\n" +
	"\x16TitleSubscriptionGroup\x12\x12\n" +
	"\x04plan\x18\x01 \x01(\tR\x04plan\x125\n" +
	"\x06titles\x18\x02 \x03(\v2\x1d.jp.co.comic.jump.proto.TitleR\x06titles\x12(\n" +
	"\x10title_count_text\x18\x03 \x01(\tR\x0etitleCountTextb\x06proto3"

var (
	file_title_list_group_proto_rawDescOnce sync.Once
	file_title_list_group_proto_rawDescData []byte
)

func file_title_list_group_proto_rawDescGZIP() []byte {
	file_title_list_group_proto_rawDescOnce.Do(func() {
		file_title_list_group_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_title_list_group_proto_rawDesc), len(file_title_list_group_proto_rawDesc)))
	})
	return file_title_list_group_proto_rawDescData
}

var file_title_list_group_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_title_list_group_proto_goTypes = []any{
	(*AllTitlesGroup)(nil),         // 0: jp.co.comic.jump.proto.AllTitlesGroup
	(*TitleRankingGroup)(nil),      // 1: jp.co.comic.jump.proto.TitleRankingGroup
	(*TitleUpdatedGroup)(nil),      // 2: jp.co.comic.jump.proto.TitleUpdatedGroup
	(*LabeledTitlesGroup)(nil),     // 3: jp.co.comic.jump.proto.LabeledTitlesGroup
	(*TitleSubscriptionGroup)(nil), // 4: jp.co.comic.jump.proto.TitleSubscriptionGroup
	(*Title)(nil),                  // 5: jp.co.comic.jump.proto.Title
	(*Tag)(nil),                    // 6: jp.co.comic.jump.proto.Tag
	(*Label)(nil),                  // 7: jp.co.comic.jump.proto.Label
	(*LabelV2)(nil),                // 8: jp.co.comic.jump.proto.LabelV2
}
var file_title_list_group_proto_depIdxs = []int32{
	5, // 0: jp.co.comic.jump.proto.AllTitlesGroup.titles:type_name -> jp.co.comic.jump.proto.Title
	6, // 1: jp.co.comic.jump.proto.AllTitlesGroup.tags:type_name -> jp.co.comic.jump.proto.Tag
	7, // 2: jp.co.comic.jump.proto.AllTitlesGroup.label:type_name -> jp.co.comic.jump.proto.Label
	8, // 3: jp.co.comic.jump.proto.AllTitlesGroup.label_v2:type_name -> jp.co.comic.jump.proto.LabelV2
	5, // 4: jp.co.comic.jump.proto.TitleRankingGroup.titles:type_name -> jp.co.comic.jump.proto.Title
	0, // 5: jp.co.comic.jump.proto.TitleUpdatedGroup.latest_title:type_name -> jp.co.comic.jump.proto.AllTitlesGroup
	5, // 6: jp.co.comic.jump.proto.LabeledTitlesGroup.titles:type_name -> jp.co.comic.jump.proto.Title
	5, // 7: jp.co.comic.jump.proto.TitleSubscriptionGroup.titles:type_name -> jp.co.comic.jump.proto.Title
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_title_list_group_proto_init() }
func file_title_list_group_proto_init() {
	if File_title_list_group_proto != nil {
		return
	}
	file_label_proto_init()
	file_label_v2_proto_init()
	file_tag_proto_init()
	file_title_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_title_list_group_proto_rawDesc), len(file_title_list_group_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_title_list_group_proto_goTypes,
		DependencyIndexes: file_title_list_group_proto_depIdxs,
		MessageInfos:      file_title_list_group_proto_msgTypes,
	}.Build()
	File_title_list_group_proto = out.File
	file_title_list_group_proto_goTypes = nil
	file_title_list_group_proto_depIdxs = nil
}
