// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: title_ranking_view.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TitleRankingView struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Titles        []*Title               `protobuf:"bytes,1,rep,name=titles,proto3" json:"titles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TitleRankingView) Reset() {
	*x = TitleRankingView{}
	mi := &file_title_ranking_view_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TitleRankingView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TitleRankingView) ProtoMessage() {}

func (x *TitleRankingView) ProtoReflect() protoreflect.Message {
	mi := &file_title_ranking_view_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TitleRankingView.ProtoReflect.Descriptor instead.
func (*TitleRankingView) Descriptor() ([]byte, []int) {
	return file_title_ranking_view_proto_rawDescGZIP(), []int{0}
}

func (x *TitleRankingView) GetTitles() []*Title {
	if x != nil {
		return x.Titles
	}
	return nil
}

var File_title_ranking_view_proto protoreflect.FileDescriptor

const file_title_ranking_view_proto_rawDesc = "" +
	"\n" +
	"\x18title_ranking_view.proto\x12\x16jp.co.comic.jump.proto\x1a\vtitle.proto\"I\n" +
	"\x10TitleRankingView\x125\n" +
	"\x06titles\x18\x01 \x03(\v2\x1d.jp.co.comic.jump.proto.TitleR\x06titlesb\x06proto3"

var (
	file_title_ranking_view_proto_rawDescOnce sync.Once
	file_title_ranking_view_proto_rawDescData []byte
)

func file_title_ranking_view_proto_rawDescGZIP() []byte {
	file_title_ranking_view_proto_rawDescOnce.Do(func() {
		file_title_ranking_view_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_title_ranking_view_proto_rawDesc), len(file_title_ranking_view_proto_rawDesc)))
	})
	return file_title_ranking_view_proto_rawDescData
}

var file_title_ranking_view_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_title_ranking_view_proto_goTypes = []any{
	(*TitleRankingView)(nil), // 0: jp.co.comic.jump.proto.TitleRankingView
	(*Title)(nil),            // 1: jp.co.comic.jump.proto.Title
}
var file_title_ranking_view_proto_depIdxs = []int32{
	1, // 0: jp.co.comic.jump.proto.TitleRankingView.titles:type_name -> jp.co.comic.jump.proto.Title
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_title_ranking_view_proto_init() }
func file_title_ranking_view_proto_init() {
	if File_title_ranking_view_proto != nil {
		return
	}
	file_title_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_title_ranking_view_proto_rawDesc), len(file_title_ranking_view_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_title_ranking_view_proto_goTypes,
		DependencyIndexes: file_title_ranking_view_proto_depIdxs,
		MessageInfos:      file_title_ranking_view_proto_msgTypes,
	}.Build()
	File_title_ranking_view_proto = out.File
	file_title_ranking_view_proto_goTypes = nil
	file_title_ranking_view_proto_depIdxs = nil
}
