// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: title.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TitleUpdateStatus int32

const (
	TitleUpdateStatus_NONE            TitleUpdateStatus = 0
	TitleUpdateStatus_NEW             TitleUpdateStatus = 1
	TitleUpdateStatus_UP              TitleUpdateStatus = 2
	TitleUpdateStatus_REEDITION       TitleUpdateStatus = 3
	TitleUpdateStatus_CREATORS_STATUS TitleUpdateStatus = 4
	TitleUpdateStatus_OUR_PICKS       TitleUpdateStatus = 5
)

// Enum value maps for TitleUpdateStatus.
var (
	TitleUpdateStatus_name = map[int32]string{
		0: "NONE",
		1: "NEW",
		2: "UP",
		3: "REEDITION",
		4: "CREATORS_STATUS",
		5: "OUR_PICKS",
	}
	TitleUpdateStatus_value = map[string]int32{
		"NONE":            0,
		"NEW":             1,
		"UP":              2,
		"REEDITION":       3,
		"CREATORS_STATUS": 4,
		"OUR_PICKS":       5,
	}
)

func (x TitleUpdateStatus) Enum() *TitleUpdateStatus {
	p := new(TitleUpdateStatus)
	*p = x
	return p
}

func (x TitleUpdateStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TitleUpdateStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_title_proto_enumTypes[0].Descriptor()
}

func (TitleUpdateStatus) Type() protoreflect.EnumType {
	return &file_title_proto_enumTypes[0]
}

func (x TitleUpdateStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TitleUpdateStatus.Descriptor instead.
func (TitleUpdateStatus) EnumDescriptor() ([]byte, []int) {
	return file_title_proto_rawDescGZIP(), []int{0}
}

type Title struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TitleId           uint32                 `protobuf:"varint,1,opt,name=title_id,json=titleId,proto3" json:"title_id,omitempty"`
	Name              string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Author            string                 `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	PortraitImageUrl  string                 `protobuf:"bytes,4,opt,name=portrait_image_url,json=portraitImageUrl,proto3" json:"portrait_image_url,omitempty"`
	LandscapeImageUrl string                 `protobuf:"bytes,5,opt,name=landscape_image_url,json=landscapeImageUrl,proto3" json:"landscape_image_url,omitempty"`
	ViewCount         uint32                 `protobuf:"varint,6,opt,name=viewCount,proto3" json:"viewCount,omitempty"`
	Language          Language               `protobuf:"varint,7,opt,name=language,proto3,enum=jp.co.comic.jump.proto.Language" json:"language,omitempty"`
	TitleUpdateStatus TitleUpdateStatus      `protobuf:"varint,8,opt,name=titleUpdateStatus,proto3,enum=jp.co.comic.jump.proto.TitleUpdateStatus" json:"titleUpdateStatus,omitempty"`
	FavoriteImageUrl  string                 `protobuf:"bytes,9,opt,name=favorite_image_url,json=favoriteImageUrl,proto3" json:"favorite_image_url,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Title) Reset() {
	*x = Title{}
	mi := &file_title_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Title) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Title) ProtoMessage() {}

func (x *Title) ProtoReflect() protoreflect.Message {
	mi := &file_title_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Title.ProtoReflect.Descriptor instead.
func (*Title) Descriptor() ([]byte, []int) {
	return file_title_proto_rawDescGZIP(), []int{0}
}

func (x *Title) GetTitleId() uint32 {
	if x != nil {
		return x.TitleId
	}
	return 0
}

func (x *Title) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Title) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *Title) GetPortraitImageUrl() string {
	if x != nil {
		return x.PortraitImageUrl
	}
	return ""
}

func (x *Title) GetLandscapeImageUrl() string {
	if x != nil {
		return x.LandscapeImageUrl
	}
	return ""
}

func (x *Title) GetViewCount() uint32 {
	if x != nil {
		return x.ViewCount
	}
	return 0
}

func (x *Title) GetLanguage() Language {
	if x != nil {
		return x.Language
	}
	return Language_ENGLISH
}

func (x *Title) GetTitleUpdateStatus() TitleUpdateStatus {
	if x != nil {
		return x.TitleUpdateStatus
	}
	return TitleUpdateStatus_NONE
}

func (x *Title) GetFavoriteImageUrl() string {
	if x != nil {
		return x.FavoriteImageUrl
	}
	return ""
}

type UpdatedTitle struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Title            *Title                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	ChapterId        uint32                 `protobuf:"varint,2,opt,name=chapter_id,json=chapterId,proto3" json:"chapter_id,omitempty"`
	ChapterName      string                 `protobuf:"bytes,3,opt,name=chapter_name,json=chapterName,proto3" json:"chapter_name,omitempty"`
	ChapterSubTitle  string                 `protobuf:"bytes,4,opt,name=chapter_sub_title,json=chapterSubTitle,proto3" json:"chapter_sub_title,omitempty"`
	IsLatest         bool                   `protobuf:"varint,5,opt,name=is_latest,json=isLatest,proto3" json:"is_latest,omitempty"`
	IsVerticalOnly   bool                   `protobuf:"varint,6,opt,name=is_vertical_only,json=isVerticalOnly,proto3" json:"is_vertical_only,omitempty"`
	IsHorizontalOnly bool                   `protobuf:"varint,7,opt,name=is_horizontal_only,json=isHorizontalOnly,proto3" json:"is_horizontal_only,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdatedTitle) Reset() {
	*x = UpdatedTitle{}
	mi := &file_title_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatedTitle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatedTitle) ProtoMessage() {}

func (x *UpdatedTitle) ProtoReflect() protoreflect.Message {
	mi := &file_title_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatedTitle.ProtoReflect.Descriptor instead.
func (*UpdatedTitle) Descriptor() ([]byte, []int) {
	return file_title_proto_rawDescGZIP(), []int{1}
}

func (x *UpdatedTitle) GetTitle() *Title {
	if x != nil {
		return x.Title
	}
	return nil
}

func (x *UpdatedTitle) GetChapterId() uint32 {
	if x != nil {
		return x.ChapterId
	}
	return 0
}

func (x *UpdatedTitle) GetChapterName() string {
	if x != nil {
		return x.ChapterName
	}
	return ""
}

func (x *UpdatedTitle) GetChapterSubTitle() string {
	if x != nil {
		return x.ChapterSubTitle
	}
	return ""
}

func (x *UpdatedTitle) GetIsLatest() bool {
	if x != nil {
		return x.IsLatest
	}
	return false
}

func (x *UpdatedTitle) GetIsVerticalOnly() bool {
	if x != nil {
		return x.IsVerticalOnly
	}
	return false
}

func (x *UpdatedTitle) GetIsHorizontalOnly() bool {
	if x != nil {
		return x.IsHorizontalOnly
	}
	return false
}

type TitleUpdated struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Title                 *Title                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	UpdatedTitleTimestamp string                 `protobuf:"bytes,2,opt,name=updated_title_timestamp,json=updatedTitleTimestamp,proto3" json:"updated_title_timestamp,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *TitleUpdated) Reset() {
	*x = TitleUpdated{}
	mi := &file_title_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TitleUpdated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TitleUpdated) ProtoMessage() {}

func (x *TitleUpdated) ProtoReflect() protoreflect.Message {
	mi := &file_title_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TitleUpdated.ProtoReflect.Descriptor instead.
func (*TitleUpdated) Descriptor() ([]byte, []int) {
	return file_title_proto_rawDescGZIP(), []int{2}
}

func (x *TitleUpdated) GetTitle() *Title {
	if x != nil {
		return x.Title
	}
	return nil
}

func (x *TitleUpdated) GetUpdatedTitleTimestamp() string {
	if x != nil {
		return x.UpdatedTitleTimestamp
	}
	return ""
}

type FreeTitle struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Title                 *Title                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	UpdatedTitleTimestamp string                 `protobuf:"bytes,2,opt,name=updated_title_timestamp,json=updatedTitleTimestamp,proto3" json:"updated_title_timestamp,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *FreeTitle) Reset() {
	*x = FreeTitle{}
	mi := &file_title_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FreeTitle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FreeTitle) ProtoMessage() {}

func (x *FreeTitle) ProtoReflect() protoreflect.Message {
	mi := &file_title_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FreeTitle.ProtoReflect.Descriptor instead.
func (*FreeTitle) Descriptor() ([]byte, []int) {
	return file_title_proto_rawDescGZIP(), []int{3}
}

func (x *FreeTitle) GetTitle() *Title {
	if x != nil {
		return x.Title
	}
	return nil
}

func (x *FreeTitle) GetUpdatedTitleTimestamp() string {
	if x != nil {
		return x.UpdatedTitleTimestamp
	}
	return ""
}

type TicketTitles struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Title              *Title                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	FirstTicketChapter uint32                 `protobuf:"varint,2,opt,name=first_ticket_chapter,json=firstTicketChapter,proto3" json:"first_ticket_chapter,omitempty"`
	LastTicketChapter  uint32                 `protobuf:"varint,3,opt,name=last_ticket_chapter,json=lastTicketChapter,proto3" json:"last_ticket_chapter,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *TicketTitles) Reset() {
	*x = TicketTitles{}
	mi := &file_title_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TicketTitles) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TicketTitles) ProtoMessage() {}

func (x *TicketTitles) ProtoReflect() protoreflect.Message {
	mi := &file_title_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TicketTitles.ProtoReflect.Descriptor instead.
func (*TicketTitles) Descriptor() ([]byte, []int) {
	return file_title_proto_rawDescGZIP(), []int{4}
}

func (x *TicketTitles) GetTitle() *Title {
	if x != nil {
		return x.Title
	}
	return nil
}

func (x *TicketTitles) GetFirstTicketChapter() uint32 {
	if x != nil {
		return x.FirstTicketChapter
	}
	return 0
}

func (x *TicketTitles) GetLastTicketChapter() uint32 {
	if x != nil {
		return x.LastTicketChapter
	}
	return 0
}

type SubscribableTitle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         *Title                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	IsLatest      bool                   `protobuf:"varint,2,opt,name=is_latest,json=isLatest,proto3" json:"is_latest,omitempty"`
	IsSubscribed  bool                   `protobuf:"varint,3,opt,name=is_subscribed,json=isSubscribed,proto3" json:"is_subscribed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribableTitle) Reset() {
	*x = SubscribableTitle{}
	mi := &file_title_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribableTitle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribableTitle) ProtoMessage() {}

func (x *SubscribableTitle) ProtoReflect() protoreflect.Message {
	mi := &file_title_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribableTitle.ProtoReflect.Descriptor instead.
func (*SubscribableTitle) Descriptor() ([]byte, []int) {
	return file_title_proto_rawDescGZIP(), []int{5}
}

func (x *SubscribableTitle) GetTitle() *Title {
	if x != nil {
		return x.Title
	}
	return nil
}

func (x *SubscribableTitle) GetIsLatest() bool {
	if x != nil {
		return x.IsLatest
	}
	return false
}

func (x *SubscribableTitle) GetIsSubscribed() bool {
	if x != nil {
		return x.IsSubscribed
	}
	return false
}

type ComingSoonTitle struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	Title                     *Title                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	NextChapterName           string                 `protobuf:"bytes,2,opt,name=next_chapter_name,json=nextChapterName,proto3" json:"next_chapter_name,omitempty"`
	NextChapterStartTimestamp uint32                 `protobuf:"varint,3,opt,name=next_chapter_start_timestamp,json=nextChapterStartTimestamp,proto3" json:"next_chapter_start_timestamp,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *ComingSoonTitle) Reset() {
	*x = ComingSoonTitle{}
	mi := &file_title_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComingSoonTitle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComingSoonTitle) ProtoMessage() {}

func (x *ComingSoonTitle) ProtoReflect() protoreflect.Message {
	mi := &file_title_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComingSoonTitle.ProtoReflect.Descriptor instead.
func (*ComingSoonTitle) Descriptor() ([]byte, []int) {
	return file_title_proto_rawDescGZIP(), []int{6}
}

func (x *ComingSoonTitle) GetTitle() *Title {
	if x != nil {
		return x.Title
	}
	return nil
}

func (x *ComingSoonTitle) GetNextChapterName() string {
	if x != nil {
		return x.NextChapterName
	}
	return ""
}

func (x *ComingSoonTitle) GetNextChapterStartTimestamp() uint32 {
	if x != nil {
		return x.NextChapterStartTimestamp
	}
	return 0
}

type TitleHighlight struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Title            *Title                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	ChapterId        uint32                 `protobuf:"varint,2,opt,name=chapter_id,json=chapterId,proto3" json:"chapter_id,omitempty"`
	PageUrlList      []string               `protobuf:"bytes,3,rep,name=page_url_list,json=pageUrlList,proto3" json:"page_url_list,omitempty"`
	PageHight        uint32                 `protobuf:"varint,4,opt,name=page_hight,json=pageHight,proto3" json:"page_hight,omitempty"`
	PageWidth        uint32                 `protobuf:"varint,5,opt,name=page_width,json=pageWidth,proto3" json:"page_width,omitempty"`
	IsVerticalOnly   bool                   `protobuf:"varint,6,opt,name=is_vertical_only,json=isVerticalOnly,proto3" json:"is_vertical_only,omitempty"`
	IsHorizontalOnly bool                   `protobuf:"varint,7,opt,name=is_horizontal_only,json=isHorizontalOnly,proto3" json:"is_horizontal_only,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TitleHighlight) Reset() {
	*x = TitleHighlight{}
	mi := &file_title_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TitleHighlight) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TitleHighlight) ProtoMessage() {}

func (x *TitleHighlight) ProtoReflect() protoreflect.Message {
	mi := &file_title_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TitleHighlight.ProtoReflect.Descriptor instead.
func (*TitleHighlight) Descriptor() ([]byte, []int) {
	return file_title_proto_rawDescGZIP(), []int{7}
}

func (x *TitleHighlight) GetTitle() *Title {
	if x != nil {
		return x.Title
	}
	return nil
}

func (x *TitleHighlight) GetChapterId() uint32 {
	if x != nil {
		return x.ChapterId
	}
	return 0
}

func (x *TitleHighlight) GetPageUrlList() []string {
	if x != nil {
		return x.PageUrlList
	}
	return nil
}

func (x *TitleHighlight) GetPageHight() uint32 {
	if x != nil {
		return x.PageHight
	}
	return 0
}

func (x *TitleHighlight) GetPageWidth() uint32 {
	if x != nil {
		return x.PageWidth
	}
	return 0
}

func (x *TitleHighlight) GetIsVerticalOnly() bool {
	if x != nil {
		return x.IsVerticalOnly
	}
	return false
}

func (x *TitleHighlight) GetIsHorizontalOnly() bool {
	if x != nil {
		return x.IsHorizontalOnly
	}
	return false
}

var File_title_proto protoreflect.FileDescriptor

const file_title_proto_rawDesc = "" +
	"\n" +
	"\vtitle.proto\x12\x16jp.co.comic.jump.proto\x1a\x0flanguages.proto\"\x8f\x03\n" +
	"\x05Title\x12\x19\n" +
	"\btitle_id\x18\x01 \x01(\rR\atitleId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06author\x18\x03 \x01(\tR\x06author\x12,\n" +
	"\x12portrait_image_url\x18\x04 \x01(\tR\x10portraitImageUrl\x12.\n" +
	"\x13landscape_image_url\x18\x05 \x01(\tR\x11landscapeImageUrl\x12\x1c\n" +
	"\tviewCount\x18\x06 \x01(\rR\tviewCount\x12<\n" +
	"\blanguage\x18\a \x01(\x0e2 .jp.co.comic.jump.proto.LanguageR\blanguage\x12W\n" +
	"\x11titleUpdateStatus\x18\b \x01(\x0e2).jp.co.comic.jump.proto.TitleUpdateStatusR\x11titleUpdateStatus\x12,\n" +
	"\x12favorite_image_url\x18\t \x01(\tR\x10favoriteImageUrl\"\xa6\x02\n" +
	"\fUpdatedTitle\x123\n" +
	"\x05title\x18\x01 \x01(\v2\x1d.jp.co.comic.jump.proto.TitleR\x05title\x12\x1d\n" +
	"\n" +
	"chapter_id\x18\x02 \x01(\rR\tchapterId\x12!\n" +
	"\fchapter_name\x18\x03 \x01(\tR\vchapterName\x12*\n" +
	"\x11chapter_sub_title\x18\x04 \x01(\tR\x0fchapterSubTitle\x12\x1b\n" +
	"\tis_latest\x18\x05 \x01(\bR\bisLatest\x12(\n" +
	"\x10is_vertical_only\x18\x06 \x01(\bR\x0eisVerticalOnly\x12,\n" +
	"\x12is_horizontal_only\x18\a \x01(\bR\x10isHorizontalOnly\"{\n" +
	"\fTitleUpdated\x123\n" +
	"\x05title\x18\x01 \x01(\v2\x1d.jp.co.comic.jump.proto.TitleR\x05title\x126\n" +
	"\x17updated_title_timestamp\x18\x02 \x01(\tR\x15updatedTitleTimestamp\"x\n" +
	"\tFreeTitle\x123\n" +
	"\x05title\x18\x01 \x01(\v2\x1d.jp.co.comic.jump.proto.TitleR\x05title\x126\n" +
	"\x17updated_title_timestamp\x18\x02 \x01(\tR\x15updatedTitleTimestamp\"\xa5\x01\n" +
	"\fTicketTitles\x123\n" +
	"\x05title\x18\x01 \x01(\v2\x1d.jp.co.comic.jump.proto.TitleR\x05title\x120\n" +
	"\x14first_ticket_chapter\x18\x02 \x01(\rR\x12firstTicketChapter\x12.\n" +
	"\x13last_ticket_chapter\x18\x03 \x01(\rR\x11lastTicketChapter\"\x8a\x01\n" +
	"\x11SubscribableTitle\x123\n" +
	"\x05title\x18\x01 \x01(\v2\x1d.jp.co.comic.jump.proto.TitleR\x05title\x12\x1b\n" +
	"\tis_latest\x18\x02 \x01(\bR\bisLatest\x12#\n" +
	"\ris_subscribed\x18\x03 \x01(\bR\fisSubscribed\"\xb3\x01\n" +
	"\x0fComingSoonTitle\x123\n" +
	"\x05title\x18\x01 \x01(\v2\x1d.jp.co.comic.jump.proto.TitleR\x05title\x12*\n" +
	"\x11next_chapter_name\x18\x02 \x01(\tR\x0fnextChapterName\x12?\n" +
	"\x1cnext_chapter_start_timestamp\x18\x03 \x01(\rR\x19nextChapterStartTimestamp\"\x9e\x02\n" +
	"\x0eTitleHighlight\x123\n" +
	"\x05title\x18\x01 \x01(\v2\x1d.jp.co.comic.jump.proto.TitleR\x05title\x12\x1d\n" +
	"\n" +
	"chapter_id\x18\x02 \x01(\rR\tchapterId\x12\"\n" +
	"\rpage_url_list\x18\x03 \x03(\tR\vpageUrlList\x12\x1d\n" +
	"\n" +
	"page_hight\x18\x04 \x01(\rR\tpageHight\x12\x1d\n" +
	"\n" +
	"page_width\x18\x05 \x01(\rR\tpageWidth\x12(\n" +
	"\x10is_vertical_only\x18\x06 \x01(\bR\x0eisVerticalOnly\x12,\n" +
	"\x12is_horizontal_only\x18\a \x01(\bR\x10isHorizontalOnly*a\n" +
	"\x11TitleUpdateStatus\x12\b\n" +
	"\x04NONE\x10\x00\x12\a\n" +
	"\x03NEW\x10\x01\x12\x06\n" +
	"\x02UP\x10\x02\x12\r\n" +
	"\tREEDITION\x10\x03\x12\x13\n" +
	"\x0fCREATORS_STATUS\x10\x04\x12\r\n" +
	"\tOUR_PICKS\x10\x05b\x06proto3"

var (
	file_title_proto_rawDescOnce sync.Once
	file_title_proto_rawDescData []byte
)

func file_title_proto_rawDescGZIP() []byte {
	file_title_proto_rawDescOnce.Do(func() {
		file_title_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_title_proto_rawDesc), len(file_title_proto_rawDesc)))
	})
	return file_title_proto_rawDescData
}

var file_title_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_title_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_title_proto_goTypes = []any{
	(TitleUpdateStatus)(0),    // 0: jp.co.comic.jump.proto.TitleUpdateStatus
	(*Title)(nil),             // 1: jp.co.comic.jump.proto.Title
	(*UpdatedTitle)(nil),      // 2: jp.co.comic.jump.proto.UpdatedTitle
	(*TitleUpdated)(nil),      // 3: jp.co.comic.jump.proto.TitleUpdated
	(*FreeTitle)(nil),         // 4: jp.co.comic.jump.proto.FreeTitle
	(*TicketTitles)(nil),      // 5: jp.co.comic.jump.proto.TicketTitles
	(*SubscribableTitle)(nil), // 6: jp.co.comic.jump.proto.SubscribableTitle
	(*ComingSoonTitle)(nil),   // 7: jp.co.comic.jump.proto.ComingSoonTitle
	(*TitleHighlight)(nil),    // 8: jp.co.comic.jump.proto.TitleHighlight
	(Language)(0),             // 9: jp.co.comic.jump.proto.Language
}
var file_title_proto_depIdxs = []int32{
	9, // 0: jp.co.comic.jump.proto.Title.language:type_name -> jp.co.comic.jump.proto.Language
	0, // 1: jp.co.comic.jump.proto.Title.titleUpdateStatus:type_name -> jp.co.comic.jump.proto.TitleUpdateStatus
	1, // 2: jp.co.comic.jump.proto.UpdatedTitle.title:type_name -> jp.co.comic.jump.proto.Title
	1, // 3: jp.co.comic.jump.proto.TitleUpdated.title:type_name -> jp.co.comic.jump.proto.Title
	1, // 4: jp.co.comic.jump.proto.FreeTitle.title:type_name -> jp.co.comic.jump.proto.Title
	1, // 5: jp.co.comic.jump.proto.TicketTitles.title:type_name -> jp.co.comic.jump.proto.Title
	1, // 6: jp.co.comic.jump.proto.SubscribableTitle.title:type_name -> jp.co.comic.jump.proto.Title
	1, // 7: jp.co.comic.jump.proto.ComingSoonTitle.title:type_name -> jp.co.comic.jump.proto.Title
	1, // 8: jp.co.comic.jump.proto.TitleHighlight.title:type_name -> jp.co.comic.jump.proto.Title
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_title_proto_init() }
func file_title_proto_init() {
	if File_title_proto != nil {
		return
	}
	file_languages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_title_proto_rawDesc), len(file_title_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_title_proto_goTypes,
		DependencyIndexes: file_title_proto_depIdxs,
		EnumInfos:         file_title_proto_enumTypes,
		MessageInfos:      file_title_proto_msgTypes,
	}.Build()
	File_title_proto = out.File
	file_title_proto_goTypes = nil
	file_title_proto_depIdxs = nil
}
