// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: title_list.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TitleList struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ListName       string                 `protobuf:"bytes,1,opt,name=list_name,json=listName,proto3" json:"list_name,omitempty"`
	FeaturedTitles []*Title               `protobuf:"bytes,2,rep,name=featured_titles,json=featuredTitles,proto3" json:"featured_titles,omitempty"`
	ContainerId    int32                  `protobuf:"varint,3,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TitleList) Reset() {
	*x = TitleList{}
	mi := &file_title_list_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TitleList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TitleList) ProtoMessage() {}

func (x *TitleList) ProtoReflect() protoreflect.Message {
	mi := &file_title_list_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TitleList.ProtoReflect.Descriptor instead.
func (*TitleList) Descriptor() ([]byte, []int) {
	return file_title_list_proto_rawDescGZIP(), []int{0}
}

func (x *TitleList) GetListName() string {
	if x != nil {
		return x.ListName
	}
	return ""
}

func (x *TitleList) GetFeaturedTitles() []*Title {
	if x != nil {
		return x.FeaturedTitles
	}
	return nil
}

func (x *TitleList) GetContainerId() int32 {
	if x != nil {
		return x.ContainerId
	}
	return 0
}

type ChapterPageList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ListName      string                 `protobuf:"bytes,1,opt,name=list_name,json=listName,proto3" json:"list_name,omitempty"`
	ChapterPages  []*ChapterPages        `protobuf:"bytes,2,rep,name=chapter_pages,json=chapterPages,proto3" json:"chapter_pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChapterPageList) Reset() {
	*x = ChapterPageList{}
	mi := &file_title_list_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChapterPageList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChapterPageList) ProtoMessage() {}

func (x *ChapterPageList) ProtoReflect() protoreflect.Message {
	mi := &file_title_list_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChapterPageList.ProtoReflect.Descriptor instead.
func (*ChapterPageList) Descriptor() ([]byte, []int) {
	return file_title_list_proto_rawDescGZIP(), []int{1}
}

func (x *ChapterPageList) GetListName() string {
	if x != nil {
		return x.ListName
	}
	return ""
}

func (x *ChapterPageList) GetChapterPages() []*ChapterPages {
	if x != nil {
		return x.ChapterPages
	}
	return nil
}

type ChapterPages struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ContainerId      int32                  `protobuf:"varint,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	ChapterId        int32                  `protobuf:"varint,2,opt,name=chapter_id,json=chapterId,proto3" json:"chapter_id,omitempty"`
	TitleId          uint32                 `protobuf:"varint,3,opt,name=title_id,json=titleId,proto3" json:"title_id,omitempty"`
	Name             string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Author           string                 `protobuf:"bytes,5,opt,name=author,proto3" json:"author,omitempty"`
	FavoriteImageUrl string                 `protobuf:"bytes,6,opt,name=favorite_image_url,json=favoriteImageUrl,proto3" json:"favorite_image_url,omitempty"`
	Pages            []*Page                `protobuf:"bytes,7,rep,name=pages,proto3" json:"pages,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ChapterPages) Reset() {
	*x = ChapterPages{}
	mi := &file_title_list_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChapterPages) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChapterPages) ProtoMessage() {}

func (x *ChapterPages) ProtoReflect() protoreflect.Message {
	mi := &file_title_list_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChapterPages.ProtoReflect.Descriptor instead.
func (*ChapterPages) Descriptor() ([]byte, []int) {
	return file_title_list_proto_rawDescGZIP(), []int{2}
}

func (x *ChapterPages) GetContainerId() int32 {
	if x != nil {
		return x.ContainerId
	}
	return 0
}

func (x *ChapterPages) GetChapterId() int32 {
	if x != nil {
		return x.ChapterId
	}
	return 0
}

func (x *ChapterPages) GetTitleId() uint32 {
	if x != nil {
		return x.TitleId
	}
	return 0
}

func (x *ChapterPages) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ChapterPages) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *ChapterPages) GetFavoriteImageUrl() string {
	if x != nil {
		return x.FavoriteImageUrl
	}
	return ""
}

func (x *ChapterPages) GetPages() []*Page {
	if x != nil {
		return x.Pages
	}
	return nil
}

var File_title_list_proto protoreflect.FileDescriptor

const file_title_list_proto_rawDesc = "" +
	"\n" +
	"\x10title_list.proto\x12\x16jp.co.comic.jump.proto\x1a\n" +
	"page.proto\x1a\vtitle.proto\"\x93\x01\n" +
	"\tTitleList\x12\x1b\n" +
	"\tlist_name\x18\x01 \x01(\tR\blistName\x12F\n" +
	"\x0ffeatured_titles\x18\x02 \x03(\v2\x1d.jp.co.comic.jump.proto.TitleR\x0efeaturedTitles\x12!\n" +
	"\fcontainer_id\x18\x03 \x01(\x05R\vcontainerId\"y\n" +
	"\x0fChapterPageList\x12\x1b\n" +
	"\tlist_name\x18\x01 \x01(\tR\blistName\x12I\n" +
	"\rchapter_pages\x18\x02 \x03(\v2$.jp.co.comic.jump.proto.ChapterPagesR\fchapterPages\"\xf9\x01\n" +
	"\fChapterPages\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\x05R\vcontainerId\x12\x1d\n" +
	"\n" +
	"chapter_id\x18\x02 \x01(\x05R\tchapterId\x12\x19\n" +
	"\btitle_id\x18\x03 \x01(\rR\atitleId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x16\n" +
	"\x06author\x18\x05 \x01(\tR\x06author\x12,\n" +
	"\x12favorite_image_url\x18\x06 \x01(\tR\x10favoriteImageUrl\x122\n" +
	"\x05pages\x18\a \x03(\v2\x1c.jp.co.comic.jump.proto.PageR\x05pagesb\x06proto3"

var (
	file_title_list_proto_rawDescOnce sync.Once
	file_title_list_proto_rawDescData []byte
)

func file_title_list_proto_rawDescGZIP() []byte {
	file_title_list_proto_rawDescOnce.Do(func() {
		file_title_list_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_title_list_proto_rawDesc), len(file_title_list_proto_rawDesc)))
	})
	return file_title_list_proto_rawDescData
}

var file_title_list_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_title_list_proto_goTypes = []any{
	(*TitleList)(nil),       // 0: jp.co.comic.jump.proto.TitleList
	(*ChapterPageList)(nil), // 1: jp.co.comic.jump.proto.ChapterPageList
	(*ChapterPages)(nil),    // 2: jp.co.comic.jump.proto.ChapterPages
	(*Title)(nil),           // 3: jp.co.comic.jump.proto.Title
	(*Page)(nil),            // 4: jp.co.comic.jump.proto.Page
}
var file_title_list_proto_depIdxs = []int32{
	3, // 0: jp.co.comic.jump.proto.TitleList.featured_titles:type_name -> jp.co.comic.jump.proto.Title
	2, // 1: jp.co.comic.jump.proto.ChapterPageList.chapter_pages:type_name -> jp.co.comic.jump.proto.ChapterPages
	4, // 2: jp.co.comic.jump.proto.ChapterPages.pages:type_name -> jp.co.comic.jump.proto.Page
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_title_list_proto_init() }
func file_title_list_proto_init() {
	if File_title_list_proto != nil {
		return
	}
	file_page_proto_init()
	file_title_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_title_list_proto_rawDesc), len(file_title_list_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_title_list_proto_goTypes,
		DependencyIndexes: file_title_list_proto_depIdxs,
		MessageInfos:      file_title_list_proto_msgTypes,
	}.Build()
	File_title_list_proto = out.File
	file_title_list_proto_goTypes = nil
	file_title_list_proto_depIdxs = nil
}
