// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: transition_action.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransitionAction_PresentationMethod int32

const (
	TransitionAction_PUSH     TransitionAction_PresentationMethod = 0
	TransitionAction_MODAL    TransitionAction_PresentationMethod = 1
	TransitionAction_EXTERNAL TransitionAction_PresentationMethod = 2
)

// Enum value maps for TransitionAction_PresentationMethod.
var (
	TransitionAction_PresentationMethod_name = map[int32]string{
		0: "PUSH",
		1: "MODAL",
		2: "EXTERNAL",
	}
	TransitionAction_PresentationMethod_value = map[string]int32{
		"PUSH":     0,
		"MODAL":    1,
		"EXTERNAL": 2,
	}
)

func (x TransitionAction_PresentationMethod) Enum() *TransitionAction_PresentationMethod {
	p := new(TransitionAction_PresentationMethod)
	*p = x
	return p
}

func (x TransitionAction_PresentationMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransitionAction_PresentationMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_transition_action_proto_enumTypes[0].Descriptor()
}

func (TransitionAction_PresentationMethod) Type() protoreflect.EnumType {
	return &file_transition_action_proto_enumTypes[0]
}

func (x TransitionAction_PresentationMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransitionAction_PresentationMethod.Descriptor instead.
func (TransitionAction_PresentationMethod) EnumDescriptor() ([]byte, []int) {
	return file_transition_action_proto_rawDescGZIP(), []int{0, 0}
}

type TransitionAction struct {
	state         protoimpl.MessageState              `protogen:"open.v1"`
	Method        TransitionAction_PresentationMethod `protobuf:"varint,1,opt,name=method,proto3,enum=jp.co.comic.jump.proto.TransitionAction_PresentationMethod" json:"method,omitempty"`
	Url           string                              `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransitionAction) Reset() {
	*x = TransitionAction{}
	mi := &file_transition_action_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransitionAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransitionAction) ProtoMessage() {}

func (x *TransitionAction) ProtoReflect() protoreflect.Message {
	mi := &file_transition_action_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransitionAction.ProtoReflect.Descriptor instead.
func (*TransitionAction) Descriptor() ([]byte, []int) {
	return file_transition_action_proto_rawDescGZIP(), []int{0}
}

func (x *TransitionAction) GetMethod() TransitionAction_PresentationMethod {
	if x != nil {
		return x.Method
	}
	return TransitionAction_PUSH
}

func (x *TransitionAction) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

var File_transition_action_proto protoreflect.FileDescriptor

const file_transition_action_proto_rawDesc = "" +
	"\n" +
	"\x17transition_action.proto\x12\x16jp.co.comic.jump.proto\"\xb2\x01\n" +
	"\x10TransitionAction\x12S\n" +
	"\x06method\x18\x01 \x01(\x0e2;.jp.co.comic.jump.proto.TransitionAction.PresentationMethodR\x06method\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\"7\n" +
	"\x12PresentationMethod\x12\b\n" +
	"\x04PUSH\x10\x00\x12\t\n" +
	"\x05MODAL\x10\x01\x12\f\n" +
	"\bEXTERNAL\x10\x02b\x06proto3"

var (
	file_transition_action_proto_rawDescOnce sync.Once
	file_transition_action_proto_rawDescData []byte
)

func file_transition_action_proto_rawDescGZIP() []byte {
	file_transition_action_proto_rawDescOnce.Do(func() {
		file_transition_action_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transition_action_proto_rawDesc), len(file_transition_action_proto_rawDesc)))
	})
	return file_transition_action_proto_rawDescData
}

var file_transition_action_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_transition_action_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_transition_action_proto_goTypes = []any{
	(TransitionAction_PresentationMethod)(0), // 0: jp.co.comic.jump.proto.TransitionAction.PresentationMethod
	(*TransitionAction)(nil),                 // 1: jp.co.comic.jump.proto.TransitionAction
}
var file_transition_action_proto_depIdxs = []int32{
	0, // 0: jp.co.comic.jump.proto.TransitionAction.method:type_name -> jp.co.comic.jump.proto.TransitionAction.PresentationMethod
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_transition_action_proto_init() }
func file_transition_action_proto_init() {
	if File_transition_action_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transition_action_proto_rawDesc), len(file_transition_action_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_transition_action_proto_goTypes,
		DependencyIndexes: file_transition_action_proto_depIdxs,
		EnumInfos:         file_transition_action_proto_enumTypes,
		MessageInfos:      file_transition_action_proto_msgTypes,
	}.Build()
	File_transition_action_proto = out.File
	file_transition_action_proto_goTypes = nil
	file_transition_action_proto_depIdxs = nil
}
