// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: updated_title_group.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdatedTitleGroup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupName     string                 `protobuf:"bytes,1,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`
	Titles        []*UpdatedTitle        `protobuf:"bytes,2,rep,name=titles,proto3" json:"titles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatedTitleGroup) Reset() {
	*x = UpdatedTitleGroup{}
	mi := &file_updated_title_group_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatedTitleGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatedTitleGroup) ProtoMessage() {}

func (x *UpdatedTitleGroup) ProtoReflect() protoreflect.Message {
	mi := &file_updated_title_group_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatedTitleGroup.ProtoReflect.Descriptor instead.
func (*UpdatedTitleGroup) Descriptor() ([]byte, []int) {
	return file_updated_title_group_proto_rawDescGZIP(), []int{0}
}

func (x *UpdatedTitleGroup) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *UpdatedTitleGroup) GetTitles() []*UpdatedTitle {
	if x != nil {
		return x.Titles
	}
	return nil
}

type UpdatedTitleV2Group struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupName     string                 `protobuf:"bytes,1,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`
	TitleGroups   []*OriginalTitleGroup  `protobuf:"bytes,2,rep,name=title_groups,json=titleGroups,proto3" json:"title_groups,omitempty"`
	GroupNameDays uint32                 `protobuf:"varint,3,opt,name=group_name_days,json=groupNameDays,proto3" json:"group_name_days,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatedTitleV2Group) Reset() {
	*x = UpdatedTitleV2Group{}
	mi := &file_updated_title_group_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatedTitleV2Group) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatedTitleV2Group) ProtoMessage() {}

func (x *UpdatedTitleV2Group) ProtoReflect() protoreflect.Message {
	mi := &file_updated_title_group_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatedTitleV2Group.ProtoReflect.Descriptor instead.
func (*UpdatedTitleV2Group) Descriptor() ([]byte, []int) {
	return file_updated_title_group_proto_rawDescGZIP(), []int{1}
}

func (x *UpdatedTitleV2Group) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *UpdatedTitleV2Group) GetTitleGroups() []*OriginalTitleGroup {
	if x != nil {
		return x.TitleGroups
	}
	return nil
}

func (x *UpdatedTitleV2Group) GetGroupNameDays() uint32 {
	if x != nil {
		return x.GroupNameDays
	}
	return 0
}

type OriginalTitleGroup struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TheTitle          string                 `protobuf:"bytes,1,opt,name=the_title,json=theTitle,proto3" json:"the_title,omitempty"`
	ChapterNumber     string                 `protobuf:"bytes,2,opt,name=chapter_number,json=chapterNumber,proto3" json:"chapter_number,omitempty"`
	Titles            []*UpdatedTitle        `protobuf:"bytes,3,rep,name=titles,proto3" json:"titles,omitempty"`
	ViewCount         uint32                 `protobuf:"varint,4,opt,name=viewCount,proto3" json:"viewCount,omitempty"`
	TitleUpdateStatus TitleUpdateStatus      `protobuf:"varint,5,opt,name=titleUpdateStatus,proto3,enum=jp.co.comic.jump.proto.TitleUpdateStatus" json:"titleUpdateStatus,omitempty"`
	ChapterStartTime  uint32                 `protobuf:"varint,6,opt,name=chapterStartTime,proto3" json:"chapterStartTime,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *OriginalTitleGroup) Reset() {
	*x = OriginalTitleGroup{}
	mi := &file_updated_title_group_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OriginalTitleGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OriginalTitleGroup) ProtoMessage() {}

func (x *OriginalTitleGroup) ProtoReflect() protoreflect.Message {
	mi := &file_updated_title_group_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OriginalTitleGroup.ProtoReflect.Descriptor instead.
func (*OriginalTitleGroup) Descriptor() ([]byte, []int) {
	return file_updated_title_group_proto_rawDescGZIP(), []int{2}
}

func (x *OriginalTitleGroup) GetTheTitle() string {
	if x != nil {
		return x.TheTitle
	}
	return ""
}

func (x *OriginalTitleGroup) GetChapterNumber() string {
	if x != nil {
		return x.ChapterNumber
	}
	return ""
}

func (x *OriginalTitleGroup) GetTitles() []*UpdatedTitle {
	if x != nil {
		return x.Titles
	}
	return nil
}

func (x *OriginalTitleGroup) GetViewCount() uint32 {
	if x != nil {
		return x.ViewCount
	}
	return 0
}

func (x *OriginalTitleGroup) GetTitleUpdateStatus() TitleUpdateStatus {
	if x != nil {
		return x.TitleUpdateStatus
	}
	return TitleUpdateStatus_NONE
}

func (x *OriginalTitleGroup) GetChapterStartTime() uint32 {
	if x != nil {
		return x.ChapterStartTime
	}
	return 0
}

var File_updated_title_group_proto protoreflect.FileDescriptor

const file_updated_title_group_proto_rawDesc = "" +
	"\n" +
	"\x19updated_title_group.proto\x12\x16jp.co.comic.jump.proto\x1a\vtitle.proto\"p\n" +
	"\x11UpdatedTitleGroup\x12\x1d\n" +
	"\n" +
	"group_name\x18\x01 \x01(\tR\tgroupName\x12<\n" +
	"\x06titles\x18\x02 \x03(\v2$.jp.co.comic.jump.proto.UpdatedTitleR\x06titles\"\xab\x01\n" +
	"\x13UpdatedTitleV2Group\x12\x1d\n" +
	"\n" +
	"group_name\x18\x01 \x01(\tR\tgroupName\x12M\n" +
	"\ftitle_groups\x18\x02 \x03(\v2*.jp.co.comic.jump.proto.OriginalTitleGroupR\vtitleGroups\x12&\n" +
	"\x0fgroup_name_days\x18\x03 \x01(\rR\rgroupNameDays\"\xb9\x02\n" +
	"\x12OriginalTitleGroup\x12\x1b\n" +
	"\tthe_title\x18\x01 \x01(\tR\btheTitle\x12%\n" +
	"\x0echapter_number\x18\x02 \x01(\tR\rchapterNumber\x12<\n" +
	"\x06titles\x18\x03 \x03(\v2$.jp.co.comic.jump.proto.UpdatedTitleR\x06titles\x12\x1c\n" +
	"\tviewCount\x18\x04 \x01(\rR\tviewCount\x12W\n" +
	"\x11titleUpdateStatus\x18\x05 \x01(\x0e2).jp.co.comic.jump.proto.TitleUpdateStatusR\x11titleUpdateStatus\x12*\n" +
	"\x10chapterStartTime\x18\x06 \x01(\rR\x10chapterStartTimeb\x06proto3"

var (
	file_updated_title_group_proto_rawDescOnce sync.Once
	file_updated_title_group_proto_rawDescData []byte
)

func file_updated_title_group_proto_rawDescGZIP() []byte {
	file_updated_title_group_proto_rawDescOnce.Do(func() {
		file_updated_title_group_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_updated_title_group_proto_rawDesc), len(file_updated_title_group_proto_rawDesc)))
	})
	return file_updated_title_group_proto_rawDescData
}

var file_updated_title_group_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_updated_title_group_proto_goTypes = []any{
	(*UpdatedTitleGroup)(nil),   // 0: jp.co.comic.jump.proto.UpdatedTitleGroup
	(*UpdatedTitleV2Group)(nil), // 1: jp.co.comic.jump.proto.UpdatedTitleV2Group
	(*OriginalTitleGroup)(nil),  // 2: jp.co.comic.jump.proto.OriginalTitleGroup
	(*UpdatedTitle)(nil),        // 3: jp.co.comic.jump.proto.UpdatedTitle
	(TitleUpdateStatus)(0),      // 4: jp.co.comic.jump.proto.TitleUpdateStatus
}
var file_updated_title_group_proto_depIdxs = []int32{
	3, // 0: jp.co.comic.jump.proto.UpdatedTitleGroup.titles:type_name -> jp.co.comic.jump.proto.UpdatedTitle
	2, // 1: jp.co.comic.jump.proto.UpdatedTitleV2Group.title_groups:type_name -> jp.co.comic.jump.proto.OriginalTitleGroup
	3, // 2: jp.co.comic.jump.proto.OriginalTitleGroup.titles:type_name -> jp.co.comic.jump.proto.UpdatedTitle
	4, // 3: jp.co.comic.jump.proto.OriginalTitleGroup.titleUpdateStatus:type_name -> jp.co.comic.jump.proto.TitleUpdateStatus
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_updated_title_group_proto_init() }
func file_updated_title_group_proto_init() {
	if File_updated_title_group_proto != nil {
		return
	}
	file_title_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_updated_title_group_proto_rawDesc), len(file_updated_title_group_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_updated_title_group_proto_goTypes,
		DependencyIndexes: file_updated_title_group_proto_depIdxs,
		MessageInfos:      file_updated_title_group_proto_msgTypes,
	}.Build()
	File_updated_title_group_proto = out.File
	file_updated_title_group_proto_goTypes = nil
	file_updated_title_group_proto_depIdxs = nil
}
