// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: updated_title_list_view.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdatedTitleListView struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Groups        []*UpdatedTitleGroup   `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatedTitleListView) Reset() {
	*x = UpdatedTitleListView{}
	mi := &file_updated_title_list_view_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatedTitleListView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatedTitleListView) ProtoMessage() {}

func (x *UpdatedTitleListView) ProtoReflect() protoreflect.Message {
	mi := &file_updated_title_list_view_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatedTitleListView.ProtoReflect.Descriptor instead.
func (*UpdatedTitleListView) Descriptor() ([]byte, []int) {
	return file_updated_title_list_view_proto_rawDescGZIP(), []int{0}
}

func (x *UpdatedTitleListView) GetGroups() []*UpdatedTitleGroup {
	if x != nil {
		return x.Groups
	}
	return nil
}

var File_updated_title_list_view_proto protoreflect.FileDescriptor

const file_updated_title_list_view_proto_rawDesc = "" +
	"\n" +
	"\x1dupdated_title_list_view.proto\x12\x16jp.co.comic.jump.proto\x1a\x19updated_title_group.proto\"Y\n" +
	"\x14UpdatedTitleListView\x12A\n" +
	"\x06groups\x18\x01 \x03(\v2).jp.co.comic.jump.proto.UpdatedTitleGroupR\x06groupsb\x06proto3"

var (
	file_updated_title_list_view_proto_rawDescOnce sync.Once
	file_updated_title_list_view_proto_rawDescData []byte
)

func file_updated_title_list_view_proto_rawDescGZIP() []byte {
	file_updated_title_list_view_proto_rawDescOnce.Do(func() {
		file_updated_title_list_view_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_updated_title_list_view_proto_rawDesc), len(file_updated_title_list_view_proto_rawDesc)))
	})
	return file_updated_title_list_view_proto_rawDescData
}

var file_updated_title_list_view_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_updated_title_list_view_proto_goTypes = []any{
	(*UpdatedTitleListView)(nil), // 0: jp.co.comic.jump.proto.UpdatedTitleListView
	(*UpdatedTitleGroup)(nil),    // 1: jp.co.comic.jump.proto.UpdatedTitleGroup
}
var file_updated_title_list_view_proto_depIdxs = []int32{
	1, // 0: jp.co.comic.jump.proto.UpdatedTitleListView.groups:type_name -> jp.co.comic.jump.proto.UpdatedTitleGroup
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_updated_title_list_view_proto_init() }
func file_updated_title_list_view_proto_init() {
	if File_updated_title_list_view_proto != nil {
		return
	}
	file_updated_title_group_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_updated_title_list_view_proto_rawDesc), len(file_updated_title_list_view_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_updated_title_list_view_proto_goTypes,
		DependencyIndexes: file_updated_title_list_view_proto_depIdxs,
		MessageInfos:      file_updated_title_list_view_proto_msgTypes,
	}.Build()
	File_updated_title_list_view_proto = out.File
	file_updated_title_list_view_proto_goTypes = nil
	file_updated_title_list_view_proto_depIdxs = nil
}
