// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: user_tickets.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserTickets struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	CurrentTickets      uint32                 `protobuf:"varint,1,opt,name=current_tickets,json=currentTickets,proto3" json:"current_tickets,omitempty"`
	NextTicketTimestamp uint32                 `protobuf:"varint,2,opt,name=next_ticket_timestamp,json=nextTicketTimestamp,proto3" json:"next_ticket_timestamp,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *UserTickets) Reset() {
	*x = UserTickets{}
	mi := &file_user_tickets_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserTickets) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserTickets) ProtoMessage() {}

func (x *UserTickets) ProtoReflect() protoreflect.Message {
	mi := &file_user_tickets_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserTickets.ProtoReflect.Descriptor instead.
func (*UserTickets) Descriptor() ([]byte, []int) {
	return file_user_tickets_proto_rawDescGZIP(), []int{0}
}

func (x *UserTickets) GetCurrentTickets() uint32 {
	if x != nil {
		return x.CurrentTickets
	}
	return 0
}

func (x *UserTickets) GetNextTicketTimestamp() uint32 {
	if x != nil {
		return x.NextTicketTimestamp
	}
	return 0
}

var File_user_tickets_proto protoreflect.FileDescriptor

const file_user_tickets_proto_rawDesc = "" +
	"\n" +
	"\x12user_tickets.proto\x12\x16jp.co.comic.jump.proto\"j\n" +
	"\vUserTickets\x12'\n" +
	"\x0fcurrent_tickets\x18\x01 \x01(\rR\x0ecurrentTickets\x122\n" +
	"\x15next_ticket_timestamp\x18\x02 \x01(\rR\x13nextTicketTimestampb\x06proto3"

var (
	file_user_tickets_proto_rawDescOnce sync.Once
	file_user_tickets_proto_rawDescData []byte
)

func file_user_tickets_proto_rawDescGZIP() []byte {
	file_user_tickets_proto_rawDescOnce.Do(func() {
		file_user_tickets_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_tickets_proto_rawDesc), len(file_user_tickets_proto_rawDesc)))
	})
	return file_user_tickets_proto_rawDescData
}

var file_user_tickets_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_user_tickets_proto_goTypes = []any{
	(*UserTickets)(nil), // 0: jp.co.comic.jump.proto.UserTickets
}
var file_user_tickets_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_user_tickets_proto_init() }
func file_user_tickets_proto_init() {
	if File_user_tickets_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_tickets_proto_rawDesc), len(file_user_tickets_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_user_tickets_proto_goTypes,
		DependencyIndexes: file_user_tickets_proto_depIdxs,
		MessageInfos:      file_user_tickets_proto_msgTypes,
	}.Build()
	File_user_tickets_proto = out.File
	file_user_tickets_proto_goTypes = nil
	file_user_tickets_proto_depIdxs = nil
}
