// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: web_home_view_v4.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WebHomeViewV4 struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	TopBanners           []*Banner              `protobuf:"bytes,1,rep,name=top_banners,json=topBanners,proto3" json:"top_banners,omitempty"`
	Groups               []*UpdatedTitleV2Group `protobuf:"bytes,2,rep,name=groups,proto3" json:"groups,omitempty"`
	RankedTitles         []*TitleRankingGroup   `protobuf:"bytes,3,rep,name=ranked_titles,json=rankedTitles,proto3" json:"ranked_titles,omitempty"`
	Popup                *Popup                 `protobuf:"bytes,4,opt,name=popup,proto3" json:"popup,omitempty"`
	FeaturedTitleLists   []*TitleList           `protobuf:"bytes,5,rep,name=featured_title_lists,json=featuredTitleLists,proto3" json:"featured_title_lists,omitempty"`
	ServiceAnnouncements []*ServiceAnnouncement `protobuf:"bytes,6,rep,name=service_announcements,json=serviceAnnouncements,proto3" json:"service_announcements,omitempty"`
	MvBanner             *MVBanner              `protobuf:"bytes,7,opt,name=mv_banner,json=mvBanner,proto3" json:"mv_banner,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *WebHomeViewV4) Reset() {
	*x = WebHomeViewV4{}
	mi := &file_web_home_view_v4_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebHomeViewV4) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebHomeViewV4) ProtoMessage() {}

func (x *WebHomeViewV4) ProtoReflect() protoreflect.Message {
	mi := &file_web_home_view_v4_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebHomeViewV4.ProtoReflect.Descriptor instead.
func (*WebHomeViewV4) Descriptor() ([]byte, []int) {
	return file_web_home_view_v4_proto_rawDescGZIP(), []int{0}
}

func (x *WebHomeViewV4) GetTopBanners() []*Banner {
	if x != nil {
		return x.TopBanners
	}
	return nil
}

func (x *WebHomeViewV4) GetGroups() []*UpdatedTitleV2Group {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *WebHomeViewV4) GetRankedTitles() []*TitleRankingGroup {
	if x != nil {
		return x.RankedTitles
	}
	return nil
}

func (x *WebHomeViewV4) GetPopup() *Popup {
	if x != nil {
		return x.Popup
	}
	return nil
}

func (x *WebHomeViewV4) GetFeaturedTitleLists() []*TitleList {
	if x != nil {
		return x.FeaturedTitleLists
	}
	return nil
}

func (x *WebHomeViewV4) GetServiceAnnouncements() []*ServiceAnnouncement {
	if x != nil {
		return x.ServiceAnnouncements
	}
	return nil
}

func (x *WebHomeViewV4) GetMvBanner() *MVBanner {
	if x != nil {
		return x.MvBanner
	}
	return nil
}

type MVBanner struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageUrl      string                 `protobuf:"bytes,1,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	TitleGroups   *OriginalTitleGroup    `protobuf:"bytes,2,opt,name=title_groups,json=titleGroups,proto3" json:"title_groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MVBanner) Reset() {
	*x = MVBanner{}
	mi := &file_web_home_view_v4_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MVBanner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MVBanner) ProtoMessage() {}

func (x *MVBanner) ProtoReflect() protoreflect.Message {
	mi := &file_web_home_view_v4_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MVBanner.ProtoReflect.Descriptor instead.
func (*MVBanner) Descriptor() ([]byte, []int) {
	return file_web_home_view_v4_proto_rawDescGZIP(), []int{1}
}

func (x *MVBanner) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *MVBanner) GetTitleGroups() *OriginalTitleGroup {
	if x != nil {
		return x.TitleGroups
	}
	return nil
}

var File_web_home_view_v4_proto protoreflect.FileDescriptor

const file_web_home_view_v4_proto_rawDesc = "" +
	"\n" +
	"\x16web_home_view_v4.proto\x12\x16jp.co.comic.jump.proto\x1a\fbanner.proto\x1a\vpopup.proto\x1a\x1aservice_announcement.proto\x1a\x10title_list.proto\x1a\x16title_list_group.proto\x1a\x19updated_title_group.proto\"\x90\x04\n" +
	"\rWebHomeViewV4\x12?\n" +
	"\vtop_banners\x18\x01 \x03(\v2\x1e.jp.co.comic.jump.proto.BannerR\n" +
	"topBanners\x12C\n" +
	"\x06groups\x18\x02 \x03(\v2+.jp.co.comic.jump.proto.UpdatedTitleV2GroupR\x06groups\x12N\n" +
	"\rranked_titles\x18\x03 \x03(\v2).jp.co.comic.jump.proto.TitleRankingGroupR\frankedTitles\x123\n" +
	"\x05popup\x18\x04 \x01(\v2\x1d.jp.co.comic.jump.proto.PopupR\x05popup\x12S\n" +
	"\x14featured_title_lists\x18\x05 \x03(\v2!.jp.co.comic.jump.proto.TitleListR\x12featuredTitleLists\x12`\n" +
	"\x15service_announcements\x18\x06 \x03(\v2+.jp.co.comic.jump.proto.ServiceAnnouncementR\x14serviceAnnouncements\x12=\n" +
	"\tmv_banner\x18\a \x01(\v2 .jp.co.comic.jump.proto.MVBannerR\bmvBanner\"v\n" +
	"\bMVBanner\x12\x1b\n" +
	"\timage_url\x18\x01 \x01(\tR\bimageUrl\x12M\n" +
	"\ftitle_groups\x18\x02 \x01(\v2*.jp.co.comic.jump.proto.OriginalTitleGroupR\vtitleGroupsb\x06proto3"

var (
	file_web_home_view_v4_proto_rawDescOnce sync.Once
	file_web_home_view_v4_proto_rawDescData []byte
)

func file_web_home_view_v4_proto_rawDescGZIP() []byte {
	file_web_home_view_v4_proto_rawDescOnce.Do(func() {
		file_web_home_view_v4_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_web_home_view_v4_proto_rawDesc), len(file_web_home_view_v4_proto_rawDesc)))
	})
	return file_web_home_view_v4_proto_rawDescData
}

var file_web_home_view_v4_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_web_home_view_v4_proto_goTypes = []any{
	(*WebHomeViewV4)(nil),       // 0: jp.co.comic.jump.proto.WebHomeViewV4
	(*MVBanner)(nil),            // 1: jp.co.comic.jump.proto.MVBanner
	(*Banner)(nil),              // 2: jp.co.comic.jump.proto.Banner
	(*UpdatedTitleV2Group)(nil), // 3: jp.co.comic.jump.proto.UpdatedTitleV2Group
	(*TitleRankingGroup)(nil),   // 4: jp.co.comic.jump.proto.TitleRankingGroup
	(*Popup)(nil),               // 5: jp.co.comic.jump.proto.Popup
	(*TitleList)(nil),           // 6: jp.co.comic.jump.proto.TitleList
	(*ServiceAnnouncement)(nil), // 7: jp.co.comic.jump.proto.ServiceAnnouncement
	(*OriginalTitleGroup)(nil),  // 8: jp.co.comic.jump.proto.OriginalTitleGroup
}
var file_web_home_view_v4_proto_depIdxs = []int32{
	2, // 0: jp.co.comic.jump.proto.WebHomeViewV4.top_banners:type_name -> jp.co.comic.jump.proto.Banner
	3, // 1: jp.co.comic.jump.proto.WebHomeViewV4.groups:type_name -> jp.co.comic.jump.proto.UpdatedTitleV2Group
	4, // 2: jp.co.comic.jump.proto.WebHomeViewV4.ranked_titles:type_name -> jp.co.comic.jump.proto.TitleRankingGroup
	5, // 3: jp.co.comic.jump.proto.WebHomeViewV4.popup:type_name -> jp.co.comic.jump.proto.Popup
	6, // 4: jp.co.comic.jump.proto.WebHomeViewV4.featured_title_lists:type_name -> jp.co.comic.jump.proto.TitleList
	7, // 5: jp.co.comic.jump.proto.WebHomeViewV4.service_announcements:type_name -> jp.co.comic.jump.proto.ServiceAnnouncement
	1, // 6: jp.co.comic.jump.proto.WebHomeViewV4.mv_banner:type_name -> jp.co.comic.jump.proto.MVBanner
	8, // 7: jp.co.comic.jump.proto.MVBanner.title_groups:type_name -> jp.co.comic.jump.proto.OriginalTitleGroup
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_web_home_view_v4_proto_init() }
func file_web_home_view_v4_proto_init() {
	if File_web_home_view_v4_proto != nil {
		return
	}
	file_banner_proto_init()
	file_popup_proto_init()
	file_service_announcement_proto_init()
	file_title_list_proto_init()
	file_title_list_group_proto_init()
	file_updated_title_group_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_web_home_view_v4_proto_rawDesc), len(file_web_home_view_v4_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_web_home_view_v4_proto_goTypes,
		DependencyIndexes: file_web_home_view_v4_proto_depIdxs,
		MessageInfos:      file_web_home_view_v4_proto_msgTypes,
	}.Build()
	File_web_home_view_v4_proto = out.File
	file_web_home_view_v4_proto_goTypes = nil
	file_web_home_view_v4_proto_depIdxs = nil
}
